### ISSUE TITLE
install package as UNKNOWN

### ISSUE THREAD

**Issue by ovasgus** [juancarlospaco/faster-than-requests#10]
Im using MacOS 10.13.16 High Sierra
using python 3.6
and using the terminal with shell_plus of django extension with version 2.1.6
pip version 19.0.3

When I try to install it with pip using the command 
`pip install faster-than-requests --isolated --disable-pip-version-check --no-cache-dir --no-binary :all:` 
it install it as **unknown-0.0.0**

![imagen](https://user-images.githubusercontent.com/1707601/58132366-b623ba00-7be6-11e9-8ec6-33b062ae943f.png)

Al when I try to import the package it gives me `out of memory` and exit terminal

![imagen](https://user-images.githubusercontent.com/1707601/58132491-0bf86200-7be7-11e9-8a65-a6b98f342d29.png)

using the default shell of python gives the same result

![imagen](https://user-images.githubusercontent.com/1707601/58133206-f2581a00-7be8-11e9-8355-795b8f539e4d.png)

**Comment by juancarlospaco** [comment]
Yes, sometimes PIP can get buggy working with isolation, :crying_cat_face: 
try directly `git clone` the project, then run the `build.sh` and then `package.sh`, 
it will give you the ZIP package on the `/dist/` folder, that you can install it like locally.

Latest PIP version is `19.1.1`. It wont require Django.

**Comment by juancarlospaco** [comment]
We will remove Mac from the package on next version, since we can not test the install process properly.
