### ISSUE TITLE
No timeout in get2str, but works in get

### ISSUE THREAD

**Issue by machinexa2** [juancarlospaco/faster-than-requests#100]
Linux kali-linux 5.8.0-kali2-amd64 #1 SMP Debian 5.8.10-1kali1 (2020-09-22) x86_64 GNU/Linux

On this OS, using this version of faster_than_requests 
```
root@kali-linux:~/MachineYadav/My-Tools/JScanner# pip3 install faster_than_requests --upgrade
Collecting faster_than_requests
  Downloading faster_than_requests-3572925.zip (1.7 MB)
     |████████████████████████████████| 1.7 MB 883 kB/s 
Building wheels for collected packages: faster-than-requests
  Building wheel for faster-than-requests (setup.py) ... done
  Created wheel for faster-than-requests: filename=faster_than_requests-20.10.19-cp38-cp38-linux_x86_64.whl size=375728 sha256=c7bd70e9aaaa556186e780570404974558fab6400fb5598b39f050fb43cff77b
  Stored in directory: /root/.cache/pip/wheels/82/a5/27/5be278b3e6c10c522f3f0685a414a2d6f345966c3848c9e714
Successfully built faster-than-requests
Installing collected packages: faster-than-requests
  Attempting uninstall: faster-than-requests
    Found existing installation: faster-than-requests 20.9.28
    Uninstalling faster-than-requests-20.9.28:
      Successfully uninstalled faster-than-requests-20.9.28
Successfully installed faster-than-requests-20.10.19
root@kali-linux:~/MachineYadav/My-Tools/JScanner# date
Tue 20 Oct 2020 09:49:25 PM +0545
```
on this date `Tue 20 Oct 2020 09:49:25 PM +0545` , using latest version as currently downloaded i tried to use get2str('http://127.0.01/', timeout=5000) which errors out and tells 
```
>>> from faster_than_requests import get2str
>>> get2str('http://127.0.0.1:8080/', timeout = 5000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get2str() takes exactly 1 arguments (2 given)
>>> 
```
It takes 1 arg but 2 given.

**Comment by machinexa2** [comment]
One thing to note is that it works in get but fails in get2str

**Comment by machinexa2** [comment]
Fix:
Get has syntax of ```py
proc get*(url: string; user_agent: string = defUserAgent; max_redirects: int = 9; proxy_url: string = ""; proxy_auth: string = ""; timeout: int = -1; http_headers: openArray[tuple[key: string, val: string]] = @[("dnt", "1")]): Table[string, string] {.exportpy.} =
```
which makes it accept different headers, unfortunately get2str doesnt have
```
proc get2str*(url: sink string): string {.exportpy.} =
```

**Comment by juancarlospaco** [comment]
That is intended, it is a little faster, but has a little less options.

You can try setting the env variable `REQUESTS_TIMEOUT` to timeout with microseconds precision (multiply by 1000) before using `get2str()` and it should work.

**Comment by machinexa2** [comment]
Nice it works
