### ISSUE TITLE
Urlencode: Change + to %20

### ISSUE THREAD

**Issue by machinexa2** [juancarlospaco/faster-than-requests#101]
Urlencode changes spaces to + instead of %20, is it intended behaviour, %20 is more seen in urls than + so if its intended behaviour can we have a function urlencode_spc that uses %20 instead of +. If its not intended then you may fix it
Example:
```
>>> urlencode(' ')
'+'
```
Expectation:
```
>>> urlencode(' ')
'%20'
```

pip3 show faster_than_requests
Version: 20.10.19

**Comment by juancarlospaco** [comment]
`use_plus = True` or `use_plus = False` :slightly_smiling_face: :+1:
