### ISSUE TITLE
Urlparse should return tuple instead of list (Feature Request)

### ISSUE THREAD

**Issue by machinexa2** [juancarlospaco/faster-than-requests#102]
List [] takes more memory than tuple (), thus faster_than_requests.urlparse() should return tuple instead of list

**Comment by machinexa2** [comment]
```py
>>> from sys import getsizeof
>>> getsizeof(list())
56
>>> getsizeof(tuple())
40
>>>
```

**Comment by juancarlospaco** [comment]
- https://play.nim-lang.org/#ix=2CBw
- https://tio.run/##K6gsycjPM/7/PzO3IL@oRKG4spiLK7G4OBXC1ktPLSnOrErNT9NQiFYyVNJRUDICEcYgwgREmIIIMxBhDiIsQISlUqyCpoKtrYKhiQkOwzRIMEwTapiRxf//AA

:thinking:
