### ISSUE TITLE
Does or will faster-than-requests support persistent connections (sessions)?

### ISSUE THREAD

**Issue by SenTisso** [juancarlospaco/faster-than-requests#105]
I have discovered this [blog](https://julien.danjou.info/python-and-fast-http-clients/#persistent-connections) about faster HTTP clients in python and the author talks about _Persistent Connections_.

> **Persistent Connections**
The first optimization to take into account is the use of a persistent connection to the Web server. Persistent connections are a standard since HTTP 1.1 though many applications do not leverage them. This lack of optimization is simple to explain if you know that when using requests in its simple mode (e.g. with the get function) the connection is closed on return. To avoid that, an application needs to use a Session object that allows reusing an already opened connection.
> 
> Reusing the TCP connection to send out several HTTP requests offers a number of performance advantages:
> - Lower CPU and memory usage (fewer connections opened simultaneously).
> - Reduced latency in subsequent requests (no TCP handshaking).
> - Exceptions can be raised without the penalty of closing the TCP connection.

This looks like a pretty neat optimization.
It is implemented with `requests` like this:
```
import requests
session = requests.Session()
session.get("http://example.com")
# Connection is re-used
session.get("http://example.com")
```
[Request's documentation about session usage](https://requests.readthedocs.io/en/master/user/advanced/)

Does `faster-than-requests` _(totally awesome library btw)_ support sessions? Or is this library gonna support them in the near future?

I have noticed this sentence in your `README.md` and I would be willing to donate something to you guys, but since I'm a single person that uses this library for some personal projects, then I have no idea how much is enough :/

> Become a Sponsor and help improve this library with the features you want!

**Comment by juancarlospaco** [comment]
No and I do not know if it will support it sorry.
It is not a drop-in replacement to any pre-existent software.

**Comment by kootenpv** [comment]
I had not realized this, but this is a big reason why I can't be using it if it closes the connection everytime.

In the end, it makes python requests faster if you have to do more than 1 call to the same domain:

### faster.py

```python
import faster_than_requests
import time
import requests

z=faster_than_requests.get2str("https://httpbin.org/")

t1 = time.time()
z=faster_than_requests.get2str("https://httpbin.org/")
print("faster_than_requests", time.time() - t1)

s = requests.Session()
s.get("https://httpbin.org/")
t1 = time.time()
s.get("https://httpbin.org/")
print("requests", time.time() - t1)
```

```bash
pascal@archbook:/home/pascal$ python faster.py 
faster_than_requests 0.12139439582824707
requests 0.11539411544799805
```

**Comment by juancarlospaco** [comment]
It has its internal session, that is not passed back to Python virtual machine,
because the more stuff you pass from Compiled to Interpreted the slower it goes,
because machine code binary is faster than virtual machine interpreter that reads your code line by line as text,
is like converting a C program to NodeJS and expect it to go faster.

For more speed you do it from the Nim side, 
the more stuff you move from the interpreter side to the compiled side the faster it goes, so is really up to you,
hardcode some of your arguments on the Nim source it already goes faster,
Nim has Python syntax, just need to import it 
https://github.com/Yardanico/nimpylib

**Comment by juancarlospaco** [comment]
`0.12` Vs `0.11` does not look bad tho,
considering the other project has decades of development, several Sponsors, dedicated resources,
an army of contributors, lots of third party dependencies, and this is 1 dev on free time  :)

**Comment by kootenpv** [comment]
Of course, I understand! Just trying to help point out the areas that would make it kick ass... 

For scraping or building an API, we'd often hit the same domain more than once, so using a `Session` will be the biggest speed gain you can get.

I was considering maybe we could use something like:

    faster_than_requests.set_session(session=True, keep_alive=60)

Hmm, maybe it is possible to create the connection in Python and then use it from Nim code?

**Comment by juancarlospaco** [comment]
But we have web scrapers already, I need to optimize some of them but is a starting point.

**Comment by kootenpv** [comment]
Yea I noticed the scraping code. But I guess no connection is kept alive for them?

How about hitting the same URL every 0.2 seconds with slightly different data (basically like an API client)?

**Comment by kootenpv** [comment]
I tried to look in the Nim httpclient documentation but I do not see any mention of persistent connections :(

**Comment by kootenpv** [comment]
I tried cloning repo and trying to compile but not sure how to start 😅

**Comment by juancarlospaco** [comment]
`nim c -d:ssl --app:lib --out:faster_than_requests.so faster_than_requests.nim` slow

`nim c -d:ssl -d:danger --app:lib --out:faster_than_requests.so faster_than_requests.nim` fast

**Comment by kootenpv** [comment]
```
pascal@archbook:/home/.../faster/faster-than-requests$ nim c -d:ssl -d:danger --app:lib --out:faster_than_requests.so faster_than_requests.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
....
Error: cannot open 'faster_than_requests.nim'
```

**Comment by juancarlospaco** [comment]
The point is that is just Marketing.

`Keep-Alive: X` is just an HTTP Header, like any other, is not magical.
Just set the header `Keep-Alive:` and call it a day. DotNotTrack is also a header.
HTTP over the wire is just 1 URL string, 1 Body string, 1 Header string, nothing more, you can not attach some magic to it.
Make a function `use_super_magical_session()` that sets the `Keep-Alive:` header.

**Comment by kootenpv** [comment]
Oh... haha. Of course... HTTP client should be stateless.

**Comment by juancarlospaco** [comment]
[File is on the repo](https://github.com/juancarlospaco/faster-than-requests/blob/master/src/faster_than_requests.nim) 

You must be on the same folder to call the command or use full path to the file.

**Comment by juancarlospaco** [comment]
https://github.com/nim-lang/Nim/wiki/Nim-for-Python-Programmers#table-of-contents

**Comment by kootenpv** [comment]
Oh - had not realized should be called from `src/` - thanks!
