### ISSUE TITLE
Can't disable redirects.

### ISSUE THREAD

**Issue by ravensoracle** [juancarlospaco/faster-than-requests#11]
I don't know how to disable redirects, maxRedirects >= 1, but I need set `maxRedirects=0`. Add this feature, please, like in requests `allow_redirects=False`

**Comment by juancarlospaco** [comment]
[It was a Documentation error,](https://github.com/juancarlospaco/faster-than-requests/commit/cedab93b92d1c1c91e9a6de615d85739e4ce50fd) its actually possible, you can set the max redirects to `0`.

Bash Terminal:
```bash
export requests_maxredirects = 0
```
:slightly_smiling_face:
