### ISSUE TITLE
Error during installing on termux

### ISSUE THREAD

**Issue by tathastu871** [juancarlospaco/faster-than-requests#117]
# Before you open a new bug

- 32 Bit is not supported.
- You must have 64 Bit Python 3.
- You must have 64 Bit GCC Compiler.
- You must have 64 Bit Operating System.
- Windows older than Windows 10 is not supported.
- ARM support is Experimental, you may need to compile manually.
- Mac OSX support is Experimental, you may need to compile manually.
- Alpine Linux support is Experimental, you may need to compile manually.

```
ERROR: Requested faster_than_requests from https://files.pythonhosted.org/packages/8f/f0/11be00462bf64c327f73fb2696fc8f0c9e0cd495369569f0f0d6cded5c55/faster_than_requests-3572925.zip#sha256=24f9b9d9fb81dbfac8af4ff3672bed0d99b566e7d64f4efeb8bf96932a4700d4 has different version in metadata: '20.10.19'
```

**Comment by juancarlospaco** [comment]
Try:

```
pip install faster-than-requests==c66bdc9 --no-binary :all:
```

I do not know whats Termu, but only Windows, Linux, OS X are supported, for others you have to compile yourself.
