### ISSUE TITLE
How is this tool comparing with httpx?

### ISSUE THREAD

**Issue by wuyudi** [juancarlospaco/faster-than-requests#118]
I recently use `httpx` and `pycurl`, and see this while searching for `requests`.

While I didn't see the comparison with httpx on README.md. So I am much curious. Since it looks shorter than those mentioned above.👀

**Comment by juancarlospaco** [comment]
No idea, when it started there was no httpx.
Has some unique features, like no garbage collector, compiled instead of interpreted, 0 dependency, single-file, few LOC, etc.

Feel free to use whatever you feel like using.
:)
