### ISSUE TITLE
nimpy.ValueError: Unexpected error encountered: invalid integer

### ISSUE THREAD

**Issue by 4A47** [juancarlospaco/faster-than-requests#12]
First off, thanks for creating this, really nice speed, im trying to replace requests with this library in some of my code but having issue with simple UserAgent which is necessary to get a correct response in many sites.

First I tried to pass it in the tuple like this

`
r = req.requests(
        url, "get", "", [("UserAgent", "Mozilla/5.0")]
)
`

but the response code is 400.

then I tried with the explicit useragent in requests2 which produced the error.

`
r = req.requests2(
        url, "get", "", [("key", "value")], userAgent="Mozilla/5.0"
)
`

A sidenote, wouldnt it be better if there was a default for body and header rather than requiring it? Would look much cleaner.

Thanks.

**Comment by juancarlospaco** [comment]
Please check this issue, I think is the same https://github.com/juancarlospaco/faster-than-requests/issues/9#issue-446586366

Try using https://httpbin.org (for testing, it behaves correctly).

Try using the `requests_useragent` environment variable: https://github.com/juancarlospaco/faster-than-requests#low-level-api-extras

Please consider that User Agent was never meant to be an Authentication mechanism,
I can not fix others doing weird things with the very well known standards they must follow, not my bug.

We will try to improve the API on next versions.
Let me know if thats good enough for you.

**Comment by 4A47** [comment]
I understand, serving different html based on user agents is not advised but the fact is, it is widely done, in most cases to try and restrict scraping. Its a shame because maybe 75% of the time I need the user agent, so I will just use your library for the occasions when I only need to post some body data.

Thanks.

**Comment by juancarlospaco** [comment]
Ok, we will try to improve the user agent on the next version, 
the environment variable lets you set it anyways, but I understand what you say, I get that feedback for next improvements.

:slightly_smiling_face: :+1:
