### ISSUE TITLE
Fix dependencies for Python 3.9

### ISSUE THREAD

**Issue by ConConDiscord** [juancarlospaco/faster-than-requests#120]
I am using Python 3.9.1 on Windows 10 64-bit, and there is a issue with dependencies because of the new wheel. 

`running install
running build
running build_ext
building 'faster_than_requests' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/`
    
I believe this is a dependency issue.

**Comment by juancarlospaco** [comment]
No, not a dependency issue, not even a bug, you need a compiler to compile, you need to install MSVC compiler,
it gives you instructions there, click the link, download and install it full, reboot and try again.
Linux and Mac comes with compiler builtin.
