### ISSUE TITLE
Windows installation 

### ISSUE THREAD

**Issue by AlexRMU** [juancarlospaco/faster-than-requests#121]
![win-compile](https://user-images.githubusercontent.com/1189414/63147831-b8bf6100-bfd5-11e9-9e6e-91d61040f139.png "")

vs

`pip install requests`

It is sad. And nothing can be changed? 
(The repository is not installed by the link and does not write anything, you need to download nim from the official website)

**Comment by AlexRMU** [comment]
You also need to add to the instruction that src/faster_than_requests.pyd should be moved to a folder from PYTHONPATH, for example \Python\Python39\Lib\

**Comment by juancarlospaco** [comment]
I do not understand what you mean,
It is not mandatory to move the .pyd,
I just always use it from the same folder as the .py file.

But if you dont like it, is really not my bug,
Open a bug to Python proposing your preferred folder.

I dont understand, why are you sad.

**Comment by AlexRMU** [comment]
I moved .pyd to \Python 39\Lib\ and it can now be imported like any other package. And in the instructions there is nothing about it at all.

**Comment by juancarlospaco** [comment]
It is not mandatory, I never move it.
