### ISSUE TITLE
Error installing using pip

### ISSUE THREAD

**Issue by amtsgv** [juancarlospaco/faster-than-requests#122]
Hello,
trying to install this via command `pip install faster-than-requests` but i receive an error, are you aware of any workarounds to this?
![image](https://user-images.githubusercontent.com/63860086/104490847-0d577900-55da-11eb-9cc1-12f7213c99f6.png)

**Comment by JoeBarouneD** [comment]
How did you manage to install it ?

**Comment by amtsgv** [comment]
> How did you manage to install it ?

i did not, just accidentally made 2 issues.

**Comment by juancarlospaco** [comment]
You have to add these options to the PIP command:
` --disable-pip-version-check --no-binary :all: --use-deprecated=legacy-resolver `

Example:
`python3.8 -m pip install faster-than-requests==c66bdc9 --no-binary :all: --use-deprecated=legacy-resolver`


Why?, I dunno, not my bug, PIP sometimes is weird but they dont care, sorry. :shrug:
