### ISSUE TITLE
Japronto

### ISSUE THREAD

**Issue by AlexRMU** [juancarlospaco/faster-than-requests#124]
Found something you might be interested in:

[![screenshot](https://github.com/squeaky-pl/japronto/blob/master/benchmarks/results.png?raw=true "")]()

https://github.com/squeaky-pl/japronto

**Comment by juancarlospaco** [comment]
Thats a server, not a client, unrelated sorry. :shrug:

**Comment by AlexRMU** [comment]
I mean, it's based on uvloop (`Ultra fast asyncio event loop`) and other and you can at least just watch it
?

**Comment by juancarlospaco** [comment]
I am reading it for real. We dont need any dependencies, once compiled you dont need anything else.
:)
