### ISSUE TITLE
It's posting 6 request at once

### ISSUE THREAD

**Issue by kigochen** [juancarlospaco/faster-than-requests#126]
# Before you open a new bug

- 32 Bit is not supported.
- You must have 64 Bit Python 3.
- You must have 64 Bit GCC Compiler.
- You must have 64 Bit Operating System.
- Windows older than Windows 10 is not supported.
- ARM support is Experimental, you may need to compile manually.
- Mac OSX support is Experimental, you may need to compile manually.
- Alpine Linux support is Experimental, you may need to compile manually.
- Termux support is Experimental, you may need to compile manually.

When I just use 

```
import faster_than_requests as requests
requests.post(url, json_request_body, http_headers=[("Content-type", "application/json")])
```
And I see it actually post 6 request to the restful service

**Comment by juancarlospaco** [comment]
Can not reproduce. Please provide full real source code to reproduce.

```console
$ python -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
127.0.0.1 - "GET / HTTP/1.1" 200 -
^C
Keyboard interrupt received, exiting.

$ 
```

---

```python
import faster_than_requests

print(
  faster_than_requests.get(url = "http://0.0.0.0:8000", http_headers = [("Content-type", "application/json")])
)
```

```
$ python3 example.py
```

Same with POST.
Try using argument with names on all arguments.
