### ISSUE TITLE
seting header dont work 

### ISSUE THREAD

**Issue by just-taki** [juancarlospaco/faster-than-requests#128]
# Before you open a new bug

- 32 Bit is not supported.
- You must have 64 Bit Python 3.
- You must have 64 Bit GCC Compiler.
- You must have 64 Bit Operating System.
- Windows older than Windows 10 is not supported.
- ARM support is Experimental, you may need to compile manually.
- Mac OSX support is Experimental, you may need to compile manually.
- Alpine Linux support is Experimental, you may need to compile manually.
- Termux support is Experimental, you may need to compile manually.

**Comment by just-taki** [comment]
when i set header 
	faster_than_requests.set_headers([("Content-Type", "application/x-www-form-urlencoded"),("das","dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd")])        

then send  a post request
['{\n  "args": {}, \n  "data": "{query:van+helsing\'}", \n  "files": {}, \n  "form": {}, \n  "headers": {\n    "Content-Length": "20", \n    "Dnt": "1", \n    "Host": "httpbin.org", \n    "User-Agent": "Nim httpclient/1.4.2", \n    "X-Amzn-Trace-Id": "Root=1-6013fe0a-64dc1f2d359939200570c2cc"\n  }, \n  "json": null, \n  "origin": "105.111.102.0", \n  "url": "https://httpbin.org/post"\n}\n', 'application/json', '200 OK', '1.1', 'https://httpbin.org/post', '372', '{"server": @["gunicorn/19.9.0"], "content-length": @["372"], "access-control-allow-credentials": @["true"], "content-type": @["application/json"], "date": @["Fri, 29 Jan 2021 12:22:34 GMT"], "access-control-allow-origin": @["*"], "connection": @["keep-alive"]}']


the header are not setted  
how to fix

**Comment by just-taki** [comment]
when i set header
faster_than_requests.set_headers([("Content-Type", "application/x-www-form-urlencoded"),("das","dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd")])

then send a post request
['{\n "args": {}, \n "data": "{query:van+helsing'}", \n "files": {}, \n "form": {}, \n "headers": {\n "Content-Length": "20", \n "Dnt": "1", \n "Host": "httpbin.org", \n "User-Agent": "Nim httpclient/1.4.2", \n "X-Amzn-Trace-Id": "Root=1-6013fe0a-64dc1f2d359939200570c2cc"\n }, \n "json": null, \n "origin": "", \n "url": "https://httpbin.org/post"\n}\n', 'application/json', '200 OK', '1.1', 'https://httpbin.org/post', '372', '{"server": @["gunicorn/19.9.0"], "content-length": @["372"], "access-control-allow-credentials": @["true"], "content-type": @["application/json"], "date": @["Fri, 29 Jan 2021 12:22:34 GMT"], "access-control-allow-origin": @["*"], "connection": @["keep-alive"]}']

the header are not setted
how to fix

**Comment by juancarlospaco** [comment]
`set_header()` is for the functions that do not have a `http_headers` argument, 
you can pass the headers as an argument of the functions, like `http_headers = [("key", "value")]`,
this is mentioned on the documentation.

```python
from faster_than_requests import post
print(
  post(url = "http://httpbin.org/post", http_headers = [("key", "value")] )
)
```
