### ISSUE TITLE
'PUT' requests stopping loop

### ISSUE THREAD

**Issue by lxi1400** [juancarlospaco/faster-than-requests#135]
# Before you open a new bug

- 32 Bit is not supported.
- You must have 64 Bit Python 3.
- You must have 64 Bit GCC Compiler.
- You must have 64 Bit Operating System.
- Windows older than Windows 10 is not supported.
- ARM support is Experimental, you may need to compile manually.
- Mac OSX support is Experimental, you may need to compile manually.
- Alpine Linux support is Experimental, you may need to compile manually.
- Termux support is Experimental, you may need to compile manually.

While trying to do a for data in data loop, put requests stop the entire loop. patch, put, etc all work, but put will stop the loop and end the program.

**Comment by lxi1400** [comment]
Example:

`
for i in range(4):
    r = requests.get(url="https://google.com")

Works fine, but not

for i in range(4):
    r = requests.put(url="https://google.com", body="")
    print(r)
    
Which just stops the whole loop  
`

**Comment by lxi1400** [comment]
I got for range to kinda work, but doing something like

```
list = ["value one", "value two"]


for i in list:
  r = requests.put(url="https://google.com/{i}, body=""_
  print(r)
```

Will stop after one item in the list, even when using something like try: or  continue

**Comment by juancarlospaco** [comment]
Can not reproduce

![temp-ftr](https://user-images.githubusercontent.com/1189414/107643938-88519500-6c55-11eb-857b-9e618059d64a.png)

**Comment by juancarlospaco** [comment]
> ```
> list = ["value one", "value two"]
> 
> 
> for i in list:
>   r = requests.put(url="https://google.com/{i}, body=""_
>   print(r)
> ```

You can not name a list literally `list`, you are breaking Python by doing so, is just how Python is.

I suspect you are overwriting Python names somewhere, that makes Python behave unpredictable without warning.

**Comment by lxi1400** [comment]
> > ```
> > list = ["value one", "value two"]
> > 
> > 
> > for i in list:
> >   r = requests.put(url="https://google.com/{i}, body=""_
> >   print(r)
> > ```
> 
> You can not name a list literally `list`, you are breaking Python by doing so, this is not my bug, is just how Python is.
> 
> The string URL is also wrong, thats not how string formatting works on Python.
> 
> I suspect you are overwriting Python names somewhere, that makes Python behave unpredictable without warning.
> 
> Can not reproduce
> 
> ![temp-ftr](https://user-images.githubusercontent.com/1189414/107645704-c780e580-6c57-11eb-8116-4fcccd757327.png)
> 
> Check all your names on all your code and rename to use descriptive names that are not similar to Python internal names.
> 
> Reinstall the library and try again.

my bad, the last code i sent was more of a example then actually working


try this


```python

ids = ["test", "test2"]

for randomid in ids:
    try:
        r = requests.put(url=f"https://google.com/{randomid}", body = str(""))
        print(r)
        continue
    except:
        continue
```

for me, it'll just stop

**Comment by juancarlospaco** [comment]
Can not reproduce

![temp-ftr](https://user-images.githubusercontent.com/1189414/107658314-c4d8bd00-6c64-11eb-9219-9a435a0348d5.png)

Are you running from the system command line terminal window?, some "alternative" IDEs and Terminals are buggy.

**Comment by lxi1400** [comment]
> Can not reproduce
> 
> ![temp-ftr](https://user-images.githubusercontent.com/1189414/107658314-c4d8bd00-6c64-11eb-9219-9a435a0348d5.png)
> 
> Are you running from the system command line terminal window?, some "alternative" IDEs and Terminals are buggy.

yes, i am running from the command line, 

here is a example that i've tried and still doesnt work (banning a blacklisted member from a discord server)



```python

import faster_than_requests as requests

blacklisted_members = ["381458939700707329","775591169626865665","155149108183695360","159985870458322944"]
headers = [('Authorization', f"Bot ODA5NDQ3ODAyMzExNTQwODAw.YCVPAg.zcE9F3p3PmnItt4EqR5eedtT2JU")] # test token, doesnt matter if leaked

# attempting to ban the blacklisted members from a server before they can do harm
for id in blacklisted_members:
    try:
        print(id)
        r = requests.put(url=f"https://discordapp.com/api/v8/guilds/809448289828339742/bans/{id}", body = str(""), http_headers=headers)
        print(r)
        continue #only does it one time 
    except:
        continue
```

**Comment by juancarlospaco** [comment]
`id` is also a Python builtin, better use another name.

**Comment by juancarlospaco** [comment]
Maybe just try using the source code instead...

Assuming you already have Windows 64Bit and CPython 3.9 64Bit:

- https://gitforwindows.org (Not really mandatory, but useful, so you dont have to download files by hand)
- You MUST reboot the PC after installing Git.

![windows-compile](https://user-images.githubusercontent.com/1189414/107665391-26e8f080-6c6c-11eb-9fa1-742265c1d57b.png)

Commands in order to copy & paste:
- `pip install pip --upgrade`
- `pip install choosenim_install`
- `pip install nimble_install --install-option="--nimble=nimpy"`
- `git clone https://github.com/juancarlospaco/faster-than-requests.git`
- `cd faster-than-requests`
- `cd src`
- `nim c -d:ssl -d:danger -d:flto --gc:arc --app:lib --out:faster_than_requests.pyd faster_than_requests.nim`
- Copy `faster_than_requests.pyd` on the same folder as the `.py` file that should import it, it is ready for use.

**Comment by lxi1400** [comment]
> `id` is also a Python builtin, better use another name.

i've chaned the name and it still will stop after one request 

> Maybe just try using the source code instead...
> 
> Assuming you already have Windows 64Bit and CPython 3.9 64Bit:
> 
> * https://gitforwindows.org (Not really mandatory, but useful, so you dont have to download files by hand)
> * You MUST reboot the PC after installing Git.
> 
> ![windows-compile](https://user-images.githubusercontent.com/1189414/107665391-26e8f080-6c6c-11eb-9fa1-742265c1d57b.png)
> 
> Commands in order to copy & paste:
> 
> * `pip install pip --upgrade`
> * `pip install choosenim_install`
> * `pip install nimble_install --install-option="--nimble=nimpy"`
> * `git clone https://github.com/juancarlospaco/faster-than-requests.git`
> * `cd faster-than-requests`
> * `cd src`
> * `nim c -d:ssl -d:danger -d:flto --gc:arc --app:lib --out:faster_than_requests.pyd faster_than_requests.nim`
> * Copy `faster_than_requests.pyd` on the same folder as the `.py` file that should import it, it is ready for use.

I already have done this, because pip was being a pain again :(

**Comment by lxi1400** [comment]
it's odd because when the request is unsuccessful (missing permissions, bad requests, etc) it will keep going in the loop, but when the request is successful it stops.

**Comment by juancarlospaco** [comment]
![temp-ftr3](https://user-images.githubusercontent.com/1189414/107673641-f0fc3a00-6c74-11eb-8eeb-29099257f34e.png)

Typo on your code?, Antivirus blocking it ?.

**Comment by lxi1400** [comment]
> ![temp-ftr3](https://user-images.githubusercontent.com/1189414/107673641-f0fc3a00-6c74-11eb-8eeb-29099257f34e.png)
> 
> Typo on your code?, Antivirus blocking it ?, try PUT but on this URL https://httpbin.org/put ?.

works fine when i try that, but when i use the code below, it will send one successful request, then stop the whole program. not an issue with my antivirus.

```python
import faster_than_requests as requests

blacklisted_members = ["381458939700707329","775591169626865665","155149108183695360","159985870458322944"]
headers = [('Authorization', f"Bot ODA5NDQ3ODAyMzExNTQwODAw.YCVPAg.zcE9F3p3PmnItt4EqR5eedtT2JU")] # test token, doesnt matter if leaked

# attempting to ban the blacklisted members from a server before they can do harm
for memb in blacklisted_members:
    try:
        print(memb)
        r = requests.put(url=f"https://discordapp.com/api/v8/guilds/809448289828339742/bans/{memb}", body = str(""), http_headers=headers)
        print(r)
        continue #only does it one time 
    except:
        continue
```

**Comment by juancarlospaco** [comment]
If you do the 3 PUT requests **without the `for` loop** repeating the `put()` call 3 times, it works ?.
(I know it wont scale, I am asking to troubleshoot).

**Comment by lxi1400** [comment]
> If you do the 3 PUT requests **without the `for` loop** repeating the `put()` call 3 times, it works ?.
> (I know it wont scale, I am asking to troubleshoot).

no, even without the for loop and just a put request on each line, even with the id hardcoded, it will only send one post request then exit

**Comment by juancarlospaco** [comment]
But if you try with https://httpbin.org/put it works ?.
Thats even more weird. :thinking:

**Comment by lxi1400** [comment]
> But if you try with https://httpbin.org/put it works ?.
> Thats even more weird. 🤔

yeah it works with httpbin but not with my code, it seems that if the request i make is invaild, then it keeps looping, but if its successful, then it just stops

**Comment by juancarlospaco** [comment]
Maybe theres a bug on the server and sends broken responses ?.

Otherwise it should fail on httpbin too...

**Comment by lxi1400** [comment]
> Maybe theres a bug on the server and sends broken responses ?.
> 
> Otherwise it should fail on httpbin too...

but why would the whole program just end,

**Comment by lxi1400** [comment]
could it maybe be because the response status code is 204?

**Comment by juancarlospaco** [comment]
Heres a simple HTTP Server that responds `204` to everything including `PUT`, 
try it on your local, run the server on one terminal and leave it running,
run the Python script on another terminal so the script makes `PUT`  to the local server and check if it crashes.

## Server 

```nim
import asynchttpserver, asyncdispatch
waitFor newAsyncHttpServer().serve(Port 5000, proc (r: Request) {.async.} = await r.respond(Http204, """{"key":"value"}"""))
```

- `nim r server.nim`

## Client

```python
import faster_than_requests
for x in ["test", "test2"]:
  print(faster_than_requests.put(url = f"http://127.0.0.1:5000/{x}", body = ""))
```

- `python file.py`

If it crashes is a bug on the library with the http status 204.
If it does not crash, bug on the server you are trying to PUT.

**Comment by lxi1400** [comment]
> Heres a simple HTTP Server that responds `204` to everything including `PUT`,
> try it on your local, run the server on one terminal and leave it running,
> run the Python script on another terminal so the script makes `PUT` to the local server and check if it crashes.
> 
> ## Server
> ```nim
> import asynchttpserver, asyncdispatch
> waitFor newAsyncHttpServer().serve(Port 5000, proc (r: Request) {.async.} = await r.respond(Http204, """{"key":"value"}"""))
> ```
> 
> * `nim r server.nim`
> 
> ## Client
> ```python
> import faster_than_requests
> for x in ["test", "test2"]:
>   print(faster_than_requests.put(url = f"http://127.0.0.1:5000/{x}", body = ""))
> ```
> 
> * `python client.py`
> 
> If it crashes is a bug on the library with the http status 204.
> If it does not crash, bug on the server you are trying to PUT.

yes, when running the client.py, it just crashes

**Comment by juancarlospaco** [comment]
Can you repeat the compilation but with this command ?.

- `nim c -d:ssl --app:lib --out:faster_than_requests.pyd faster_than_requests.nim`

...and try again. 
I am running out of ideas, Python should not exit the program, theres no code to exit on the library, worse case it should print an error on the terminal but not exit.

**Comment by lxi1400** [comment]
> Can you repeat the compilation but with this command ?.
> 
> * `nim c -d:ssl --app:lib --out:faster_than_requests.pyd faster_than_requests.nim`
> 
> ...and try again.
> I am running out of ideas, Python should not exit the program, theres no code to exit on the library, worse case it should print an error on the terminal but not exit.

this time, it either exists out, or just freezes and doesnt continue

**Comment by lxi1400** [comment]
i sent you some code earlier, you can try to use it and see if it workes for you.

**Comment by juancarlospaco** [comment]
![temp-ftr](https://user-images.githubusercontent.com/1189414/107713958-1e63da80-6cab-11eb-9254-c44cdb8080d0.png)

**Comment by lxi1400** [comment]
ah, so it's a issue with my machine @juancarlospaco? if so, how should i go about fixing it

**Comment by juancarlospaco** [comment]
Maybe just run it inside WSL or Docker ?.
Everyone is using Docker nowadays.
:)

**Comment by lxi1400** [comment]
> Maybe just run it inside WSL or Docker ?.
> Everyone is using Docker nowadays.
> :)

hmm, but how would you use the pyd in WSL (ive never really done this kinda stuff before)

**Comment by juancarlospaco** [comment]
The same way you done in Windows, 
the only thing that changes is the file extension `faster_than_requests.pyd` :arrow_right: `faster_than_requests.so`.

**Comment by lxi1400** [comment]
`faster-than-requests/src/faster_than_requests.nim.cfg(11, 3) Error: 'none', 'boehm' or 'refc' expected, but 'orc' found` when attempting to run `nim c -d:ssl --app:lib --out:faster_than_requests.so faster_than_requests.nim` on WSL

**Comment by juancarlospaco** [comment]
Old version of the compiler, `nim --version` should say `1.4.2`.

**Comment by lxi1400** [comment]
how can i go about updating it?

**Comment by juancarlospaco** [comment]
```
curl https://nim-lang.org/choosenim/init.sh -sSf | sh
```
