### ISSUE TITLE
GET headers

### ISSUE THREAD

**Issue by iLoooordFx** [juancarlospaco/faster-than-requests#136]
How do i use headers with get?

`r = requests.get('http://example.com/', http_headers=[{"User-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64)","Authorization": "Bearer "+token}])`

**Comment by juancarlospaco** [comment]
It is Ok, but is not with `{` `}`, it is a List of Tuples,
List can be any length, Tuple is always length 2, like `("key", "value")`.

Why?; It is more lightweight than a dictionary, it is immutable because Tuple can not change, but List length can change.

```python
http_headers = [
  ("key", "value"),
  ("other", "value2"),
]
```

:)
