### ISSUE TITLE
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

### ISSUE THREAD

**Issue by hectormoreno404** [juancarlospaco/faster-than-requests#14]
After send a couple of hundreds request to the same address I get this error message

`requests.setHeaders(headers)`
`while True:`
`contador = contador +1`
`r = requests2.get2str("http://mockbin.org/bin/42807fa1-bd2b-4f2d-91b5-f30608c6a2dc")`
`print (contador)`
![Captura](https://user-images.githubusercontent.com/13341467/60772187-d0dfbe80-a0c0-11e9-9f9d-88cc359fc325.PNG)

Gracias por todo esto!

**Comment by juancarlospaco** [comment]
- **Try Compiling it from Sources:**

![win-compile](https://user-images.githubusercontent.com/1189414/63147831-b8bf6100-bfd5-11e9-9e6e-91d61040f139.png "Git Clone and Compile on Windows 10 with only Git and Nim installed, just 2 commands!")
:slightly_smiling_face: :+1:
