### ISSUE TITLE
ImportError: faster_than_requests.so: undefined symbol: __builtin_saddll_overflow

### ISSUE THREAD

**Issue by FractalMatt** [juancarlospaco/faster-than-requests#142]
Using python version 3.9.2
OS: CentOS 7.5.1804
64 bit python and OS and gcc
gcc (GCC) 10.2.0

I run my program and get the following error.

Traceback (most recent call last):
  File "/home/centos/mczarnek/parser/src/initializer.py", line 3, in <module>
    import grab_info
  File "/home/centos/mczarnek/parser/src/grab_info.py", line 1, in <module>
    import RPC_Caller
  File "/home/centos/mczarnek/parser/src/RPC_Caller.py", line 2, in <module>
    import faster_than_requests as requests
ImportError: /home/centos/.local/lib/python3.9/site-packages/faster_than_requests.so: undefined symbol: __builtin_saddll_overflow

Looks like the server I'm running on doesn't support a built-in gcc function.. is it possible to get around this one? Is this a nim issue or faster-than-requests?

Thanks.

**Comment by juancarlospaco** [comment]
The GCC version is too old, or the distro compiles it in a really weird way, but yeah theres a problem with your systems GCC.

Not much I can do from this side, not my bug, looks like a Distro/package bug.

**Comment by FractalMatt** [comment]
Apparently, you can use this flag when building in nim
-d:nimEmulateOverflowChecks

Probably very slightly faster when not using that flag but would support more people.  Apparently, this error is a fairly common nim error.

My advice would be try running it with and without that flag and benchmark to see if the speedup is actually worth it, it isn't for me given it doesn't work.

**Comment by FractalMatt** [comment]
Trying to compile this on Linux myself so I can use that check. I tried compiling to .pyd.. but apparently, that's windows only.  Would you happen to have the compilation for Linux instruction somewhere in case I want to use this with the -d:nimEmulateOverflowChecks set for Linux?  Thanks again Juan.

**Comment by juancarlospaco** [comment]
- Linux :arrow_right: `*.so`.
- Mac :arrow_right: `*.so`.
- Windows :arrow_right: `*.pyd`.

Thats how it works, we did not invent that, thats just how each operating system is.

The only thing that  should be changed in the compilation is the file extension, from `.pyd` to `.so`.
