### ISSUE TITLE
Unexpected error encountered: Too many open files

### ISSUE THREAD

**Issue by g1noox** [juancarlospaco/faster-than-requests#143]
Hi,
I'm sending super Fast request and your library is clearly the best. 
i'm Getting error : nimpy.OSError: Unexpected error encountered: Too many open files, nimpy.OSError: Unexpected error encountered: Cannot assign requested address

I know its about my server limit, but dont really know how to solve it.

**Comment by juancarlospaco** [comment]
Hi; You can try calling `close()` function after the requests.

**Comment by lululombard** [comment]
Hello, do you mean `close_client()`? If my request is like `faster_than_requests.get(url)`, where should-I call the `close()`? Thanks!

**Comment by juancarlospaco** [comment]
Then your version may be too old. :slightly_smiling_face:

**Comment by g1noox** [comment]
Updated to last version using : pip3 install faster_than_requests==21.03.03
Install dependency nim : apt-get install nim
New error : 
![image](https://user-images.githubusercontent.com/49704664/113719721-375a9c00-96ee-11eb-985d-56ea432c4937.png)
Here is /usr/local/lib/python3.8/dist-packages/faster_than_requests/

![image](https://user-images.githubusercontent.com/49704664/113719806-4c372f80-96ee-11eb-8f1b-147a304f568a.png)

**Comment by juancarlospaco** [comment]
Check that you have the latest version of PIP `21.0.1`, Python `3.9` and Nim `1.4.4`.

**Comment by g1noox** [comment]
![image](https://user-images.githubusercontent.com/49704664/113751103-d9d54800-970b-11eb-8da7-014b90740eb9.png)
All dependency and still one error

**Comment by juancarlospaco** [comment]
I think you need to reboot because is not finding stuff in `PATH`.
