### ISSUE TITLE
ImportError: faster_than_requests.so: undefined symbol: __builtin_saddll_overflow  (Update!)

### ISSUE THREAD

**Issue by FractalMatt** [juancarlospaco/faster-than-requests#144]
I added an update here, figured out how to fix it, which I suspect you'll never see given that issue is closed:
https://github.com/juancarlospaco/faster-than-requests/issues/142

Thanks juancarlospaco, appreciate your work!

**Comment by juancarlospaco** [comment]
Closed issues with new comments have the same notification as open issues in GitHub.
Issues without notifications are Locked issues, but those are read-only anyway.
:)

**Comment by juancarlospaco** [comment]
Thanks for your input, closing now I guess...  :slightly_smiling_face:
