### ISSUE TITLE
not running faster-than-requests on window 10 64bit

### ISSUE THREAD

**Issue by Yiming828** [juancarlospaco/faster-than-requests#147]
when I run the example py files, get error like this:
ImportError: DLL load failed: The specified module could not be found.
Please help.

**Comment by juancarlospaco** [comment]
[Install these DLL](https://nim-lang.org/download/dlls.zip) and reboot.

**Comment by Yiming828** [comment]
Please create youtube video that shows installation on windows and send me link. Thanks

**Comment by Yiming828** [comment]
File "C:\faster_than_requests-21.03.03_1\faster_than_requests\faster_than_requests\example.py", line 1, in <module>
    import faster_than_requests as requests
ImportError: DLL load failed while importing faster_than_requests: %1 is not a valid Win32 application.
