### ISSUE TITLE
Installation error (?)

### ISSUE THREAD

**Issue by realjami** [juancarlospaco/faster-than-requests#149]
Tried installing the library but it doesn't seem to work, I'm using 64 Bit

WARNING: Discarding https://files.pythonhosted.org/packages/fb/93/442a194afb29e5cdb45b06a97f4fcf474645f0106088715a3ec9767e04d6/faster_than_requests-21.03.01.zip#sha256=1ac5f174e542aa35146015f347f23e84b26f3021518bd9b06eb6e39a718897dd (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement faster-than-requests (from versions: 21.3.1, 21.3.2, 21.3.3)
ERROR: No matching distribution found for faster-than-requests

That's the error, no idea how to fix

**Comment by juancarlospaco** [comment]
PIP Bug, see if this works:

```
pip install faster-than-requests==21.3.3 --disable-pip-version-check --no-cache-dir --no-binary :all:
```

**Comment by realjami** [comment]
Tried py -m pip install faster-than-requests==21.3.3 --disable-pip-version-check --no-cache-dir --no-binary :all:
Using Python 3.9.5 (latest one)

Log:

C:\Users\Jami>py --version
Python 3.9.5

C:\Users\Jami>py -m pip install faster-than-requests==21.3.3 --disable-pip-version-check --no-cache-dir --no-binary :all:
Collecting faster-than-requests==21.3.3
  Downloading faster_than_requests-21.03.03.zip (4.9 MB)
     |████████████████████████████████| 4.9 MB 2.2 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Jami\AppData\Local\Programs\Python\Python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Jami\\AppData\\Local\\Temp\\pip-install-oas8fyuv\\faster-than-requests_0138e154175940bbab23bdd04891ea5a\\setup.py'"'"'; __file__='"'"'C:\\Users\\Jami\\AppData\\Local\\Temp\\pip-install-oas8fyuv\\faster-than-requests_0138e154175940bbab23bdd04891ea5a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Jami\AppData\Local\Temp\pip-pip-egg-info-d72ke4iw'
         cwd: C:\Users\Jami\AppData\Local\Temp\pip-install-oas8fyuv\faster-than-requests_0138e154175940bbab23bdd04891ea5a\
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: 'C:\Users\Jami\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Jami\\AppData\\Local\\Temp\\pip-wheel-vjxmryrd\\choosenim-install_8f08850a037f4f9c80e4248c0829096e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Jami\\AppData\\Local\\Temp\\pip-wheel-vjxmryrd\\choosenim-install_8f08850a037f4f9c80e4248c0829096e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Jami\AppData\Local\Temp\pip-wheel-qh_mt6rx'
           cwd: C:\Users\Jami\AppData\Local\Temp\pip-wheel-vjxmryrd\choosenim-install_8f08850a037f4f9c80e4248c0829096e\
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for choosenim-install
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "C:\Users\Jami\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "C:\Users\Jami\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Users\\Jami\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Jami\\AppData\\Local\\Temp\\tmp06ijmb86', '--quiet', 'choosenim_install']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Jami\AppData\Local\Temp\pip-install-oas8fyuv\faster-than-requests_0138e154175940bbab23bdd04891ea5a\setup.py", line 2, in <module>
        setuptools.setup(package_data = {"": ["*.nim", "*.nims", "*.cfg", "*.dll", "*.so", "*.h", "*.hpp"]})
      File "C:\Users\Jami\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "C:\Users\Jami\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\Users\Jami\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py", line 721, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:\Users\Jami\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "C:\Users\Jami\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "C:\Users\Jami\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 1063, in obtain
        return installer(requirement)
      File "C:\Users\Jami\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py", line 780, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "C:\Users\Jami\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['C:\\Users\\Jami\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Jami\\AppData\\Local\\Temp\\tmp06ijmb86', '--quiet', 'choosenim_install']' returned non-zero exit status 1.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f0/9b/f392487c0ddb086aad681a781fbb1da4fcd2761920d20cfae18ecb724e67/faster_than_requests-21.03.03.zip#sha256=3cc247556e10c64d8897933304670c873236026b4ef9f219215b124e990c2dac (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement faster-than-requests==21.3.3 (from versions: c66bdc9, d4d03a6, eb38cdb, 49d49f0, 272d664, 21.3.1, 21.3.2, 21.3.3, 57rc7862, 3572925)
ERROR: No matching distribution found for faster-than-requests==21.3.3

C:\Users\Jami>

**Comment by juancarlospaco** [comment]
>       error: invalid command 'bdist_wheel'
>       ----------------------------------------
>       ERROR: Failed building wheel for choosenim-install
>     ERROR: Failed to build one or more wheels

PIP Bug, PIP wants you to install/update `wheel` package first, then try again, 
sorry, my code do not need wheel, but PIP does.

**Comment by juancarlospaco** [comment]
Si sabes usar Git, clona el repo y compila manualmente, en readme hay un ejemplo, mas facil...

**Comment by realjami** [comment]
Ya lo logré instalar, necesitaba actualizar el `wheel`, pero me sale en mi IDE que no hay ningún module llamado `faster_than_requests`

**Comment by juancarlospaco** [comment]
> Ya lo logré instalar, necesitaba actualizar el `wheel`

Awesome!. :+1:
