### ISSUE TITLE
Error running py file

### ISSUE THREAD

**Issue by Yiming828** [juancarlospaco/faster-than-requests#158]
# Before you open a new bug

- 32 Bit is not supported.
- You must have 64 Bit Python 3.
- You must have 64 Bit GCC Compiler.
- You must have 64 Bit Operating System.
- Windows older than Windows 10 is not supported.
- ARM support is Experimental, you may need to compile manually.
- Mac OSX support is Experimental, you may need to compile manually.
- Alpine Linux support is Experimental, you may need to compile manually.
- Termux support is Experimental, you may need to compile manually.

**Comment by Yiming828** [comment]
File "C:\faster_than_requests-21.03.03_1\faster_than_requests\faster_than_requests\example.py", line 1, in
import faster_than_requests as requests
ImportError: DLL load failed while importing faster_than_requests: %1 is not a valid Win32 application.

**Comment by juancarlospaco** [comment]
Please provide full source code to reproduce the bug.
