### ISSUE TITLE
get is slowler than requests session object. get2str does not work, does not support header

### ISSUE THREAD

**Issue by Yiming828** [juancarlospaco/faster-than-requests#159]
# Before you open a new bug

- 32 Bit is not supported.
- You must have 64 Bit Python 3.
- You must have 64 Bit GCC Compiler.
- You must have 64 Bit Operating System.
- Windows older than Windows 10 is not supported.
- ARM support is Experimental, you may need to compile manually.
- Mac OSX support is Experimental, you may need to compile manually.
- Alpine Linux support is Experimental, you may need to compile manually.
- Termux support is Experimental, you may need to compile manually.

**Comment by juancarlospaco** [comment]
We dont accept this kind of bug reports, theres no useful information in the bug report whatsoever.
