### ISSUE TITLE
Unable to import in VS Code

### ISSUE THREAD

**Issue by happyshows** [juancarlospaco/faster-than-requests#16]
**Describe the bug**
Cannot import in VS Code jupyter mode. It just keep spinning.

**To Reproduce**
![image](https://user-images.githubusercontent.com/3208181/61760840-71f19900-ad92-11e9-82f8-0e943d1952f2.png)

**Expected behavior**
Execute in sub second

**Screenshots**
![image](https://user-images.githubusercontent.com/3208181/61760813-62725000-ad92-11e9-98c8-d88c7ffd98c9.png)

**Desktop (please complete the following information):**
Mojave 10.14.5

**Comment by juancarlospaco** [comment]
Report the Bug to VS Code, we cant fix VS Code, I dont do JavaScript and we dont have the resources to Fix VS Code, we cant Fix all Microsoft Bugs, sorry.
🤷‍♀️

**Comment by happyshows** [comment]
It doesn't work in terminal either, so it's problem with the lib not vs code or terminal I guess.

![image](https://user-images.githubusercontent.com/3208181/62413977-aa3b7780-b5db-11e9-9455-1c44de7084a0.png)

**Comment by juancarlospaco** [comment]
Download the source code from Git and Compile it. Use the Source...
:slightly_smiling_face:
