### ISSUE TITLE
status code?

### ISSUE THREAD

**Issue by wristbleed** [juancarlospaco/faster-than-requests#160]
im trying to get the status code of the site but it keeps saying this

AttributeError: 'list' object has no attribute 'status_code'

code 

` if r.status_code == 200:
        return True`

**Comment by juancarlospaco** [comment]
It returns a simple list type, you can `print(response)` and see it, 
it is ` [body, contentType, status_code, version, url, contentLength, headers] `
you can use `to_dict` to get Dict, you can use `to_json` to get a JSON.

**Comment by wristbleed** [comment]
alright thank you also i tried doing post on something and it kept saying 

TypeError: post() missing 1 required positional argument: body

Here my code

`def test():
 while True:
   member = open('members.txt')
   requests.post(f'https://discord.com/api/v8/guilds/$%7BguildID%7D/bans/$%7Bid%7D?', 
   http_headers=http_headers,threads=True)
   member.close`

Also i was wondering if it has proxy support if so how can i use it?

**Comment by juancarlospaco** [comment]
Add ` body = "" `

**Comment by wristbleed** [comment]
to where do i add that?

**Comment by juancarlospaco** [comment]
This is the full signature of post, there you can see the types and arguments:

```nim
post(
  url: string,
  body: string,
  user_agent: string,
  max_redirects: int,
  proxy_url: string,
  proxy_auth: string,
  timeout: int,
  http_headers = [("dnt", "1")],
)
```

**Comment by wristbleed** [comment]
I dont really get what u mean but maybe me sending u my code could help what im tryna say or makes it Easier for u to understand


`import discord
import json 
import random
import sys
from os import system
from itertools import cycle
import faster_than_requests as requests
from random import randint
import threading
from time import time, sleep


user_ids = []
proxies = []
rotating = cycle(proxies)


try:
    for line in open('Proxies.txt'):
        proxies.append(line.replace('\n', ''))
except:
    print(f"     \x1b[38;5;214m[\x1b[0m~\x1b[38;5;214m] \x1b[0mFailed To Load Proxies From Proxies.txt")


with open('Config.json') as f:
    config = json.load(f)

Token = config.get('Token')
Bot = config.get('Bot')


if Bot == True:
    http_headers = [("Authorization", f"Bot {Token}")]
else:
    http_headers = [("Authorization", f"{Token}")]

class Test:


    def Check(token, bot):
        if bot == True:
            http_headers = [("Authorization", f"Bot {token}")]
        else:
            http_headers = [("Authorization", f"{token}")]
            r=requests.get('https://discord.com/api/v8/users/@me', http_headers=http_headers)
        if   r.response.status == 200:
            return True
        else:
            return False


    def Ban(guild_id, member_id):
        try:
            r=requests.post(url=f"https://discord.com/api/v{randint(6,8)}/guilds/{guild_id}/bans/{member_id}", http_headers=http_headers, proxy_url={"http": 'http://' + next(rotating)}).result()
            if r.response.status == 200 or r.response.status == 201 or r.response.status == 204:
                print(f"     \x1b[38;5;214m[\x1b[0m~\x1b[38;5;214m] \x1b[0mSuccessfully Banned {member_id}")
            if r.response.status == 429:
                Thread(target=Test.Ban, args=(guild_id, member_id,)).start()
        except:
            pass


def aa():
    if Test.Check(Token, Bot):
        print(f"     \x1b[38;5;214m[\x1b[0m~\x1b[38;5;214m] \x1b[0mAuthenticated Token!")
        guild = input(f"     \x1b[38;5;214m[\x1b[0m~\x1b[38;5;214m] \x1b[0mGuild\x1b[38;5;214m: \x1b[0m")

        try:
            members = open('Scraped/members.txt').readlines()
            for member in members:
                member = member.replace("\n", "")
                user_ids.append(member)
        except:
            print(f"     \x1b[38;5;214m[\x1b[0m~\x1b[38;5;214m] \x1b[0mFailed To Load Scraped Data!")

        print(f"     \x1b[38;5;214m[\x1b[0m~\x1b[38;5;214m] \x1b[0mLoaded {len(user_ids)} Members!")
        sleep(2)
        Menu(guild)
    else:
        print(f"     \x1b[38;5;214m[\x1b[0m~\x1b[38;5;214m] \x1b[0mInvalid Token!")
        input()
        exit()

def Menu(guild):
	try:
	    clear()
	    print('''
     \x1b[0mBETA\x1b[0m
     \x1b[38;5;214m[\x1b[0m1\x1b[38;5;214m] \x1b[0mBan Users
     \x1b[38;5;214m[\x1b[0m2\x1b[38;5;214m] \x1b[0mKick Users
     \x1b[38;5;214m[\x1b[0m3\x1b[38;5;214m] \x1b[0mUnban Users
     \x1b[38;5;214m[\x1b[0m4\x1b[38;5;214m] \x1b[0mDelete Roles
     \x1b[38;5;214m[\x1b[0m5\x1b[38;5;214m] \x1b[0mDelete Channels
     \x1b[38;5;214m[\x1b[0m6\x1b[38;5;214m] \x1b[0mCreate Channels
     \x1b[38;5;214m[\x1b[0m7\x1b[38;5;214m] \x1b[0mCreate Roles
	    ''')
	    opt = input(f"     \x1b[38;5;214m[\x1b[0m~\x1b[38;5;214m] \x1b[0mOption\x1b[38;5;214m: \x1b[0m")
	    if opt == "1":
	        for i in range(len(user_ids)):
	            Thread(target=Test.Ban, args=(guild, user_ids[i],)).start()
	        sleep(2)
	        Menu(guild)
	    else:
	        Init()
	except:
		pass

if __name__ == "__main__":
    aa()`

Json FIle

`{
	"Token": "a',
	"Bot": true
}`

my imports 


import discord
import json 
import random
import sys
from os import system
from itertools import cycle
import faster_than_requests as requests
from random import randint
import threading
from time import time, sleep

**Comment by juancarlospaco** [comment]
Add ` body = "" ` to `post(  )` arguments.

**Comment by wristbleed** [comment]
Im really confused about what u mean by that if u mean like this 

`r=requests.post(body = "",f"https://discord.com/api/v{randint(6,8)}/guilds/{guild_id}/bans/{member_id}", http_headers=http_headers)` it gives me a 'SyntaxError: positional argument follows keyword argument'

**Comment by juancarlospaco** [comment]
`r = requests.post(url = f"https://discord.com/api/v{randint(6,8)}/guilds/{guild_id}/bans/{member_id}", body = "", http_headers=http_headers)`

Thats just how Python function arguments work. :shrug:

**Comment by wristbleed** [comment]
i was just confused about how u said it but thank u also can u give me an example of how to use proxies on faster than requests because on requests i use proxies={"http": 'http://' + next(rotating)}).result() and it works fine but if i use that on faster than requests it gives me some key errors

**Comment by juancarlospaco** [comment]
` proxy_url = "http://proxy.url.here:8080" `

**Comment by wristbleed** [comment]
Okay thank you sm if i have another question to ask ill let u know thanks for helping me :D

**Comment by wristbleed** [comment]
everything works except response it just keeps saying this

        if  r.response == 200:
            return True
        else:
            return False

AttributeError: 'list' object has no attribute 'response' i tried just printing the response it didnt work either

**Comment by juancarlospaco** [comment]
`r` is a list, theres no `r.response`, try `print( r[2] )`.

**Comment by wristbleed** [comment]
it works thank you, for status 429, 201, 429 do i just do r[29] [21] [49] or what

**Comment by juancarlospaco** [comment]
`r` is just a `list`, `r[2]` is just list indexing, item at index `2` of list `r`.
