### ISSUE TITLE
Premature termination

### ISSUE THREAD

**Issue by redrossa** [juancarlospaco/faster-than-requests#161]
It seems that when involving multithreading, faster-than-requests functions terminate early. I get the following message on the console: `Process finished with exit code -1073741819 (0xC0000005)` and the interpreter terminates before I see any result from the functions.

I get the same behavior with any of
```
get2str(urls, thread=True)
get2str(urls, thread=False)
scraper(urls, thread=True)
scraper(urls, thread=False)
```
even if I try make the threads myself and use the individual `get` function
```    
with concurrent.futures.ThreadPoolExecutor() as executor:
    yield from executor.map(lambda url: fast.get(url)[0], urls)
```
but not with just
```
get(url)
```

**Comment by juancarlospaco** [comment]
Can you post the whole code that reproduces the bug ?.

**Comment by redrossa** [comment]
![Screenshot 2021-05-28 161900](https://user-images.githubusercontent.com/43428886/120042861-7f9c8900-bfd0-11eb-8dea-8fc4b537ef56.png)

OS: 64-bit Windows 10

**Comment by juancarlospaco** [comment]
https://github.com/juancarlospaco/faster-than-requests/blob/master/examples/bug161.py

`threads = True` is not required anymore, can be omitted, all GET are always done in parallel.
