### ISSUE TITLE
how to set timeout time when requesting get and post request

### ISSUE THREAD

**Issue by abhi00031** [juancarlospaco/faster-than-requests#162]
how to set timeout time when requesting get and post request ?

**Comment by juancarlospaco** [comment]
` timeout = 1_000 ` in the arguments.

Millisecond precision so multiply by 1000.

**Comment by abhi00031** [comment]
I tried this but i am getting the  below response  from server 
 'status': '401 Unauthorized'.
When i don't put the timeout argument i am getting desired response from server

**Comment by juancarlospaco** [comment]
But it says you are not authorized.

Timeout is not related to auth whatsoever.

**Comment by juancarlospaco** [comment]
Maybe try debugging the HTTP operation itself using Postman or Insomnia ?.

**Comment by abhi00031** [comment]
ok Will try debugging

**Comment by abhi00031** [comment]
is the below line correct?
response=ftr.get2str(url,timeout=50000)

I noticed that when i use get() function i am getting response as unauthorized but when i use get2str() method i get the requested data.. why is it so ?
