### ISSUE TITLE
Just support python 3.6

### ISSUE THREAD

**Issue by reedniv** [juancarlospaco/faster-than-requests#165]
`WARNING: Discarding https://files.pythonhosted.org/packages/f0/9b/f392487c0ddb086aad681a781fbb1da4fcd2761920d20cfae18ecb724e67/faster_than_requests-21.03.03.zip#sha256=3cc247556e10c64d8897933304670c873236026b4ef9f219215b124e990c2dac (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement faster-than-requests (from versions: 21.3.3)`

**Comment by juancarlospaco** [comment]
That is not an error from our code, thats a PIP/Pypi error message, not my bug.

Git clone and compile if PIP keeps giving you errors.

**Comment by reedniv** [comment]
> Itu bukan kesalahan dari kode kami, itu pesan kesalahan PIP/Pypi, bukan bug saya.
> 
> Python 3.6 didukung dalam kode.
> 
> Git clone dan kompilasi jika PIP terus memberi Anda kesalahan.

I use python 3.8 ++ not python 3.6

**Comment by juancarlospaco** [comment]
Python 3.8 is supported in the code.
