### ISSUE TITLE
Win 10. Yet another install issue

### ISSUE THREAD

**Issue by vellrya** [juancarlospaco/faster-than-requests#169]
# Before you open a new bug

- 32 Bit is not supported.
- You must have 64 Bit Python 3.
- You must have 64 Bit GCC Compiler.
- You must have 64 Bit Operating System.
- Windows older than Windows 10 is not supported.
- ARM support is Experimental, you may need to compile manually.
- Mac OSX support is Experimental, you may need to compile manually.
- Alpine Linux support is Experimental, you may need to compile manually.
- Termux support is Experimental, you may need to compile manually.

Hello. Pip install failed, then I try to compile from source. Git, Nim and nimpy installed, rebooted, could you please look at this error?

-->  nim c -d:ssl -d:danger --app:lib --out:faster_than_requests.pyd faster_than_requests.nim
Hint: used config file 'C:\Users\Administrator\Downloads\nim-1.4.8_x64\nim-1.4.8\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\Administrator\Downloads\nim-1.4.8_x64\nim-1.4.8\config\config.nims' [Conf]
Hint: used config file 'C:\Users\Administrator\Downloads\faster-than-requests-master\faster-than-requests-master\faster_than_requests\faster_than_requests.nim.cfg' [Conf]
........................................................................
faster_than_requests.nim(3, 83) Error: cannot open file: std/tasks

Win 10 (x64, of course), python 3.9.5
Thank you)

**Comment by juancarlospaco** [comment]
Use Nim devel https://github.com/nim-lang/nightlies/releases

**Comment by vellrya** [comment]
Thank you, I am able to install library using nim devel.
Simple get and post works, but python crashes silently when I try threaded processing.

This sample for example: https://github.com/juancarlospaco/faster-than-requests/blob/master/examples/multitag_web_scraper.py

Could you please check?)
