### ISSUE TITLE
PIP Install Problem...

### ISSUE THREAD

**Issue by steeljardas** [juancarlospaco/faster-than-requests#170]
I have tried installing with Pip and it keeps giving me an error, I'm also not too sure how to install packages any other way..
Trying to install on Windows 10
Python version = 3.9

`C:\Users\Administrator>pip install faster-than-requests
Collecting faster-than-requests
  Using cached faster_than_requests-21.03.03.zip (4.9 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\administrator\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-install-9viyr7u5\\faster-than-requests_b36be11cfe8a439d84d49b75d7571c0b\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-install-9viyr7u5\\faster-than-requests_b36be11cfe8a439d84d49b75d7571c0b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Administrator\AppData\Local\Temp\2\pip-pip-egg-info-00dg0mig'
         cwd: C:\Users\Administrator\AppData\Local\Temp\2\pip-install-9viyr7u5\faster-than-requests_b36be11cfe8a439d84d49b75d7571c0b\
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\administrator\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-wheel-kqgg866n\\choosenim-install_3721c9862de94c139c18ba5a0ec1bc47\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-wheel-kqgg866n\\choosenim-install_3721c9862de94c139c18ba5a0ec1bc47\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Administrator\AppData\Local\Temp\2\pip-wheel-dhp7cj_j'
           cwd: C:\Users\Administrator\AppData\Local\Temp\2\pip-wheel-kqgg866n\choosenim-install_3721c9862de94c139c18ba5a0ec1bc47\
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for choosenim-install
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\tmp_cuayft_', '--quiet', 'choosenim_install']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Administrator\AppData\Local\Temp\2\pip-install-9viyr7u5\faster-than-requests_b36be11cfe8a439d84d49b75d7571c0b\setup.py", line 2, in <module>
        setuptools.setup(package_data = {"": ["*.nim", "*.nims", "*.cfg", "*.dll", "*.so", "*.h", "*.hpp"]})
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1076, in obtain
        return installer(requirement)
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['c:\\users\\administrator\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\tmp_cuayft_', '--quiet', 'choosenim_install']' returned non-zero exit status 1.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f0/9b/f392487c0ddb086aad681a781fbb1da4fcd2761920d20cfae18ecb724e67/faster_than_requests-21.03.03.zip#sha256=3cc247556e10c64d8897933304670c873236026b4ef9f219215b124e990c2dac (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement faster-than-requests (from versions: 21.3.3)
ERROR: No matching distribution found for faster-than-requests`

**Comment by george-studenko** [comment]
Wanted to give it a go but I cannot install it either, I get a similar error

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for choosenim-install
    ERROR: Failed to build one or more wheels

**Comment by Parvat-R** [comment]
Facing the same problem
 - Windows 10 32bit
 - Python 3.9.6
---
# On using **`pip install faster_than_requests `**
```
ERROR: Command errored out with exit status 1:
     command: 'e:\python3.9.6\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\new\\AppData\\Local\\Temp\\pip-install-eahufnd_\\faster-than-requests_0e1d5722dd2848328157f684bb560659\\setup.py'"'"'; __file__='"'"'C:\\Users\\new\\AppData\\Local\\Temp\\pip-install-eahufnd_\\faster-than-requests_0e1d5722dd2848328157f684bb560659\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\new\AppData\Local\Temp\pip-pip-egg-info-ka78vpvi'
         cwd: C:\Users\new\AppData\Local\Temp\pip-install-eahufnd_\faster-than-requests_0e1d5722dd2848328157f684bb560659\
    Complete output (77 lines):
      ERROR: Command errored out with exit status 1:
       command: 'e:\python3.9.6\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\new\\AppData\\Local\\Temp\\pip-wheel-tgoueq90\\choosenim-install_9640d8a92f9344308227bd05a79538b9\\setup.py'"'"'; __file__='"'"'C:\\Users\\new\\AppData\\Local\\Temp\\pip-wheel-tgoueq90\\choosenim-install_9640d8a92f9344308227bd05a79538b9\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\new\AppData\Local\Temp\pip-wheel-6go0qa36'
           cwd: C:\Users\new\AppData\Local\Temp\pip-wheel-tgoueq90\choosenim-install_9640d8a92f9344308227bd05a79538b9\
      Complete output (40 lines):
      running bdist_wheel
      running build
      installing to build\bdist.win32\wheel
      running install
      running install_egg_info
      running egg_info
      writing choosenim_install.egg-info\PKG-INFO
      writing dependency_links to choosenim_install.egg-info\dependency_links.txt
      deleting choosenim_install.egg-info\requires.txt
      writing top-level names to choosenim_install.egg-info\top_level.txt
      writing manifest file 'choosenim_install.egg-info\SOURCES.txt'
      reading manifest file 'choosenim_install.egg-info\SOURCES.txt'
      writing manifest file 'choosenim_install.egg-info\SOURCES.txt'
      Copying choosenim_install.egg-info to build\bdist.win32\wheel\.\choosenim_install-0.5.5-py3.9.egg-info
      running install_scripts
      This version of C:\Users\new\AppData\Local\Temp\pip-wheel-tgoueq90\choosenim-install_9640d8a92f9344308227bd05a79538b9\choosenim.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
      This version of C:\Users\new\AppData\Local\Temp\pip-wheel-tgoueq90\choosenim-install_9640d8a92f9344308227bd05a79538b9\choosenim.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
      C:\Users\new\AppData\Local\Temp\pip-wheel-tgoueq90\choosenim-install_9640d8a92f9344308227bd05a79538b9\setup.py:107: UserWarning: Failed to run C:\Users\new\AppData\Local\Temp\pip-wheel-tgoueq90\choosenim-install_9640d8a92f9344308227bd05a79538b9\choosenim.exe --yes --verbose --noColor --firstInstall stable
        warnings.warn("Failed to run " + choosenim_cmd)
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Users\new\AppData\Local\Temp\pip-wheel-tgoueq90\choosenim-install_9640d8a92f9344308227bd05a79538b9\setup.py", line 210, in <module>
          setuptools.setup(
        File "e:\python3.9.6\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "e:\python3.9.6\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "e:\python3.9.6\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "e:\python3.9.6\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\new\AppData\Roaming\Python\Python39\site-packages\wheel\bdist_wheel.py", line 326, in run
line 785, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "e:\python3.9.6\lib\site-packages\pkg_resources\__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "e:\python3.9.6\lib\site-packages\pkg_resources\__init__.py", line 1051, in best_match
        return self.obtain(req, installer)      File "e:\python3.9.6\lib\site-packages\pkg_resources\__init__.py", line 1063, in obtain
        return installer(requirement)
      File "e:\python3.9.6\lib\site-packages\setuptools\dist.py", line 844, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "e:\python3.9.6\lib\site-packages\setuptools\installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['e:\\python3.9.6\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\new\\AppData\\Local\\Temp\\tmpv9b180dd', '--quiet', 'choosenim_install']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I don't understand if there is problem from _my side_, or the _packaging_ or my _os_??

**Comment by muxueqz** [comment]
@steeljardas @george-studenko @Parvat-R 
I got the same problem, and i used it to fix:
```bash
pip install wheel
```

**Comment by tensX** [comment]
Download the latest Windows version of choosenim from the [releases](https://github.com/dom96/choosenim/releases) page (the .zip file).

Extract the zip archive and run the runme.bat script. Follow any on screen prompts and enjoy your new Nim and choosenim installation.
