### ISSUE TITLE
Failed importing library

### ISSUE THREAD

**Issue by vargaspazdaniel** [juancarlospaco/faster-than-requests#171]
Hello,

After install + compile the library in Linux Mint x64 bits, when I try to import faster_than_requests, I'm getting the following error:
`FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-c0c82cb9e8ed> in <module>
      1 # sudo apt install nim
      2 # pip install faster_than_requests
----> 3 import faster_than_requests as requests

~/anaconda3/lib/python3.8/site-packages/faster_than_requests/__init__.py in <module>
      5 import nimporter
      6 
----> 7 from . faster_than_requests import *

~/anaconda3/lib/python3.8/importlib/_bootstrap.py in _find_and_load(name, import_)

~/anaconda3/lib/python3.8/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

~/anaconda3/lib/python3.8/importlib/_bootstrap.py in _find_spec(name, path, target)

~/anaconda3/lib/python3.8/site-packages/nimporter.py in find_spec(cls, fullname, path, target)
   1148     @classmethod
   1149     def find_spec(cls, fullname, path=None, target=None):
-> 1150         return Nimporter.import_nim_code(fullname, path, library=False)
   1151 
   1152 

~/anaconda3/lib/python3.8/site-packages/nimporter.py in import_nim_code(cls, fullname, path, library)
    826 
    827             if cls.should_compile(module_path):
--> 828                 NimCompiler.compile_nim_code(
    829                     module_path.parent if library else module_path,
    830                     build_artifact,

~/anaconda3/lib/python3.8/site-packages/nimporter.py in compile_nim_code(cls, module_path, build_artifact, library)
    586                 raise NimInvokeException(tmp_cwd, nim_args, errors, output)
    587             else:
--> 588                 raise NimCompileException(errors[0])
    589 
    590         for warn in warnings: print(warn)

~/anaconda3/lib/python3.8/site-packages/nimporter.py in __init__(self, msg)
     54             message = error_msg + '\n'
     55 
---> 56             with open(nim_module, 'r') as mod:
     57                 line = 0
     58                 for each_line in mod:

FileNotFoundError: [Errno 2] No such file or directory: 'faster_than_requests.nim.cfg'`

**Comment by juancarlospaco** [comment]
Anaconda is not supported, only the official Python implementation is supported.

**Comment by vargaspazdaniel** [comment]
Okay, thank you.
