### ISSUE TITLE
faster benchmarkes 3x slower than pycurl

### ISSUE THREAD

**Issue by p-i-** [juancarlospaco/faster-than-requests#172]
Sorry to be the bringer of sad tidings.
But this is important information, that would have saved me 3 days.

With faster:
```
0.8790318965911865
2.0442020893096924
3.06596302986145
1.0118408203125
0.9790389537811279
0.7987222671508789
0.7720210552215576
0.882786750793457
0.7800428867340088
0.7802371978759766
```

Now with pycurl:
```
0.8444831371307373
0.20353293418884277
0.3020648956298828
0.3071250915527344
0.20524311065673828
0.20215511322021484
0.20119595527648926
0.2034451961517334
0.20181608200073242
0.20012187957763672
```

FTR code:
```
import faster_than_requests as faster
faster.init_client()
for i in range(10):
    t0 = time()
    h = faster.get(f'https://some_url/{i}')
    print(time()-t0)
```

PyCurl code:
```
c = pycurl.Curl()
for i in range(10):
    c.setopt(c.URL, f'{url}/{1512-i}')
    buffer = BytesIO()
    c.setopt(c.WRITEDATA, buffer)
    c.perform()
    body = buffer.getvalue().decode('iso-8859-1')
    # print('BODY:', body)
c.close()
```

Now pycurl is reusing the session.
The initial fetch is roughly equivalent:
```
0.8790318965911865  # FTR
0.8444831371307373  # pycurl
```

So if there's a way to do this with FTR, I expect they will be roughly equivalent.

**Comment by juancarlospaco** [comment]
Use `get2str()`.

To do this kind of measure the script should be the only thing running on the PC.

A rewrite is coming relatively soon.

If you want to use curl, feel free to use it. 

Curl may not be for everybody, same as this may not be for you :)

**Comment by juancarlospaco** [comment]
That is not the best approach for max performance btw, you should for loop from the Nim side.

By calling Python side stuff "in between" you slow down to Python average speeds.

Doing as much as possible from the typed compiled side is better than the interpreted duck-typing side.

Here you have a tool that allows you to go fast as C, safe as Rust, easy as Python,
[you have Python syntax that you can just import](https://github.com/Yardanico/nimpylib#usage).

Ideally you have your function `doStuff(["http://foo.com", "http://bar.com"]) -> str`,
`doStuff` is a Nim function, you call `doStuff()` from the Python side.

Similar as when you write a module using Rust, is just that the syntax is not ugly as Rusts.
:)

**Comment by p-i-** [comment]
Issues I see:
1. Build system -- FTR requires a lot of fiddling on different OS, which is a barrier to adoption. An automated test-suite that tests on macOS, linux and Windows would show bugs before they get reported on issues-tracker.
2. Threading -- attempts to multithread FTR fail on my macOS setup.
3. Reuse of 'session' to avoid re-execution of SSL handshake stuff. Notice the first cURL request takes 4x longer than subsequent ones. The same is probably possible with FTR.
4. Async lib -- if you could build FTR async, by async-bridging between nim and Python, FTR would be the only fast HTTP client. Async is the way forwards with this kind of stuff, and there's currently no performant solution. It's deep technical work tho'. If you DO look at it, please consider Trio rather than asyncio. It's taking over due to simply being so much better/cleaner. They have a great gitter channel.

`pycurl` is a headache. And requires digging into GET and POST internals. I needed a fair bit of help from the #curl channel on IRC Libera. So yes, if you can provide an easy-to-use fast HTTP lib that's also easy-to-install and withing 10% of cURL, it will gain a lot of traction.

**Comment by juancarlospaco** [comment]
Ok, Pull Requests welcomed.
