### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'faster_than_requests.nim.cfg'

### ISSUE THREAD

**Issue by A91K3C1l** [juancarlospaco/faster-than-requests#174]
hello everyone I want to ask why I got an error like this
 >>> import faster_than_requests Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/faster_than_requests/__init__.py", line 7, in <module> from . faster_than_requests import * File "<frozen importlib._bootstrap>", line 991, in _find_and_load File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 914, in _find_spec File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/nimporter.py", line 1150, in find_spec return Nimporter.import_nim_code(fullname, path, library=False) File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/nimporter.py", line 828, in import_nim_code NimCompiler.compile_nim_code( File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/nimporter.py", line 588, in compile_nim_code raise NimCompileException(errors[0]) File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/nimporter.py", line 56, in __init__ with open(nim_module, 'r') as mod: FileNotFoundError: [Errno 2] No such file or directory: 'faster_than_requests.nim.cfg'

 I installed via zip file and I have also installed nimpy info:aarch64 android 6.0 thank you

**Comment by juancarlospaco** [comment]
Android is not supported by the ZIP, you have to Git clone and compile manually, sorry.
