### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by A91K3C1l** [juancarlospaco/faster-than-requests#175]
please help to install in termux I've tried all the ways and asked in the group to no avail I want to ask for help how to install in termux aarch64 android 6.0 I've installed nympy

**Comment by juancarlospaco** [comment]
```
nim c -d:ssl -d:danger --app:lib --out:/full/path/to/faster_than_requests.so /full/path/to/faster_than_requests.nim
```

Must replace `/full/path/to/faster_than_requests.so` to the actual real full path that `faster_than_requests.so` should be written to.

Must replace `/full/path/to/faster_than_requests.nim` to the actual real full path of `faster_than_requests.nim`.

This project is pending for a big rewrite, for several reasons, 
including performance and better code overall, sorry.

Ive been working on https://github.com/juancarlospaco/cpython#documentation

**Comment by A91K3C1l** [comment]
I don't understand how to do it because I've only just learned 1 nim I need an easy to understand install tutorial thank you for answering my question

**Comment by juancarlospaco** [comment]
I dont know how to make it more simpler, explicit nor easy, is just 1 command that you have to run to compile.

Maybe learn more nim and come back later with more experience...
