### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by iCheppy** [juancarlospaco/faster-than-requests#176]
I am getting a bad exit code after several requests are made. The first few requests work fine, but then it breaks.
`Process finished with exit code -1073741819 (0xC0000005)` (access violation error)

```python
requests2.init_client()

for url in url_bank:
    requests2.get(url)
```

**Comment by juancarlospaco** [comment]
You need to `close_client`, but in the future `init_client` nor `close_client` will not be needed, because of this kind of problems.
