### ISSUE TITLE
Windows Installation Error

### ISSUE THREAD

**Issue by klc573** [juancarlospaco/faster-than-requests#18]
Tried installing with PIP and got an error. So tried to manually run install.py and got the following:

![image](https://user-images.githubusercontent.com/54154671/63122816-9d246e00-bf75-11e9-9892-19b2da6994cd.png)

I am running Python 3.7 on Windows.

In other answers you say compile the source code. What is the best way to do that to get it working?

**Comment by klc573** [comment]
with --verbose turned on

![image](https://user-images.githubusercontent.com/54154671/63142853-928bc800-bfb9-11e9-8279-86ec86b78ccd.png)

**Comment by juancarlospaco** [comment]
Download the source code from Git and Compile it. Use the Source...
:slightly_smiling_face:

**Comment by klc573** [comment]
Could you provide some more detailed instructions on how to do that?

Do you mean the .nim file in the source folder? What is the easiest way to compile it?

**Comment by juancarlospaco** [comment]
![win-compile](https://user-images.githubusercontent.com/1189414/63147831-b8bf6100-bfd5-11e9-9e6e-91d61040f139.png "Git Clone and Compile on Windows 10 with only Git and Nim installed, just 2 commands!")
:slightly_smiling_face: :+1:

**Comment by klc573** [comment]
Thanks - once I have the compiled *dll and *nim files what do I do next to build the python module?

Or are you just using the *dll directly in python by loading it with ctypes? What's the best way?

**Comment by juancarlospaco** [comment]
If it compiles, you wont need `*.nim` files anymore, nor Nim, nor Git.

It is a vanilla native Python module, should be possible to import it directly.

Where they go I dunno, depends on your venv/environment/etc.
Install other native python module from pypi and see where it puts the files on your system (?).
:slightly_smiling_face:

**Comment by klc573** [comment]
Thanks. I was able to successfully run it.

For anyone else installing on windows:

Like Juan Carlo posted - you need to install the latest version of NIM and add it to the path. Then execute the following in a cmd window from the faster-than-requests-master\src folder:

nimble install nimpy
nim c --hint[Processing]:off --app:lib --out:faster_than_requests.dll faster_than_requests.nim

That will generate a DLL file. Move the DLL file to the DLLs folder in your python installation. You will need to change the ending from .dll to .pyd. Then you will be able to load the faster_than_requests module in python.

import faster_than_requests as requests
print(requests.gets("http://httpbin.org/get"))

**Comment by juancarlospaco** [comment]
`--hint[Processing]:off` is just to make compiler a little bit silent so it fits on the screenshot. :stuck_out_tongue_closed_eyes: 

You can replace `.dll` by `.pyd` on the compile command itself.

Adding `-d:release` can be recommendable too.
:slightly_smiling_face:
