### ISSUE TITLE
ModuleNotFoundError: No module named 'faster_than_requests.faster_than_requests'

### ISSUE THREAD

**Issue by flooowd** [juancarlospaco/faster-than-requests#180]
I have compiled my program to .exe and now its returning this error ModuleNotFoundError: No module named 'faster_than_requests.faster_than_requests', if i run without compile it works normally, any idea what it might be?

**Comment by juancarlospaco** [comment]
It depends how are you compiling to EXE, that is not a functionality of the code in this repo...

**Comment by flooowd** [comment]
Im using pyinstaller 4.7 to compile it

using this command
`
pyinstaller --noconfirm --onedir --console  "C:/path/archive.py"
`

**Comment by juancarlospaco** [comment]
Then that is a Bug or Feature for Pyinstaller project, and should be reported there.

We can not fix bugs in Pyinstaller. The code in the repo does not makes EXEs.

**Comment by juancarlospaco** [comment]
Good luck with that!, I never been able to make EXE with Pyinstaller in a stable way, but was years ago.
