### ISSUE TITLE
Use the same connection

### ISSUE THREAD

**Issue by 161134050** [juancarlospaco/faster-than-requests#19]
So in requests library you can have `reqSession = requests.Session()`, and it will set up a connection that can be re-used, which improves performance a lot if you are sending requests over the same connection.

Is there a similar option in faster-than-requests?

Because right now, faster-than-requests is slower-than-requests, when compared to requests with a Session :(

**Comment by juancarlospaco** [comment]
It is not designed as a drop-in replacement of any pre-existing library.
The API is different also because it does more different things.
It does reuse internally what it needs, without needing the user to do anything extra.
