### ISSUE TITLE
python: can't open file '/home/runner/work/Experimentation/Experimentation/request-alternatives.py': [Errno 2] No such file or directory Error: Process completed with exit code 2.

### ISSUE THREAD

**Issue by ShodhArthavruksha** [juancarlospaco/faster-than-requests#199]
### Architecture

x86_64 (Default)

### Operating System

Linux

### Disk

Others (USB)

### Memory

8 Gigabytes

### CPU Cores

1 CPU Cores

### Internet Connection

Wifi (WLAN, Wireless)

### What is your web browser?

Chrome/Chromium

### Device

Desktop PC

### Where are you from?

India

### What happened?

`python: can't open file '/home/runner/work/Experimentation/Experimentation/request-alternatives.py': [Errno 2] No such file or directory
Error: Process completed with exit code 2.`

### Standard Output Logs

```shell
python: can't open file '/home/runner/work/Experimentation/Experimentation/request-alternatives.py': [Errno 2] No such file or directory
Error: Process completed with exit code 2.
```

**Comment by themysticsavages** [comment]
This is a very vague question
