### ISSUE TITLE
How do you actually install this?

### ISSUE THREAD

**Issue by Trahax** [juancarlospaco/faster-than-requests#2]
The download is a DLL and you can't import that to python. The docker script I have no idea how i'm supposed to retrieve the files on it

**Comment by juancarlospaco** [comment]
The download is a DLL and you can import that to python.
The Dockerfile is like a recipe, it will retrieve the files for you.
Also you can Git clone the repo and compile it yourself for any OS.

Its WIP, the idea is when ready for Prod upload it to PyPI, Pull Requests welcome tho.
:slightly_smiling_face:

**Comment by juancarlospaco** [comment]
```
pip install faster_than_requests
```
🐍🤪
