### ISSUE TITLE
this project is totally broken.  A shame as I wanted to use it.  [bug] 

### ISSUE THREAD

**Issue by HeeebsInc** [juancarlospaco/faster-than-requests#201]
### Architecture

x86_64 (Default)

### Operating System

Linux

### Disk

SSD (Solid)

### Memory

64 Gigabytes

### CPU Cores

16 CPU Cores

### Internet Connection

Optical Fiber (very fast)

### What is your web browser?

Chrome/Chromium

### Device

Desktop PC

### Where are you from?

United States

### What happened?

Nim is breaking the pip install.  Tried everything you mention in the Github issues.   I don't think I have been able to find one user that has successfully downloaded and used it aside from the contributors.  In the issues, all that I see it "a stale close" or you guys asking for contributions.  Please advise as the benchmarks you display are really exciting

### Standard Output Logs

```shell
nimporter.NimCompileException: faster_than_requests.nim.cfg(20, 3) Error: invalid command line option: '--exceptions'


faster_than_requests==21.3.3

Ubuntu=20.04
python = 3.9
```

**Comment by dev-mani** [comment]
I would agree with @HeeebsInc since faster_than_requests came up few months back, i tried to use it and putted too much effort but i was not able to even run it till this day. Please remove this from PyPI and github as well

**Comment by Omar-TI** [comment]
### **solved guys
you need to use python 3.8
this is my output
py -3.8 -m pip install faster-than-requests**
Collecting faster-than-requests
  Using cached https://files.pythonhosted.org/packages/f0/9b/f392487c0ddb086aad681a781fbb1da4fcd2761920d20cfae18ecb724e67/faster_than_requests-21.03.03.zip
Collecting nimporter (from faster-than-requests)
  Downloading https://files.pythonhosted.org/packages/96/3c/ded65fcf69a8a487be84f96ab3072bfd4133ec40617ab60421f87c9684f5/nimporter-1.1.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: nimporter
  Building wheel for nimporter (PEP 517) ... done
  Created wheel for nimporter: filename=nimporter-1.1.0-cp38-none-any.whl size=24144 sha256=2e5beadf4d9233d1032786bb6e820123e4bff4bae6dc2e087648b1a404e16587
  Stored in directory: C:\Users\kamel\AppData\Local\pip\Cache\wheels\0b\27\f1\ae2dddddf2b8afa7efefb45d58caa4c5067cf75b39f1265f55
Successfully built nimporter
Installing collected packages: nimporter, faster-than-requests
  Running setup.py install for faster-than-requests ... done
Successfully installed faster-than-requests-21.3.3 nimporter-1.1.0
Worked

**Comment by itschasa** [comment]
@dev-mani did you find a solution to your problem? i have the same issue
