### ISSUE TITLE
how to use in python after git & compile?

### ISSUE THREAD

**Issue by danosagi** [juancarlospaco/faster-than-requests#21]
Sorry for asking a basic question like this.   I tried both pip install & git clone and install, but both methods show errors.   I read your FAQ and wanted to go with the Git clone & compile way and "use source code".  I completed both commands and having both `faster_than_requests.dll` & `faster_than_requests.nim` in the src folder.  But I guess I'm too new to know how to use the source code in python after this.  

I tried google to search like how to use in python after compile but still can't find help on how to do it afterwards.  Many thanks if you can help on this!

**Comment by danosagi** [comment]
Thanks a lot for the help.  It works now!

I'm into a speed issue now.  I test run comparing requests.get ().content and faster_than_requests.get2str () using %%timeit on the same website "https://finance.yahoo.com/quote/MSFT/key-statistics?p=MSFT".

requests.get ().content run time:
526 ms ± 131 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

faster_than_requests.get2str () run time:
694 ms ± 143 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

I tested it a few more time and found their running time are mostly similar.  According to your introduction it shall run a lot faster than requests.  Is that anything that I did wrong to make it slower?  Or is there certain restriction on requesting faster, maybe like only for json file such such?

**Comment by juancarlospaco** [comment]
I dont know, without the code theres no way to know, I dont know whats `%%timeit`,
but proper test should be made on the Terminal of the operating system.

It is optimized for HTTP JSON APIs.

**Comment by danosagi** [comment]
%%timeit is the code to test-run 7 times and getting average time of such code.  More intuitively using time.time() my code would be:

'import time'
'import requests'
'import faster_than_requests as reqs'

'time1 = time.time()'
'a = requests.get("https://finance.yahoo.com/quote/MSFT/key-statistics?p=MSFT").content'
'print (f'requests runtime = {time.time()-time1}')'

'time2 = time.time()'
'b = reqs.get2str("https://finance.yahoo.com/quote/MSFT/key-statistics?p=MSFT")'
'print (f'faster_than_requests runtime = {time.time()-time2}')'

and output is:
'''requests runtime = 0.46082472801208496
faster_than_requests runtime = 0.6559121608734131'''

I'm using 64bit.  It might be running less efficiently under https non-APIs sites?

**Comment by danosagi** [comment]
%%timeit is the code to test-run 7 times and getting average time of such code. More intuitively using time.time() my code would be:

```
import time
import requests
import faster_than_requests as reqs

time1 = time.time()
a = requests.get("https://finance.yahoo.com/quote/MSFT/key-statistics?p=MSFT").content
print (f'requests runtime = {time.time()-time1}')

time2 = time.time()
b = reqs.get2str("https://finance.yahoo.com/quote/MSFT/key-statistics?p=MSFT")
print (f'faster_than_requests runtime = {time.time()-time2}')
```

and output is:
```
requests runtime = 0.46082472801208496
faster_than_requests runtime = 0.6559121608734131
```

I'm using 64bit. It might be running less efficiently under https non-APIs sites?

**Comment by juancarlospaco** [comment]
```python
import time
import requests
import faster_than_requests as reqs

time1 = time.time()
for i in range(9):
  requests.get("https://httpbin.org/get").content
print(f'Requests = {time.time() - time1}')

time2 = time.time()
for i in range(9):
  reqs.get2str("https://httpbin.org/get")
print(f'Faster_than_requests = {time.time() - time2}')
```

```console
$ python3 example2.py
Requests = 7.90063419342041
Faster_than_requests = 2.0017221927642822
```

🤷‍♀️

- If its a Windows PC, can be the builtin AntiVirus, if you dont have AntiVirus can be a Virus :grey_question: 
- is it Python `3.7.4` :grey_question: 
- Other stuff running on the PC, missing Updates :grey_question: 
- That URL acting funky :grey_question:

**Comment by juancarlospaco** [comment]
- `git pull origin master` and Recompile and try again :grey_question: 

It works on my machine *(classic)* :slightly_smiling_face:

**Comment by danosagi** [comment]
When I used the site (https://httpbin.org/get) you tested it shows the similar result which is 4 times faster than requests.  
However when I used other regular sites (like yahoo finance) it becomes slightly slower.Guess it's limitation on different sites.  Thanks very much for all the help tho!
