### ISSUE TITLE
FAQ: How is faster-than-requests faster than requests?

### ISSUE THREAD

**Issue by rooom13** [juancarlospaco/faster-than-requests#211]
A question that would be nice to have in the FAQ section in the readme

Why is faster-than-requests faster than requests? How is this achieved?
The answer of this question can help users taking the decision whether to use it or not

**Comment by juancarlospaco** [comment]
It is a compiled statically typed native binary module,
similar to when Rust is used to make Python modules, 
but using Nim lang, that is mentioned in the readme.
