### ISSUE TITLE
[bug] Cannot find reference 'put' in __init__.py

### ISSUE THREAD

**Issue by LazzaAU** [juancarlospaco/faster-than-requests#212]
### Architecture

ARM_64 (64Bit)

### Operating System

Linux

### Disk

SSD (Solid)

### Memory

1 Gigabytes

### CPU Cores

1 CPU Cores

### Internet Connection

Wifi (WLAN, Wireless)

### What is your web browser?

Chrome/Chromium

### Device

Desktop PC

### Where are you from?

Australia

### What happened?

i'm using Pycharm community edition. 

- I installed faster-than-requests through pycharm into my venv. 
-  Pycharm told me all was successfully installed
- i imported ``import faster_than_requests as requests``` into my module
- I wrote my code
 ```new_url = f"{url}users/{local_id}.json?auth={firebase_token}"
        responce = requests.patch(url=new_url, json=json_data)
```
- Pycharm constantly tells me "Cannot find reference 'put' in __init__.py", same for patch, post, get etc

I'm on python 3.10

**Comment by juancarlospaco** [comment]
The code autocomplete bugs of Pycharm IDE should be reported to JetBrains,
we can not fix Pycharm because we do not have the money nor resources that JetBrains has, sorry.

**Comment by LazzaAU** [comment]
Wouldn't of thought it's a pycharm issue. But ok

**Comment by juancarlospaco** [comment]
How can I change the behaviour of Pycharm ?,
I think that is not my bug whatsoever... 🤷
