### ISSUE TITLE
its broken bruh

### ISSUE THREAD

**Issue by FargeGoty** [juancarlospaco/faster-than-requests#214]
### Architecture

x86_64 (Default)

### Operating System

Windows

### Disk

SSD (Solid)

### Memory

16 Gigabytes

### CPU Cores

4 CPU Cores

### Internet Connection

Wifi (WLAN, Wireless)

### What is your web browser?

Chrome/Chromium

### Device

Desktop PC

### Where are you from?

Russia

### What happened?

It doesn't downloading even with manually from github

**Comment by Random-Code-Guy** [comment]
> ### Architecture
> x86_64 (Default)
> 
> ### Operating System
> Windows
> 
> ### Disk
> SSD (Solid)
> 
> ### Memory
> 16 Gigabytes
> 
> ### CPU Cores
> 4 CPU Cores
> 
> ### Internet Connection
> Wifi (WLAN, Wireless)
> 
> ### What is your web browser?
> Chrome/Chromium
> 
> ### Device
> Desktop PC
> 
> ### Where are you from?
> Russia
> 
> ### What happened?
> It doesn't downloading even with manually from github
> 
> ### Standard Output Logs
> _No response_

can you post your code on github and provide a link to it i have been using this librery for about 6 months now with no issues at all
