### ISSUE TITLE
Is it possible to use a proxy with download ?

### ISSUE THREAD

**Issue by Random-Code-Guy** [juancarlospaco/faster-than-requests#215]
Hi i have been using this with no issues and its been working perfect how ever i now need to use a http proxy when download files using this libery 

i see a proxy is supported with the standard get but can it also be used with the download function as i dont see it in the documents ?

**Comment by juancarlospaco** [comment]
Proxy does not work with the download function, 
it can work with the fetch function directly.

**Comment by Random-Code-Guy** [comment]
> Proxy does not work with the download function, it can work with the fetch function directly.

Do you have any examples of this ? 

also would you consider adding a proxy to the download function this would allow tho's that need to download files from say a work network only to be able todo so using a proxy from a remote location

**Comment by juancarlospaco** [comment]
You have to read about how HTTP works, 
because you have to make the request to the proxy address instead of the web server of the web page, 
then on the proxy header you put the address of the web server of the page, 
so proxy fetch it for you and serve it and cache it, 
it works basically but you have to know HTTP, 
I do not have time to make examples sadly.

**Comment by Random-Code-Guy** [comment]
> You have to read about how HTTP works, because you have to make the request to the proxy address instead of the web server of the web page, then on the proxy header you put the address of the web server of the page, so proxy fetch it for you and serve it and cache it, it works basically but you have to know HTTP, I do not have time to make examples sadly.

i managed todo it just using

requests.get(url, proxyurl=proxy)[0]

works ok so far and allows me to use the same code for downloads as well as normal requests simply by sending an useproxy bool option
