### ISSUE TITLE
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

### ISSUE THREAD

**Issue by saiv94** [juancarlospaco/faster-than-requests#25]
Faster_than_requests is good for small runs.
But when integrated with python flask, it doesn't work properly.
it shows the error as :+1: 
"SIGSEGV: Illegal storage access. (Attempt to read from nil?)"

issue place:
for i in links:
    #page_source_string = faster_than_requests.gets(i)
    (or)
   #page_source_string = faster_than_requests.get2str(i)
#page_source_string = faster_than_requests.get2str_list(links)

I tried all above, but same error!
I use:
ubuntu:18.04
python 3.6.8

Any idea on this? How to fix this error? or any better library?

**Comment by juancarlospaco** [comment]
Without the full source code of a working example of the bug is impossible to reproduce.

Try compiling it as is shown in the readme documentation maybe.

**Comment by saiv94** [comment]
my code:
################################################
from flask import Flask, request, render_template, Response
import faster_than_requests as req
application = Flask(__name__)

@application.route('/test', methods=['POST'])
def test():
    list_of_links = request.form['links']
    links_pagesources = []
    for i in list_of_links:
        try:
            each_pagesource = req.gets(i)
            links_pagesources.append(each_pagesource)
        except Exception as e:
            print(e)
    return links_pagesources

if __name__ == '__main__':
    try:
        application.run(host = '127.0.0.1, port=80, debug=True)
    except Exception as e:
        print(e)
##############################################################

but when I run this code on valid sample links through flask, it shows stops saying this.
**SIGSEGV: Illegal storage access. (Attempt to read from nil?)**

I observed that it doesn't even go to exception, but just stops. And everytime time stopped at line 
**each_pagesource = req.gets(i)**

Let me know if you get the issue! How to fix it?

**Comment by juancarlospaco** [comment]
is the URL an API?, thats optimized for API JSON REST.

You can try using `get2str()`.
