### ISSUE TITLE
Compilation Errors On Windows 64 With Anaconda

### ISSUE THREAD

**Issue by FrankDMartinez** [juancarlospaco/faster-than-requests#26]
**Describe the bug**
I am attempting to install the library via `pip` from `Anaconda`, version 4.7.12. When I do so, with or without the "skip wheel-building process" option enabled, I get errors like those found [here](https://pastebin.com/irDYp9S6).

**To Reproduce**
1. Run `pip install faster_than_requests --isolated --disable-pip-version-check --no-cache-dir --no-binary :all:` or simply `pip install faster_than_requests`.
2. Wait a few seconds...
3. See the screen-shattering kaboom.

**Expected behavior**
A proper installation of `faster_than_requests`.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows, version 10 (x64)
 - Anaconda, version 4.7.12
 - Pip, version 19.3.1
 - Python, version 3.7.1

**Additional context**
Additional relevant information available upon request.

**Comment by juancarlospaco** [comment]
Git clone the repo and compile it, [as shown here](https://github.com/juancarlospaco/faster-than-requests#windows)

**Comment by FrankDMartinez** [comment]
I am unfamiliar with Nimble and Docker and a web search turns up too many false positives to be useful. Can You point me in the direction of a good quick-start guide? Thanks in advance.

**Comment by FrankDMartinez** [comment]
Scratch that. I was able to build the DLL. Am I correct in presuming I then copy the file to my `site-packages` directory and change the extension to `pyd`?

**Comment by juancarlospaco** [comment]
Change the file extension from `*.dll` to `*.pyd`.
Copy it on the same folder as the `*.py` that imports it.
