### ISSUE TITLE
Call To `gets()` Results In A `nimpy.ValueError`.

### ISSUE THREAD

**Issue by FrankDMartinez** [juancarlospaco/faster-than-requests#27]
**Describe the bug**
When calling `faster_than_requests.gets(some_url)`, I receive:

```
nimpy.ValueError: Unexpected error encountered: invalid integer:
shell returned 1
```

**To Reproduce**
1. Try to access any valid URL with `gets()`.
2. See error

**Expected behavior**
Either more information as to what is wrong or, better still, no exception.

**Desktop (please complete the following information):**
 - Windows, version 10 (x64)
 - Anaconda, version 4.7.12
 - Python, version 3.7.1

**Additional context**
Additional relevant-information available upon request.

**Comment by juancarlospaco** [comment]
Its optimized for HTTP JSON API.

Try `get2str()`.
