### ISSUE TITLE
"Out of memory" after imports FTR

### ISSUE THREAD

**Issue by xLinkOut** [juancarlospaco/faster-than-requests#28]
**Describe the bug**
After importing ftr, python say "out of memory" and close itself. This happen both using python shell and from a script.

**To Reproduce**
Install ftr from pip
Open python from shell
"import faster_than_requests"

**Expected behavior**
Uhm, idk what to say here, I expected it to work.

**Screenshots**
<img width="656" alt="Schermata 2019-10-21 alle 22 38 11" src="https://user-images.githubusercontent.com/14892153/67241325-8574d480-f453-11e9-8a27-b35f4a3458a4.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Firefox
 - Version 69.0.3

**Smartphone (please complete the following information):**
Not using a smartphone.

**Additional context**
I'm using python venv, if this matter in any way.

**Comment by juancarlospaco** [comment]
Git clone the repo and compile it. https://github.com/juancarlospaco/faster-than-requests#windows

**Comment by xLinkOut** [comment]
So I've compiled it with your istructions, now I have a .pyd and a .nim. What I'm supposed to do now? (I'm on macOS, just in case)

**Comment by juancarlospaco** [comment]
Put the `*.pyd` file on the same folder as the `*.py` file that imports it.

**Comment by xLinkOut** [comment]
**Import error**.
<img width="752" alt="Schermata 2019-10-23 alle 19 13 28" src="https://user-images.githubusercontent.com/14892153/67417554-5b452300-f5c9-11e9-97b6-b70b1d74694e.png">

**Comment by juancarlospaco** [comment]
Try renaming the `*.pyd` to `*.so`, and try again.

**Comment by xLinkOut** [comment]
Ok so this worked, now it run and I can use API functions, thank you! But... I've copied *.nim and *.so files in another directory, where my software is located, then imported in my script but get `Segmentation fault: 11` when run it. Idk if I need to open another issue for this or what...

**Comment by juancarlospaco** [comment]
`*.nim` are not needed after you compile it, you can keep it if you want, but its not required.
`*.nim.cfg` are not needed after you compile it, you can keep it if you want, but its not required.
`*.so` is the only file really needed.
Ideally it should be compiled into a system-wide folder on your Pythons `site-packages/`.
You can try that as a more permanent solution.

**Comment by xLinkOut** [comment]
Thanks a lot for helping me, I've nevere used Nim. I can close now :)

**Comment by dvska** [comment]
macOS

> after
    out of memory
```

$ pip install https://github.com/juancarlospaco/faster-than-requests/archive/master.zip

Collecting https://github.com/juancarlospaco/faster-than-requests/archive/master.zip
Installing collected packages: faster-than-requests
   ...
    Running setup.py install for faster-than-requests ... error
    ERROR: Command errored out with exit status 1:
     command: /venv37/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fv/8s5nyv5d25x_bdf22mjbktd40000gn/T/pip-req-build-_ghqfa_8/setup.py'"'"'; __file__='"'"'/private/var/folders/fv/8s5nyv5d25x_bdf22mjbktd40000gn/T/pip-req-build-_ghqfa_8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/fv/8s5nyv5d25x_bdf22mjbktd40000gn/T/pip-record-pd2r9hx1/install-record.txt --single-version-externally-managed --compile --install-headers /venv37/include/site/python3.7/faster-than-requests
         cwd: /private/var/folders/fv/8s5nyv5d25x_bdf22mjbktd40000gn/T/pip-req-build-_ghqfa_8/
    Complete output (9 lines):
    running install
    running build
    running build_ext
    building 'faster_than_requests' extension
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    clang -bundle -undefined dynamic_lookup -L/usr/local/opt/llvm/lib -I/usr/local/opt/llvm/include -L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.14-x86_64-3.7/faster_than_requests.cpython-37m-darwin.so -s
    clang: error: no input files
    error: command 'clang' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of faster-than-requests
  Moving to /venv37/lib/python3.7/site-packages/faster_than_requests-0.9.6-py3.7.egg-info
   from /venv37/lib/python3.7/site-packages/~aster_than_requests-0.9.6-py3.7.egg-info
  Moving to /venv37/lib/python3.7/site-packages/faster_than_requests.cpython-37m-darwin.so
   from /private/var/folders/fv/8s5nyv5d25x_bdf22mjbktd40000gn/T/pip-uninstall-4et_izmn/faster_than_requests.cpython-37m-darwin.so
ERROR: Command errored out with exit status 1: /venv37/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fv/8s5nyv5d25x_bdf22mjbktd40000gn/T/pip-req-build-_ghqfa_8/setup.py'"'"'; __file__='"'"'/private/var/folders/fv/8s5nyv5d25x_bdf22mjbktd40000gn/T/pip-req-build-_ghqfa_8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/fv/8s5nyv5d25x_bdf22mjbktd40000gn/T/pip-record-pd2r9hx1/install-record.txt --single-version-externally-managed --compile --install-headers /venv37/include/site/python3.7/faster-than-requests Check the logs for full command output.

```

**Comment by juancarlospaco** [comment]
Git clone and Compile it. Use the Source...
:slightly_smiling_face:
