### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by K3nn3th2** [juancarlospaco/faster-than-requests#29]
Hey there!

I have a question regarding the performance of your library. in your example2.py, i moved the time1 and time2 into the for-loop below each respectively two see the actual time it took to get the response from the server, ran it and got this:

Requests = 0.6914482116699219
Faster_than_requests = 10.83625054359436
Faster_than_requests = 0.2046496868133545
Faster_than_requests = 0.20482158660888672
Faster_than_requests = 0.14079642295837402
Faster_than_requests = 0.11947941780090332
Faster_than_requests = 0.12047505378723145
Faster_than_requests = 0.13101911544799805
Faster_than_requests = 0.20536327362060547
Faster_than_requests = 0.20432114601135254
Requests = 5.753178834915161
Faster_than_requests = 0.1209573745727539
Faster_than_requests = 0.16707611083984375
Faster_than_requests = 0.20477294921875
Faster_than_requests = 0.2046821117401123
Faster_than_requests = 0.20487618446350098
Faster_than_requests = 0.2051069736480713
Faster_than_requests = 0.12069845199584961
Faster_than_requests = 0.1858832836151123
Faster_than_requests = 0.20453524589538574
Requests = 0.821847677230835
Faster_than_requests = 0.20351266860961914
Faster_than_requests = 0.20571684837341309
Faster_than_requests = 0.20254945755004883
Faster_than_requests = 0.20587754249572754
Faster_than_requests = 0.20402741432189941
Faster_than_requests = 0.20452356338500977
Faster_than_requests = 0.20508551597595215
Faster_than_requests = 0.2050635814666748
Faster_than_requests = 0.20361590385437012
Requests = 5.839308977127075
Faster_than_requests = 0.2020251750946045
Faster_than_requests = 0.20502758026123047
Faster_than_requests = 0.20466995239257812
Faster_than_requests = 0.20478320121765137
Faster_than_requests = 0.20468997955322266
Faster_than_requests = 0.12096881866455078
Faster_than_requests = 0.18620848655700684
Faster_than_requests = 0.3206334114074707
Faster_than_requests = 0.19153141975402832
Requests = 0.9242508411407471
Faster_than_requests = 0.21742606163024902
Faster_than_requests = 0.18995332717895508
Faster_than_requests = 0.2036573886871338
Faster_than_requests = 0.20474791526794434
Faster_than_requests = 0.20509791374206543
Faster_than_requests = 0.20488739013671875
Faster_than_requests = 0.20490312576293945
Faster_than_requests = 0.20398998260498047
Faster_than_requests = 0.2048048973083496
Requests = 5.634171485900879
Faster_than_requests = 0.20264816284179688
Faster_than_requests = 0.20509052276611328
Faster_than_requests = 0.20397186279296875
Faster_than_requests = 0.20514535903930664
Faster_than_requests = 0.20467352867126465
Faster_than_requests = 0.20493745803833008
Faster_than_requests = 0.20561838150024414
Faster_than_requests = 0.20402288436889648
Faster_than_requests = 0.2041006088256836
Requests = 0.7188794612884521
Faster_than_requests = 0.2036271095275879
Faster_than_requests = 0.20375895500183105
Faster_than_requests = 0.20459461212158203
Faster_than_requests = 0.2049410343170166
Faster_than_requests = 0.2049884796142578
Faster_than_requests = 0.20487117767333984
Faster_than_requests = 0.20487117767333984
Faster_than_requests = 0.2040412425994873
Faster_than_requests = 0.2046959400177002
Requests = 5.736588001251221
Faster_than_requests = 0.22121143341064453
Faster_than_requests = 0.11904406547546387
Faster_than_requests = 0.12100052833557129
Faster_than_requests = 0.15052390098571777
Faster_than_requests = 0.20485424995422363
Faster_than_requests = 0.20472455024719238
Faster_than_requests = 0.2050766944885254
Faster_than_requests = 0.20578455924987793
Faster_than_requests = 0.21968436241149902
Requests = 0.7026252746582031
Faster_than_requests = 0.2062211036682129
Faster_than_requests = 0.21484708786010742
Faster_than_requests = 0.1917572021484375
Faster_than_requests = 0.2038252353668213
Faster_than_requests = 0.20501351356506348
Faster_than_requests = 0.20442986488342285
Faster_than_requests = 0.2047410011291504
Faster_than_requests = 0.2047741413116455
Faster_than_requests = 0.2046823501586914

what i find interesting is the fact that 'vanilla' requests.get seems to be quite fast at the initial run and tends to get worse later on, whereas 'your' .get perfoms worst on the first run and improves significantly during the run.

edit: strange. i ran the script mutliple times with a similar result as described above before writing this post. now i cannot reproduce the behavior. even though i did not change anything..

im posting this anyway to let you know what happened.

**Comment by juancarlospaco** [comment]
I appreciate the comments that it runs well, is expected to get good performance if not the fastest,
having said that and seeing its working I see no big problems here. 
Closing for now, sorry.
:slightly_smiling_face:
