### ISSUE TITLE
Can't install because of:  error: command 'gcc' failed with exit status 1 

### ISSUE THREAD

**Issue by pastet89** [juancarlospaco/faster-than-requests#30]
**Describe the bug**
I can not install the package.

**To Reproduce**
1. pip install faster_than_requests

 - OS: Centos 6
- GCC: gcc-4.4.7-23.el6.x86_64
- Python: 3.6

I am getting:

 ```
 Running setup.py install for unknown ... error
    Complete output from command /usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-jje_g1ha/faster-than-requests/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-iahodbb1/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'faster_than_requests' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I. -I/usr/local/include/python3.6m -c stdlib_macros.c -o build/temp.linux-x86_64-3.6/stdlib_macros.o -flto -ffast-math -march=native -O3
    cc1: error: unrecognized command line option "-flto"
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-jje_g1ha/faster-than-requests/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-iahodbb1/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-jje_g1ha/faster-than-requests/


```

**Comment by juancarlospaco** [comment]
Your GCC is too old.

**Comment by pastet89** [comment]
I've just installed ```9.2```.

Now it gives tons of 
``` /usr/bin/ld: build/temp.linux-x86_64-3.6/stdlib_asyncdispatch.o: warning: sh_link not set for section `__SOMETHING__'
``` errors and crashes with:
```    /usr/bin/ld: unable to place orphaned sharable section .gnu.debuglto_.debug_info (build/temp.linux-x86_64-3.6/stdlib_macros.o)
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
```

**Comment by juancarlospaco** [comment]
Your `ld` is too old. `ld` is `2.33.1`.

**Comment by pastet89** [comment]
I can't install newer version from the repos and I know compiling manualy a non-repo based on can literally brake my entire Centos so I will not play with that.

I really want to try your package as it seems so cool.

Isn't there another way to install it?

**Comment by juancarlospaco** [comment]
*(Millennial voice)*
[Docker](https://hub.docker.com/r/archlinux/base) :grey_question: 
:laughing:

**Comment by pastet89** [comment]
Hmm.. You mean to build a docker and put everything (Python, SQL, etc..) I need inside + faster_than_requests? Then run this in production? Doesn't sound like a good idea to me.

I am rather trying to copy it from the site packages. I installed it successfully on my laptop @ Debian and am trying to copy the needed files to my Centos server.
If you need this might work, any advice is appreciated.

**Comment by juancarlospaco** [comment]
It is really not your bug, is really not my bug.
Distro should provide a backported repo for apps of this decade, like Ubuntu does with PPAs.

Everyone seems to be using Docker nowadays in prod, some also use Vagrant too.

Theres also a new option [BedRock Linux](https://bedrocklinux.org/0.7/distro-support.html), is a Linux that you install on top of your Linux,
but being new it might be more unstable than a docker. Even Windows users use Docker for Windows.

Copying files from one Distro to another may not always work.

As for myself, I use Arch Linux. There are options out there what you use depends on you...
🤷‍♀️

**Comment by pastet89** [comment]
Bueno, gracias de todas maneras por tu tiempo.
