### ISSUE TITLE
Could not load dll

### ISSUE THREAD

**Issue by oiracis** [juancarlospaco/faster-than-requests#32]
I'm getting an error saying "could not load: (libcrypto-1_1-x64|libeay64).dll" when importing the module on python.

I've tried manually installing on system32 but it still didn't work. Any solutions? Thanks.

**Comment by juancarlospaco** [comment]
Module wont go into system32.
Which operating system do you have?.
Whats the module extension?, its not dll.

**Comment by oiracis** [comment]
I compiled the project with this line:
"nim c -d:ssl -d:release --app:lib --out:faster_than_requests.pyd faster_than_requests.nim"

That created a file called faster-than-requests.pyd

I moved that file into my python project and used "import faster_than_requests as requests" on my python script. When executing that single line, it gives the error http://prntscr.com/ps2mds

Everything was compile and all the software is 64 bits, because otherwise it wouldnt compile correctly.

**Comment by juancarlospaco** [comment]
Thats weird most windows have that, [you can download the dll here](https://nim-lang.org/download/dlls.zip)
Unzip it and put it on system32 or current folder. Reboot.

**Comment by oiracis** [comment]
It's been solved, gracias juan.
