### ISSUE TITLE
Threading issues?

### ISSUE THREAD

**Issue by oiracis** [juancarlospaco/faster-than-requests#33]
I'm running faster_than_requests with one thread and it works perfectly fine, however, when I add more threads, it starts doing weird things and basically performance is even worse than running one thread.

Watch it over here: (The numbers are the requests sent)

1 thread:
https://gyazo.com/f349b8be716100a36079175b70bf5a07

10 threads:
https://gyazo.com/5d597dce75ae4115841d5e3c859c07b1

**Comment by jaredliw** [comment]
Nothing wrong, bro. You make many threads at once, so which thread has done first, which one will print first. I advise you to familiar with threading.

**Comment by juancarlospaco** [comment]
Hes right.

**Comment by oiracis** [comment]
@jaredliw That's not the issue. When I do the same with requests or urllib3, It works perfectly and It increments the requests made per second exponentially. This can be seen here:

Requests with 1 thread:
https://gyazo.com/a79a218445f709b1dba033a049f2a871

Requests with 10 threads:
https://gyazo.com/480fca08df0cb52dc931bc005d3aed31

faster-than-requests with 1 thread:
https://gyazo.com/f349b8be716100a36079175b70bf5a07

faster-than-requests with 10 threads:
https://gyazo.com/5d597dce75ae4115841d5e3c859c07b1

Also, when using 10 threads on faster-than-requests and reaching around 100 requests, it throws this:
"Process returned 3221225477 (0xc0000005)"

**Comment by juancarlospaco** [comment]
I guess it depends how you compiled it.

**Comment by oiracis** [comment]
I compiled it using this lines:

"nim c -d:ssl -d:release --app:lib --out:faster_than_requests.pyd faster_than_requests.nim"

I don't get why such error would happen?

**Comment by juancarlospaco** [comment]
On the same `/src/` folder of the repo?.

**Comment by oiracis** [comment]
Yes

**Comment by juancarlospaco** [comment]
is the example code open source?.

**Comment by oiracis** [comment]
Do you mean the code I'm running?

**Comment by juancarlospaco** [comment]
yes.

**Comment by oiracis** [comment]
Here it is:

https://hastebin.com/mapizeheji.py

**Comment by jaredliw** [comment]
@oiracis Sorry, I can't help you. For me, I request for the same URL by using requests, urllib3, faster-than-requests +threading. the results gave me were all non-linear. I think the things affect may just like @juancarlospaco said, the way you compile as you use 'nim' and I just simply use 'python'.

**Comment by juancarlospaco** [comment]
From this:

```python
import time
import requests
import faster_than_requests
import threading


check_url = "https://httpbin.org/get"

c = 0
def requests():
    global c
    while True:
        r = requests.get(check_url).text
        c = c + 1
        print("\t" + str(c))


for x in range(25):
    t = threading.Thread(target=requ)
    t.start()

```

To this:

```nim
import threadpool, httpclient, pylib
include pylib/range


var check_url = "https://httpbin.org/get"

var c = 0
proc ftr() =
    var client = new_http_client()
    while True:
        var r = client.get_content(check_url)
        c = c + 1
        print("\t", c)


for x in range(25):
    spawn ftr()
```

So it seems is the Python interpreter lagging behind, this version is faster,
Python also "jumps" and freeze for 1 second and jumps again and repeats.
🤷‍♀️

**Comment by oiracis** [comment]
But the thing is I was trying to use faster-than-requests for its performance compared to urllib3. Isn't there any other workaround?

**Comment by juancarlospaco** [comment]
Added Multi-Threading. 

- Passing `threads = True` uses Multi-Threading.
- Passing `threads = False` will *Not* use Multi-Threading.
- Omitting that argument will *Not* use Multi-Threading.

Example usage: https://github.com/juancarlospaco/faster-than-requests/blob/master/examples/example3.py#L10

:slightly_smiling_face:
