### ISSUE TITLE
got this error when using faster than requests when using proxy settings export

### ISSUE THREAD

**Issue by saiv94** [juancarlospaco/faster-than-requests#34]
nimpy.SslError: Unexpected error encountered: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init

It works perfectly fine with request library but.
I used proxy setting

**Comment by juancarlospaco** [comment]
Can you share the code that reproduces the bug :grey_question: 
Hard to debug without code...

**Comment by juancarlospaco** [comment]
Fixed on Master.
