### ISSUE TITLE
Latest version not available from PyPI

### ISSUE THREAD

**Issue by cassiobotaro** [juancarlospaco/faster-than-requests#35]
**Describe the bug**
```
$ pip install faster_than_requests==0.9.0 
ERROR: Could not find a version that satisfies the requirement faster_than_requests==0.9.0 (from versions: 0.1, 0.5)
ERROR: No matching distribution found for faster_than_requests==0.9.0
```

**To Reproduce**
pip install faster_than_requests==0.9.0

**Expected behavior**
Install latest version

**Additional context**
python: 3.8.0
pip: 19.3.1

**Comment by dwightmulcahy** [comment]
:sadpanda:

**Comment by juancarlospaco** [comment]
Automagically Published to PYPI via GitHub Actions.
https://github.com/juancarlospaco/faster-than-requests/commit/a4be5be5ef7dfbe110df882a9fe45cfb869ff336/checks?check_suite_id=336800193
`0.9.2` is really just `0.9.0` but PYPI wont allow overwrite versions nor files so I have to bump version.
The GitHub Action builds and publish from scratch on each new Release.
More improvements can be made on the future, but basically its working now.
:slightly_smiling_face:
