### ISSUE TITLE
Failed installing on "Termux, Android Apps"

### ISSUE THREAD

**Issue by khaclep007** [juancarlospaco/faster-than-requests#36]
I got error when installing using pip

 `Running setup.py install for faster-than-requests ... error
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-ui2ljm43/faster-than-requests/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-ui2ljm43/faster-than-requests/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg install --record /data/data/com.termux/files/usr/tmp/pip-record-u7nv0iyn/install-record.txt --single-version-externally-managed --compile
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-ui2ljm43/faster-than-requests/
    Complete output (9 lines):
    running install
    running build
    running build_ext
    building 'faster_than_requests' extension
    creating build
    creating build/temp.linux-aarch64-3.7
    aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -Oz -fstack-protector-strong -Oz -fPIC -I. -I/data/data/com.termux/files/usr/include/python3.7m -c stdlib_sets.c -o build/temp.linux-aarch64-3.7/stdlib_sets.o -flto -ffast-math -march=native -O3
    clang-9: error: the clang compiler does not support '-march=native'
    error: command 'aarch64-linux-android-clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-ui2ljm43/faster-than-requests/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-ui2ljm43/faster-than-requests/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg install --record /data/data/com.termux/files/usr/tmp/pip-record-u7nv0iyn/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.`

gcc version: 

>`$ gcc --version
clang version 9.0.0 (tags/RELEASE_900/final)
Target: aarch64-unknown-linux-android
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin`

Python Version :

>`$ python --version 
Python 3.7.5`

**Comment by juancarlospaco** [comment]
Git Clone and Compile it.
Check the GitHub Actions it builds it from scratch manually.
Check the Windows Instructions on the readme also builds it from scratch manually.
