### ISSUE TITLE
proxy shows nimpy.SslError: Unexpected error encountered: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init

### ISSUE THREAD

**Issue by saivignan-malyala** [juancarlospaco/faster-than-requests#37]
**without export of my http_proxy and https_proxy, it works fine:**
![image](https://user-images.githubusercontent.com/22785987/69812749-c8765480-1216-11ea-841a-0e0ce4b9eecc.png)

**with export of http_proxy and https_proxy, I get this error:**
i first did: 
export https_proxy="https:myproxy.com:8000/"
export http_proxy="http:myproxy.com:8000"
![image](https://user-images.githubusercontent.com/22785987/69813389-1770b980-1218-11ea-8b39-f618c2fee0f7.png)

And it works perfectly fine with python requests module with proxy parameter.
Please let me know whats the issue here with faster than requests with proxy?

**Comment by juancarlospaco** [comment]
For HTTPS the URL must be HTTPS.
You can also try the request function that has a proxy argument.
