### ISSUE TITLE
Is it possible to send Post requests with the "Content Type" of type "multipart / form-data"?

### ISSUE THREAD

**Issue by alexander-ae** [juancarlospaco/faster-than-requests#38]
I would like to send a form similar to:

`POST /test.html HTTP/1.1 
Host: example.org 
Content-Type: multipart/form-data;boundary="boundary" 

--boundary 
Content-Disposition: form-data; name="field1" 

value1 
--boundary 
Content-Disposition: form-data; name="field2"; filename="example.txt" 

value2`

Is it possible to use **faster-than-requests** for something like that?

**Comment by juancarlospaco** [comment]
Just set the HTTP Header, with `set_header()`. Also `request()` has it too. 
`[("Content Type", "foo bar"), ("DNT", "1")]` or similar.
:slightly_smiling_face:

**Comment by alexander-ae** [comment]
I tried to reproduce the following query made with curl:


> curl 'https://es.babelio.com/resrecherche.php' -H 'Content-Type: multipart/form-data; boundary=----Boundary' --data-binary $'------Boundary\r\nContent-Disposition: form-data; name="Recherche"\r\n\r\n9780345805362\r\n------Boundary\r\nContent-Disposition: form-data; name="recherche"\r\n\r\n \r\n------Boundary\r\nContent-Disposition: form-data; name="item_recherche"\r\n\r\nisbn\r\n------Boundary--\r\n'

My problem is how to send the **"data-binary"** parameter with **faster-than-requests**

I understand that faster-than-requests uses Nim's Http Client, and specifically uses the *postContent* method:

"https://nim-lang.org/docs/httpclient.html#postContent"

postContent has the parameter **multipart** but is not sent from faster-than-requests.

How could I reproduce the previous query made with curl?

**Comment by juancarlospaco** [comment]
Oh, now I understand, you are right, that is not supported on the current version.

**Comment by alexander-ae** [comment]
I understand, thanks for your support anyway.

faster-than-requests is helping me a lot. I hope that in the future we can count on this feature.

**Comment by juancarlospaco** [comment]
https://github.com/juancarlospaco/faster-than-requests/blob/master/examples/post_multipart.py
