### ISSUE TITLE
Import error in VS Code

### ISSUE THREAD

**Issue by SnappierSoap318** [juancarlospaco/faster-than-requests#39]
I'm getting an import error in python 3.8.0 version I have successfully compiled and have put the .pyd file into the directory containing the python script, I have even tried putting sys.path.append() function but still, it doesn't work. I have put the necessary DLLs into system32

I am running win10 version 1903, Build 18362.476 64bit

python version and import error
![Annotation 2019-12-08 130430](https://user-images.githubusercontent.com/42905211/70386118-74f4cb00-19bb-11ea-96cf-6badc30e781c.jpg)

folder:
![Annotation 2019-12-08 130515](https://user-images.githubusercontent.com/42905211/70386122-86d66e00-19bb-11ea-826c-e8671dc9dc79.jpg)

code inside fasterDownloader.py
```
import sys
sys.path.append('D:/Python/ModPack Downloader')

import faster_than_requests as requests
import json
import os
import re


file_url = []

with open('manifest.json') as json_file:
    # Getting data from the json file
    data = json.load(json_file)

    # getting the Minecraft version and modpack name
    minecraft_version = data['minecraft']['version']
    modpack_name = data['name']

    # Making Directories and Changing the current working directories
    try:
        os.mkdir(modpack_name + ' ' + minecraft_version)
    except:
        print('Directory already exists so skipping')
    os.chdir(modpack_name + ' ' + minecraft_version)
    try:
        os.mkdir('mods')
    except:
        print('Directory already exists so skipping')
    os.chdir('mods')
    for ID in data['files']:
        file_url.append('https://addons-ecs.forgesvc.net/api/v2/addon/%s/file/%s/download-url'%(str(ID['projectID']),str(ID['fileID'])))


for url in file_url:
    url = re.findall(
            'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', url.replace(" ","%20"))

requests.download2([(urls,os.path.basename(urls)) for urls in file_url])```

**Comment by juancarlospaco** [comment]
That should work, is that a Terminal of VS Code?, I wonder if is some kind of Bug of VS Code failing to detect the file.

Try download and decompress [this DLL](https://nim-lang.org/download/dlls.zip) into system32 folder.

Try renaming the folder from `'D:/Python/ModPack Downloader'` to `'D:/Python/modpack_downloader'` to see if VS Code takes it.

On Antivirus make an exception globally to skip all `*.pyd`, if you have antivirus.

On the code, put the import of std lib first, and the faster_than_requests last.

Reboot and try again.
:thinking:

**Comment by SnappierSoap318** [comment]
I already did that cause some other devs had that problem but didnt work

**Comment by SnappierSoap318** [comment]
> That should work, is that a Terminal of VS Code?, I wonder if is some kind of Bug of VS Code failing to detect the file.
> 
> Try to download and decompress [this DLL](https://nim-lang.org/download/dlls.zip) into the system32 folder.
> 
> Try renaming the folder from `'D:/Python/ModPack Downloader'` to `'D:/Python/modpack_downloader'` to see if VS Code takes it.
> 
> On Antivirus make an exception globally to skip all `*.pyd` if you have antivirus.
> 
> On the code put the import of std lib first, and the faster_than_requests last.
> 
> Reboot and try again.
> 🤔

I Don't think the error is with vs code cause when I tried to import the .pyd file using cmd after selecting the directory containing the .pyd it doesn't import it either, also when I [searched](https://stackoverflow.com/questions/8846480/error-importing-a-pyd-file-as-a-python-module-from-a-pyo-file) on google it showed me there are 3 ways that the error can occur and I quote

> 1.The .pyd is not in your current path (you said it was in the same folder so that should not be the problem)
> 2. A DLL the .pyd depends on is not in your current path. Locate the missing DLL's using depends.exe or its modern rewrite and either copy these DLL's to the same folder or add the containing directories to your system path
> 3. You're using a debug version of python. Then the module must be renamed from xyz.pyd to xyz_d.pyd.

**Comment by juancarlospaco** [comment]
The file wont need to be renamed, I never renamed it.

**Comment by SnappierSoap318** [comment]
Oh btw, when i tried to install via pip, it showed error so i tried to update the build tools restarted and then tried again but didnt work so then i tried compiling the source and this happened

**Comment by juancarlospaco** [comment]
I dont know what to say about it, is something on your path or config.
I use Docker for Windows on Windows, and everyone seems to be using Docker anyways,
maybe you can try that too, I am not Windows expert.
🤷‍♀️

**Comment by SnappierSoap318** [comment]
Ok so apparently WSL can install the library using pip and I can import it inside the subsystem and it works, 

so here is a short version of how I made it work
tutorial on how to [install](https://docs.microsoft.com/en-us/windows/wsl/install-win10) WSL

after that just install pip and install the library using the commands and just import and use 

anyways thanks for the support and help on this.
