### ISSUE TITLE
get status code of get

### ISSUE THREAD

**Issue by simonbonnefoy** [juancarlospaco/faster-than-requests#40]
Hi, 

I have been searching through the doc. How can I cant the status code of a request?
Something similar to:
>>> r = requests.get('https://httpbin.org/get')
>>> r.status_code
200

thanks!

**Comment by juancarlospaco** [comment]
```python
requests.get('https://httpbin.org/get')["status"]
```

**Comment by simonbonnefoy** [comment]
Thanks! this seems to work only with the method 
`requests.get()`
I have to use 
`requests.get2str()`
Because I get an error on several website using get method:
`Python 3.8.0 (default, Oct 23 2019, 18:51:26) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faster_than_requests as requests
>>> requests.get("http://www.ebizmba.com/articles/blogs")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
nimpy.ValueError: Unexpected error encountered: invalid integer: `

Not sure how to solve that

**Comment by juancarlospaco** [comment]
Its optimized for HTTP REST JSON API.
Use `get2str()`  or full `request()`.

**Comment by simonbonnefoy** [comment]
OK, I see.
Thanks a lot!

**Comment by juancarlospaco** [comment]
So if you need like work with APIs, REST JSON, Downloads, Scraper, etc you can use the `get()` and similar.
If you need like human readable string `get2str()`.

If you need like human readable interactive like line-by-line, probably httpie or Insomnia may be better.
*So basically is working, closing for now...*
:slightly_smiling_face:

**Comment by FalconDigital** [comment]
Sir Can u Explain how to use this for one session ? 
so i can login and Do extra thing ?

**Comment by juancarlospaco** [comment]
Set the Headers, on HTTP theres only Header, Body and URL, nothing more,
so all stuff like users, tokens, mime, etc goes all into the Headers.
Maybe install https://insomnia.rest and try hitting the URL with the header.
