### ISSUE TITLE
Fail to install windows - freezes

### ISSUE THREAD

**Issue by Nightingale131** [juancarlospaco/faster-than-requests#42]
Hi,

I tried to install it via pip install faster_than_requests
It freezez completly and blocks me off from doing anything on the computer

I've got:
GCC 8.2
Python 3.7

It stops at:
```
C:\Users\thoma>pip install faster_than_requests

Collecting faster_than_requests

  Using cached https://files.pythonhosted.org/packages/90/15/72ffe29bf34b40b4b9881a89e0fbbf9d22ea0b493681965fd08ce1fafa7b/faster_than_requests-0.9.2.zip

Building wheels for collected packages: faster-than-requests
  Building wheel for faster-than-requests (setup.py) 
```

**Comment by juancarlospaco** [comment]
https://github.com/juancarlospaco/faster-than-requests#windows

**Comment by Nightingale131** [comment]
Still doesn't work. Steps which I've covered:

1. Download MinGW and install gcc
![image](https://user-images.githubusercontent.com/58428501/70903037-4e0f4800-1ffe-11ea-8e55-244ba4a65268.png)

2. Download Nim and DLLs package
![image](https://user-images.githubusercontent.com/58428501/70903176-9890c480-1ffe-11ea-816c-471edacb2c41.png)

3. Finish in nim:
![image](https://user-images.githubusercontent.com/58428501/70903255-c7a73600-1ffe-11ea-940b-c4315a4c1970.png)

4. Downloaded zip of faster_than_requests

5. Git Bash in src folder
![image](https://user-images.githubusercontent.com/58428501/70903567-72b7ef80-1fff-11ea-9875-7a01e94345a1.png)

6. Chnaged faster_than_requests.dll to .pyd

7. Copied it do DLLs directory of python

Yet still I get an error:
![image](https://user-images.githubusercontent.com/58428501/70903712-be6a9900-1fff-11ea-944d-227791fe3063.png)

**Comment by juancarlospaco** [comment]
GCC should be `9.2.0`.
it should be `*.pyd` not `*.dll`.
Your Python has an error on the PATH.
Try it on vanilla Python console.

**Comment by Nightingale131** [comment]
Works! Thank you!

**Comment by juancarlospaco** [comment]
Cool. :slightly_smiling_face: :+1:
