### ISSUE TITLE
faster-than-requests install problem

### ISSUE THREAD

**Issue by dev-hashem** [juancarlospaco/faster-than-requests#43]
hello , i have problem with install it

python version :  3.8.0

gcc : 

C:\Windows\System32>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --with-gmp=/mingw --with-mpfr --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)

[Problem is] :

Collecting faster_than_requests
  Using cached https://files.pythonhosted.org/packages/90/15/72ffe29bf34b40b4b9881a89e0fbbf9d22ea0b493681965fd08ce1fafa7b/faster_than_requests-0.9.2.zip
Installing collected packages: faster-than-requests
    Running setup.py install for faster-than-requests ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\win10\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\win10\\AppData\\Local\\Temp\\pip-install-1myznyeu\\faster-than-requests\\setup.py'"'"'; __file__='"'"'
C:\\Users\\win10\\AppData\\Local\\Temp\\pip-install-1myznyeu\\faster-than-requests\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' in
stall --record 'C:\Users\win10\AppData\Local\Temp\pip-record-7p_sim4s\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\win10\AppData\Local\Temp\pip-install-1myznyeu\faster-than-requests\
    Complete output (19 lines):
    running install
    running build
    running build_ext
    building 'faster_than_requests' extension
    creating build
    creating build\temp.win32-3.8
    creating build\temp.win32-3.8\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Ic:\users\win10\appdata\local\programs\python\python38-32\include -Ic:\users\win10\appdata\local\prog
rams\python\python38-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt"
"-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18
362.0\cppwinrt" /Tc@m..@s..@s..@s..@s.nimble@spkgs@snimpy-0.1.0@snimpy.nim.c /Fobuild\temp.win32-3.8\Release\@m..@s..@s..@s..@s.nimble@spkgs@snimpy-0.1.0@snimpy.nim.obj -flto -ffast-math -march=native -mtune=native -O3 -fno-ident -fsingle-precision-constant
    cl : Command line warning D9002 : ignoring unknown option '-flto'
    cl : Command line warning D9002 : ignoring unknown option '-ffast-math'
    cl : Command line warning D9002 : ignoring unknown option '-march=native'
    cl : Command line warning D9002 : ignoring unknown option '-mtune=native'
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    cl : Command line warning D9002 : ignoring unknown option '-fno-ident'
    cl : Command line warning D9002 : ignoring unknown option '-fsingle-precision-constant'
    @m..@s..@s..@s..@s.nimble@spkgs@snimpy-0.1.0@snimpy.nim.c
    C:\Users\win10\AppData\Local\Temp\pip-install-1myznyeu\faster-than-requests\nimbase.h(457): error C2118: negative subscript
    @m..@s..@s..@s..@s.nimble@spkgs@snimpy-0.1.0@snimpy.nim.c(10): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\win10\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\win10\\AppData\\Local\\Temp\\pip-install-1myznyeu\\faster-than-reques
ts\\setup.py'"'"'; __file__='"'"'C:\\Users\\win10\\AppData\\Local\\Temp\\pip-install-1myznyeu\\faster-than-requests\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(cod
e, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\win10\AppData\Local\Temp\pip-record-7p_sim4s\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by juancarlospaco** [comment]
https://github.com/juancarlospaco/faster-than-requests#windows

**Comment by dev-hashem** [comment]
i got same error 

is there any solution ?

**Comment by juancarlospaco** [comment]
GCC is `9.2.0`, your GCC is `6.3.0`.
Your Python is 32Bit I think ?.

**Comment by dev-hashem** [comment]
i change it 
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/msys32/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-9.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++ --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --enable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev2, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 9.2.0 (Rev2, Built by MSYS2 project)

**Comment by dev-hashem** [comment]
yes is 32

**Comment by juancarlospaco** [comment]
Everything should be 64Bit.

**Comment by dev-hashem** [comment]
i change it to 64

**Comment by dev-hashem** [comment]
PS C:\xampp\htdocs\python> pip install faster-than-requests --user
Collecting faster-than-requests
  Using cached https://files.pythonhosted.org/packages/90/15/72ffe29bf34b40b4b9881a89e0fbbf9d22ea0b493681965fd08ce1fafa7b/faster_than_requests-0.9.2.zip
Building wheels for collected packages: faster-than-requests
  Building wheel for faster-than-requests (setup.py) ... error

**Comment by juancarlospaco** [comment]
Git clone and compile, [as shown here.](https://github.com/juancarlospaco/faster-than-requests#windows)
