### ISSUE TITLE
How to pass auth=(username, password) with faster-than-requests

### ISSUE THREAD

**Issue by Dan-coder-92** [juancarlospaco/faster-than-requests#44]
Hi,

I'm trying to convert a requests query on the following format that uses the auth keyword and passes username and password as a tuple: 

`r = requests.post(url, data={key0: value0, key1: value1, ...}, auth=(username, password))`

Any aid regarding how to convert the authorization part would be very appreciated. I can't seem to figure out how to use either the multipart_data arg or the set_headers() function to this end. Thanks in advance!

**Comment by juancarlospaco** [comment]
- Headers: `[("Authorization", "Basic QWxhZGRpbjpPcGVuU2VzYW1l"), ("DNT", "1")]`
- URL: `https://username:password@server.com/example`
