### ISSUE TITLE
HEAD method

### ISSUE THREAD

**Issue by ikewzer0** [juancarlospaco/faster-than-requests#45]
Hi, 

Would i be able to make a HEAD request using faster-than-requests using this? or check the status of number of hosts without reading the whole response body ?

**Comment by juancarlospaco** [comment]
Yes

**Comment by ikewzer0** [comment]
may i know how i can achieve this ?

**Comment by juancarlospaco** [comment]
Reading the Documentation

**Comment by ikewzer0** [comment]
Hi @juancarlospaco i have gone through the Documentation again, i don't find a way to get headers only without response body. or anyway i can do requests.head(url)

**Comment by juancarlospaco** [comment]
HEAD is now literally `requests.head(url)`.

**Comment by ikewzer0** [comment]
I get the following error when i use head method.

```
Traceback (most recent call last):
  File "ftrhead.py", line 1, in <module>
    import faster_than_requests as requests
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/lib/python3.8/site-packages/faster_than_requests-0.9.6-py3.8-linux-x86_64.egg/faster_than_requests.py", line 7, in <module>
  File "/usr/lib/python3.8/site-packages/faster_than_requests-0.9.6-py3.8-linux-x86_64.egg/faster_than_requests.py", line 6, in __bootstrap__
  File "/usr/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dynamic module does not define module export function (PyInit_faster_than_requests)
```

**Comment by juancarlospaco** [comment]
It is an installation error, I dont know how you installed it, use it from git master.

**Comment by ikewzer0** [comment]
i used git to install it

**Comment by ikewzer0** [comment]
previously i used pip .. the new HEAD update is not in the pip ..

**Comment by ikewzer0** [comment]
i use `python setup.py install` to install

**Comment by juancarlospaco** [comment]
Git clone the repo and compile, theres instructions on documentation and on the GitHub Actions,
or wait for a release.
:slightly_smiling_face:

**Comment by ikewzer0** [comment]
no worries.. i managed to compile it , was a bit differed in arch linux
```
yay -S nim nimble
nimble install nimpy
```
then compiled.. 

but the head method is making a full http request with the body.. not just a HEAD request. see comparison below

**Comment by ikewzer0** [comment]
```
import time
import requests as requests_old
import faster_than_requests as requests

time1 = time.time()
rr = requests.get("http://ipv4.download.thinkbroadband.com/5MB.zip")
print(rr['headers'])
print(f'\nfaster_than_requests = {time.time() - time1}\n')


time2 = time.time()
rr2 = requests_old.head("http://ipv4.download.thinkbroadband.com/5MB.zip")
print (rr2.headers)
print(f'\nOld Requests = {time.time() - time2}')
```

![ftr](https://user-images.githubusercontent.com/21004441/71669292-fe66a580-2d8d-11ea-8682-c58a6ae08330.png)

**Comment by juancarlospaco** [comment]
I added a new example exclusively for you https://github.com/juancarlospaco/faster-than-requests/blob/master/examples/example_head.py

Git pull, recompile, and try again following the example. :slightly_smiling_face:

**Comment by ikewzer0** [comment]
Thanks for the quick updates :) i totally love this project of urs.. :+1: 

i made a git pull and updated. did a HEAD requests with your example.. i get the following error msg.. all other request method are working well though.

`Segmentation fault (core dumped)`

what might be the issue ?

**Comment by ikewzer0** [comment]
![Screenshot from 2020-01-03 00-16-15](https://user-images.githubusercontent.com/21004441/71686852-37b70980-2dbe-11ea-86c4-d6b9760f27cd.png)

**Comment by juancarlospaco** [comment]
```console
$ git pull https://github.com/juancarlospaco/faster-than-requests.git
$ nim c -f -d:release -d:danger --app:lib --gc:markAndSweep --out:faster_than_requests.so faster_than_requests.nim
```

Copy `faster_than_requests.so` to the same folder as `example_head.py`.
If you had it installed with PIP previously, then uninstall it `sudo pip3 uninstall faster-than-requests`.
Run `python3 example_head.py` 
(do not rename `faster_than_requests.so`).

If problems continue paste the output of `faster_than_requests.debugs()`.

**Comment by ikewzer0** [comment]
awesome :)

```
import time
import requests as requests_old
import faster_than_requests as requests

time1 = time.time()
rr = requests.head("http://ipv4.download.thinkbroadband.com/100MB.zip")
print (rr['headers'])
print(f'\nfaster_than_requests = {time.time() - time1}\n')

time2 = time.time()
rr2 = requests_old.head("http://ipv4.download.thinkbroadband.com/100MB.zip")
print (rr2.headers)
print(f'\nOld Requests = {time.time() - time2}')
```
![Screenshot from 2020-01-03 00-33-01](https://user-images.githubusercontent.com/21004441/71687891-94b3bf00-2dc0-11ea-8a04-143cf0421ca8.png)

**Comment by ikewzer0** [comment]
can i use the HEAD method with requests2 ? i want to have a timeout for HEAD.. is this doable ?

**Comment by ikewzer0** [comment]
also there's an issue while calling head method for some domains and ips, see example request below.

```
import requests as requests_old
import faster_than_requests as requests

print('Output of old requests')
print (requests_old.head("https://google.com").headers)
print (requests_old.head("http://18.204.81.190").headers)
print (requests_old.head("http://ipv4.download.thinkbroadband.com/5MB.zip").headers)

print('\nOutput of faster_than_requests')
try:print(requests.head("https://google.com")['headers'])
except Exception as e: print (e)

try:print(requests.head("http://18.204.81.190")['headers'])
except Exception as e: print (e)

try:print(requests.head("http://ipv4.download.thinkbroadband.com/5MB.zip")['headers'])
except Exception as e: print (e)
```
![Screenshot from 2020-01-16 16-20-38](https://user-images.githubusercontent.com/21004441/72520806-0ccbbb80-387c-11ea-91df-22e3447f0c98.png)

**Comment by ikewzer0** [comment]
hi @juancarlospaco may I know what might be the issue here.. thanks and much appreciate your awesome work

**Comment by juancarlospaco** [comment]
Fixed.

**Comment by juancarlospaco** [comment]
Example exclusively for you: https://github.com/juancarlospaco/faster-than-requests/blob/master/examples/bug45.py

**Comment by ikewzer0** [comment]
i followed the build method i used earlier.. but failed to build :( still trying

**Comment by ikewzer0** [comment]
```
(.text+0x0): multiple definition of `nimpy_nimpyDatInit000'; build/temp.linux-x86_64-3.8/@m..@s..@s..@s..@s..@sroot@s.nimble@spkgs@snimpy-0.1.0@snimpy.nim.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

```

**Comment by juancarlospaco** [comment]
- Reboot.
- Add `--forceBuild` to the compile command.
Looks like a cache problem on your end.

**Comment by ikewzer0** [comment]
./package.sh
./build.sh
sudo python setup.py install --force

that worked for me on arch.. this nim thing is new for me :/

**Comment by ikewzer0** [comment]
working well :D HEAD method is now perfect, ur a legend :+1:

**Comment by ikewzer0** [comment]
i hope you add timeout sometime when ur free.. much appreciate ur work..

**Comment by juancarlospaco** [comment]
Ok, yes.

**Comment by juancarlospaco** [comment]
Done.
https://github.com/juancarlospaco/faster-than-requests#how-to-set-timeout

**Comment by ikewzer0** [comment]
okay that works :) but is there a way to set it inside the script ? 
```
import faster_than_requests as requests
REQUESTS_TIMEOUT = 42000
print(requests.head("https://google.com"))
```
something like that ? would that work ?

**Comment by ikewzer0** [comment]
or maybe set a specific timeout for requests.head and another timeout for requests.head ?

**Comment by juancarlospaco** [comment]
```python
import os
os.putenv("REQUESTS_TIMEOUT", 42000)  # at the very beginning preferably. 
```

**Comment by ikewzer0** [comment]
cool.. that works..
