### ISSUE TITLE
have bug when use a requests2

### ISSUE THREAD

**Issue by ahmedhaies** [juancarlospaco/faster-than-requests#46]
- **Please paste the output of `faster_than_requests.debugs()`.**
{
  "proxyUrl": "",
  "timeout": "",
  "userAgent": "",
  "maxRedirects": "",
  "nimVersion": "1.0.4",
  "httpCore": "Nim httpclient/1.0.4",
  "cpu": "amd64",
  "os": "linux",
  "endian": "littleEndian",
  "release": true,
  "danger": true,
  "CompileDate": "2019-12-24",
  "CompileTime": "02:03:09",
  "tempDir": "/tmp/",
  "ssl": true,
  "currentCompilerExe": "/home/runner/.choosenim/toolchains/nim-1.0.4/bin/nim",
  "int.high": 9223372036854775807
}

- **Describe the bug**
nimpy.ValueError: Unexpected error encountered: invalid integer: 

- **code is**
```import faster_than_requests as req
print(req.requests2(url="http://httpbin.org/get", http_method="get", body="", http_headers=[("key", "value")],
							proxyUrl="socks5h://localhost:9050", proxyAuth="",
							userAgent=str(choice(agents)), timeout=1099, maxRedirects=1)
		)
```

**Comment by ahmedhaies** [comment]
proxy is tor
also we need new function with proxy to get a text like requests

**Comment by juancarlospaco** [comment]
Typo on Proxy URL `socks5h://` should be `socks5://`. :woman_shrugging:

**Comment by ahmedhaies** [comment]
i try this but not resolve problem
this is new code
```
def main():
	req.debugs()
	print(req.requests2(url="http://httpbin.org/get", http_method="get", body="", http_headers=[("key", "value")],
							proxyUrl="socks5://localhost:9050", proxyAuth="",
							userAgent=str(choice(agents)), timeout=1099, maxRedirects=1)
		)
```
```
/usr/bin/python3.7 /home/ahmedhaies/PycharmProjects/start_from_here.py
{
  "proxyUrl": "",
  "timeout": "",
  "userAgent": "",
  "maxRedirects": "",
  "nimVersion": "1.0.4",
  "httpCore": "Nim httpclient/1.0.4",
  "cpu": "amd64",
  "os": "linux",
  "endian": "littleEndian",
  "release": true,
  "danger": true,
  "CompileDate": "2019-12-24",
  "CompileTime": "02:03:09",
  "tempDir": "/tmp/",
  "ssl": true,
  "currentCompilerExe": "/home/runner/.choosenim/toolchains/nim-1.0.4/bin/nim",
  "int.high": 9223372036854775807
}
Traceback (most recent call last):
  File "/home/ahmedhaies/PycharmProjects/start_from_here.py", line 31, in <module>
    main()
  File "/home/ahmedhaies/PycharmProjects/start_from_here.py", line 26, in main
    userAgent=str(choice(agents)), timeout=1099, maxRedirects=1)
nimpy.ValueError: Unexpected error encountered: invalid integer: 
```

**Comment by juancarlospaco** [comment]
Can you try HTTP Proxy or no proxy instead?.
It works for me.

**Comment by ahmedhaies** [comment]
proxy socks5 is very necessary
you can made new update to fix this bug
your lib is amazing

**Comment by ahmedhaies** [comment]
i'm tried with no proxy and this work good but the socks5 proxy is very important

**Comment by juancarlospaco** [comment]
HTTP Proxy is supported. socks5 is not, at least for now.
:crying_cat_face:

**Comment by ahmedhaies** [comment]
ok thanks your lib is very amazing but i can't use it for now because socks5 bug 
also we need some flexibility like requests
