### ISSUE TITLE
How to handle SslError?

### ISSUE THREAD

**Issue by Qwerty-Space** [juancarlospaco/faster-than-requests#47]
When using ^C I get nimpy.SslError, I would like to handle this with KeyboardInterrupt.  How can I do this?

**Comment by juancarlospaco** [comment]
```nim
try: 
    input()  # Mimic some logic here, no need for actual input call.
except KeyboardInterrupt as error:
    print(error)
    sys.exit(0)
```

Basically use Python std lib batteries.
:slightly_smiling_face:

**Comment by Qwerty-Space** [comment]
I think you misunderstand

I would like to do `except SslError` but it doesn't accept that

**Comment by juancarlospaco** [comment]
But it is really a ctrl+c keyboardinterrupt.
Then stuff going down as requested.

**Comment by Qwerty-Space** [comment]
How can I `except` the Ssl error?

**Comment by juancarlospaco** [comment]
Python do not have that feature.
🤷‍♀️

**Comment by Qwerty-Space** [comment]
It does though

**Comment by Qwerty-Space** [comment]
Okay, another question.  How would I handle this error using try...except?

![image](https://user-images.githubusercontent.com/6967592/72665799-b8534800-3a03-11ea-820e-dbf27508c77c.png)

**Comment by juancarlospaco** [comment]
That is a broken download, corrupted file on the server or bad network connection.
We plan to add a feature to retry on the future, but does not exist yet.

**Comment by Qwerty-Space** [comment]
I mean, how can I do something like this:

```try:
  requests.download(url, file)
except nimpy.ProtocolError:  # this line doesn't work
  pass
``` 
![image](https://user-images.githubusercontent.com/6967592/72666061-78419480-3a06-11ea-9311-6946df70c154.png)

**Comment by juancarlospaco** [comment]
I did not add nor remove any exception on the code whatsoever, 
messages may be printed and are lower level C libs of your system,
similar when you use stuff like PyGTK you see messages printed that you do not added to the actual code.

**Comment by juancarlospaco** [comment]
We plan to add a feature to retry on the future, but does not exist yet.

**Comment by Qwerty-Space** [comment]
All I want to be able to do is handle errors that faster_than_requests throws at me

**Comment by udf** [comment]
@Qwerty-Space You can handle exceptions from faster_than_requests:

```python
import faster_than_requests as requests
import sys

try:
    r = requests.get("asdasd")
except:
    e = sys.exc_info()
    print('e', e)
```
prints
```
e (<class 'nimpy.ValueError'>, ValueError('Unexpected error encountered: No uri scheme supplied.'), <traceback object at 0x7fd734a98280>)
````
when ran

It might be a bug that exceptions like `nimpy.SslError` and `nimpy.ProtocolError` can't be caught in Python.

**Comment by juancarlospaco** [comment]
```python
try:
  requests.download(url, file)
except Exception as error_to_inspect:
  print(error_to_inspect)
  check_exception(error_to_inspect)

```

This is just pseudo code example. Basically catch an general `Exception` and inspect what it is, that is the point of Exception being a type.

**Comment by Qwerty-Space** [comment]
check_exception() isn't even a valid python function

**Comment by udf** [comment]
@juancarlospaco  You should also be able to `except requests.NimPyException:`, right?

**Comment by juancarlospaco** [comment]
No `check_exception` is imaginary as I said is pseudocode, is something up to the user to implement, is like fake example: https://en.wikipedia.org/wiki/Pseudocode

**Comment by Qwerty-Space** [comment]
Okay.

So can you confirm that it's a bug that nimpy.ProtocolError etc. can't be caught in python?
