### ISSUE TITLE
User Agents

### ISSUE THREAD

**Issue by infosisio** [juancarlospaco/faster-than-requests#5]
How can we use user agents in order to get the contents of a page that otherwise forbids it?

**Comment by juancarlospaco** [comment]
Currently is hardcoded as empty string for performance reasons.
I didnt think that User Agent is a reliable Authentication method whatsoever.
:thinking:

**Comment by infosisio** [comment]
@juancarlospaco With requests, I can simply do for instance:    
```
page = requests.get("https://www.google.com/search?q={}".format(search))
```
With your library, that kind of request gets forbidden and it's not stated anywhere how to overcome it.

Can you provide an example?

**Comment by juancarlospaco** [comment]
```python
>>> import faster_than_requests                                                     
>>> search = "potato"
>>> faster_than_requests.get2str("https://www.google.com/search?q={}".format(search)) 

b'<!doctype html><html itemscope="" itemtype="http://schema.org/SearchResultsPage" lang="es-419"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"> ...

```

**Comment by infosisio** [comment]
@juancarlospaco It doesn't work.
```
nimpy.HttpRequestError: Unexpected error encountered: 400 Bad Request
```

**Comment by infosisio** [comment]
@juancarlospaco I realized what was going on. I wasn't converting the spaces to %. But now there's another error:

```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by juancarlospaco** [comment]
If you dont paste the complete code is impossible to know.
Read the documentation and examples tho...
:woman_shrugging:

**Comment by infosisio** [comment]
@juancarlospaco There's a context incompatibility with nimpy that you should look into.
