### ISSUE TITLE
Build error on openSUSE i586: Nim_and_C_compiler_disagree_on_target_architecture

### ISSUE THREAD

**Issue by jayvdb** [juancarlospaco/faster-than-requests#50]
```console
[   77s] gcc -pthread -DNDEBUG -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fPIC -I. -I/usr/include/python3.7m -c stdlib_parsexml.nim.c -o build/temp.linux-i686-3.7/stdlib_parsexml.nim.o -flto -ffast-math -march=native -mtune=native -O3 -fno-ident -fsingle-precision-constant
[   77s] In file included from stdlib_parsexml.nim.c:6:
[   77s] nimbase.h:457:13: error: size of array ‘Nim_and_C_compiler_disagree_on_target_architecture’ is negative
[   77s]   457 | typedef int Nim_and_C_compiler_disagree_on_target_architecture[sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof(NI)*8 ? 1 : -1];
[   77s]       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
c.f. https://build.opensuse.org/package/live_build_log/home:jayvdb:py-new/python-faster-than-requests/openSUSE_Tumbleweed/i586

**Comment by juancarlospaco** [comment]
Everything should be 64 bits, hardware, os, nim, python, etc.

You can try compile for 32bit, 
But is not supported, int and float are too small, and had to be software emulated, etc.

**Comment by jayvdb** [comment]
I did try compiling for 32bit - that is the result of a normal .spec file https://build.opensuse.org/package/view_file/home:jayvdb:py-new/python-faster-than-requests/python-faster-than-requests.spec?expand=1

Is there anything special I need to do for 32 bit?

The speed benefits are not needed on 32 bit - the compatibility is needed.

**Comment by juancarlospaco** [comment]
Compile from source.
Like the github actions do.
See the github action named Python.

**Comment by jayvdb** [comment]
I am compiling from the sdist on PyPI, v0.9.6

But I will take a look at the build process here to see if it is different.
