### ISSUE TITLE
Installation on Raspberry Pi 3 fail

### ISSUE THREAD

**Issue by MaksymD** [juancarlospaco/faster-than-requests#52]
Collecting faster_than_requests
  Using cached https://files.pythonhosted.org/packages/71/dd/b2160ca61114a35238bf9d5f5ccb88ca759b6d2f9246e6e13f4d263c270d/faster_than_requests-0.1.zip
Building wheels for collected packages: faster-than-requests
  Running setup.py bdist_wheel for faster-than-requests: started
  Running setup.py bdist_wheel for faster-than-requests: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dh6zluw0/faster-than-requests/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp06p98ngspip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'faster_than_requests' extension
  creating build
  creating build/temp.linux-armv7l-3.5
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/include/python3.5m -c stdlib_asyncstreams.c -o build/temp.linux-armv7l-3.5/stdlib_asyncstreams.o -flto -ffast-math -march=native -O3
  In file included from stdlib_asyncstreams.c:7:0:
  nimbase.h:490:13: error: size of array ‘Nim_and_C_compiler_disagree_on_target_architecture’ is negative
   typedef int Nim_and_C_compiler_disagree_on_target_architecture[sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof(NI)*8 ? 1 : -1];
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  stdlib_asyncstreams.c: In function ‘stdlib_asyncstreamsInit000’:
  stdlib_asyncstreams.c:23:9: warning: variable ‘FR_’ set but not used [-Wunused-but-set-variable]
    TFrame FR_; FR_.len = 0;
           ^~~
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  
  ----------------------------------------
  Running setup.py clean for faster-than-requests
Failed to build faster-than-requests
Installing collected packages: faster-than-requests
  Running setup.py install for faster-than-requests: started
    Running setup.py install for faster-than-requests: finished with status 'error'
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dh6zluw0/faster-than-requests/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ead6lbpx-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'faster_than_requests' extension
    creating build
    creating build/temp.linux-armv7l-3.5
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-6waWnr/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/usr/include/python3.5m -c stdlib_asyncstreams.c -o build/temp.linux-armv7l-3.5/stdlib_asyncstreams.o -flto -ffast-math -march=native -O3
    In file included from stdlib_asyncstreams.c:7:0:
    nimbase.h:490:13: error: size of array ‘Nim_and_C_compiler_disagree_on_target_architecture’ is negative
     typedef int Nim_and_C_compiler_disagree_on_target_architecture[sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof(NI)*8 ? 1 : -1];
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    stdlib_asyncstreams.c: In function ‘stdlib_asyncstreamsInit000’:
    stdlib_asyncstreams.c:23:9: warning: variable ‘FR_’ set but not used [-Wunused-but-set-variable]
      TFrame FR_; FR_.len = 0;
             ^~~
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------****

**Comment by juancarlospaco** [comment]
Git clone and compile from source.
See GitHub Actions and readme to see how it is done.
