### ISSUE TITLE
Rewrite curl to requests

### ISSUE THREAD

**Issue by xxxpsyduck** [juancarlospaco/faster-than-requests#54]
I have a curl command like this: 
`curl -X POST http://127.0.0.1:8080/predictions/ -T image.jpg`
How do I rewrite it using faster-than-request?

**Comment by xxxpsyduck** [comment]
In addition, the document should be more clear about sending data through post request

**Comment by juancarlospaco** [comment]
Example exclusively for you: 
https://github.com/juancarlospaco/faster-than-requests/blob/master/examples/post_file.py

**Comment by xxxpsyduck** [comment]
@juancarlospaco Thanks so much
