### ISSUE TITLE
Issue using http_header with requests()

### ISSUE THREAD

**Issue by K3nn3th2** [juancarlospaco/faster-than-requests#55]
hey there,

as stated, i'm having trouble trying to use requests() with http_headers.
i'm using the following header as a test:

```
[("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3"),
    ("Accept-Encoding", "gzip, deflate, br"), ("Accept-Language", "en-US,en;q=0.9"), 
("User-Agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36")]
```

but i get the following error:

`Error: unhandled exception: Cannot convert python object to seq[tuple[key: string, val: string]] [Exception]`

The documentation states a list of tuples is needed, or do i misunderstand?
i dont understand whats wrong with the stated header.

can you clarify?

thanks!

**Comment by K3nn3th2** [comment]
after looking into the unit test file and into the source code, it turns out the documentation states a different order of arguments than in the sources. shifting my parameters to the appropriate positions and adding http_headers= in front of the passed header fixed the problem.

**Comment by juancarlospaco** [comment]
Yes.
