### ISSUE TITLE
Error with pip  faster_than_requests in Visual Studio

### ISSUE THREAD

**Issue by staebchen0** [juancarlospaco/faster-than-requests#59]
hi,
 i tried pip  faster_than_requests
to install and received following errors:

I unzipped the zip file in User / Anja

> ----- "pip faster_than_requests" wird installiert -----
> Requirement already up-to-date: pip in c:\python\python37\lib\site-packages (20.0.2)
> Collecting faster_than_requests
>   Using cached faster_than_requests-0.9.8.zip (435 kB)
> Building wheels for collected packages: faster-than-requests
>   Building wheel for faster-than-requests (setup.py): started
>   Building wheel for faster-than-requests (setup.py): finished with status 'error'
>   Running setup.py clean for faster-than-requests
>   ERROR: Command errored out with exit status 1:
>    command: 'C:\Python\Python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\anja\\AppData\\Local\\Temp\\pip-install-xqex7ji5\\faster-than-requests\\setup.py'"'"'; __file__='"'"'C:\\Users\\anja\\AppData\\Local\\Temp\\pip-install-xqex7ji5\\faster-than-requests\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\anja\AppData\Local\Temp\pip-wheel-j0mx2asf'
>        cwd: C:\Users\anja\AppData\Local\Temp\pip-install-xqex7ji5\faster-than-requests\
>   Complete output (18 lines):
>   running bdist_wheel
>   running build
>   running build_ext
>   building 'faster_than_requests' extension
>   creating build
>   creating build\temp.win-amd64-3.7
>   creating build\temp.win-amd64-3.7\Release
>   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -IC:\Python\Python37\include -IC:\Python\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" /Tc@m..@s..@s..@s.nimble@spkgs@snimpy-0.1.0@snimpy.nim.c /Fobuild\temp.win-amd64-3.7\Release\@m..@s..@s..@s.nimble@spkgs@snimpy-0.1.0@snimpy.nim.obj -flto -ffast-math -march=native -mtune=native -O3 -fno-ident -fsingle-precision-constant
>   cl : Befehlszeile warning D9002 : Unbekannte Option "-flto" wird ignoriert.
>   cl : Befehlszeile warning D9002 : Unbekannte Option "-ffast-math" wird ignoriert.
>   cl : Befehlszeile warning D9002 : Unbekannte Option "-march=native" wird ignoriert.
>   cl : Befehlszeile warning D9002 : Unbekannte Option "-mtune=native" wird ignoriert.
>   cl : Befehlszeile warning D9002 : Unbekannte Option "-O3" wird ignoriert.
>   cl : Befehlszeile warning D9002 : Unbekannte Option "-fno-ident" wird ignoriert.
>   cl : Befehlszeile warning D9002 : Unbekannte Option "-fsingle-precision-constant" wird ignoriert.
>   @m..@s..@s..@s.nimble@spkgs@snimpy-0.1.0@snimpy.nim.c
>   c:\users\anja\appdata\local\temp\pip-install-xqex7ji5\faster-than-requests\nimbase.h(258): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "stddef.h": No such file or directory
>   error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
>   ----------------------------------------

**Comment by juancarlospaco** [comment]
If PIP fails you can just use the source code, Git clone and Compile, 
the GitHub Actions CI build every commit from zero with very basic commands (curl, etc),
also the Windows section explains how to do it too 
https://github.com/juancarlospaco/faster-than-requests#windows
also a lot of people just use Docker nowadays.
