### ISSUE TITLE
Fail to use pip install on python 3.6

### ISSUE THREAD

**Issue by popeyaho** [juancarlospaco/faster-than-requests#6]
As the title, i got this issue when using pip install, or *.py files resources, I can't see any file on there, hope your help

> running install
    running build
    running build_ext
    building 'faster_than_requests' extension
    creating build
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Ic:\users\duyth\appdata\local\programs\python\python36\include -Ic:\users\duyth\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcstdlib_asyncstreams.c /Fobuild\temp.win-amd64-3.6\Release\stdlib_asyncstreams.obj -flto -ffast-math -march=native -O3
    cl : Command line warning D9002 : ignoring unknown option '-flto'
    cl : Command line warning D9002 : ignoring unknown option '-ffast-math'
    cl : Command line warning D9002 : ignoring unknown option '-march=native'
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    stdlib_asyncstreams.c
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Ic:\users\duyth\appdata\local\programs\python\python36\include -Ic:\users\duyth\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcstdlib_httpcore.c /Fobuild\temp.win-amd64-3.6\Release\stdlib_httpcore.obj -flto -ffast-math -march=native -O3
    cl : Command line warning D9002 : ignoring unknown option '-flto'
    cl : Command line warning D9002 : ignoring unknown option '-ffast-math'
    cl : Command line warning D9002 : ignoring unknown option '-march=native'
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    stdlib_httpcore.c
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Ic:\users\duyth\appdata\local\programs\python\python36\include -Ic:\users\duyth\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcstdlib_os.c /Fobuild\temp.win-amd64-3.6\Release\stdlib_os.obj -flto -ffast-math -march=native -O3
    cl : Command line warning D9002 : ignoring unknown option '-flto'
    cl : Command line warning D9002 : ignoring unknown option '-ffast-math'
    cl : Command line warning D9002 : ignoring unknown option '-march=native'
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    stdlib_os.c
    stdlib_os.c(84): warning C4013: 'S_ISREG' undefined; assuming extern returning int
    stdlib_os.c(101): warning C4013: 'nanosleep' undefined; assuming extern returning int
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Ic:\users\duyth\appdata\local\programs\python\python36\include -Ic:\users\duyth\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcstdlib_strscans.c /Fobuild\temp.win-amd64-3.6\Release\stdlib_strscans.obj -flto -ffast-math -march=native -O3
    cl : Command line warning D9002 : ignoring unknown option '-flto'
    cl : Command line warning D9002 : ignoring unknown option '-ffast-math'
    cl : Command line warning D9002 : ignoring unknown option '-march=native'
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    stdlib_strscans.c
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Ic:\users\duyth\appdata\local\programs\python\python36\include -Ic:\users\duyth\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcstdlib_base64.c /Fobuild\temp.win-amd64-3.6\Release\stdlib_base64.obj -flto -ffast-math -march=native -O3
    cl : Command line warning D9002 : ignoring unknown option '-flto'
    cl : Command line warning D9002 : ignoring unknown option '-ffast-math'
    cl : Command line warning D9002 : ignoring unknown option '-march=native'
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    stdlib_base64.c
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Ic:\users\duyth\appdata\local\programs\python\python36\include -Ic:\users\duyth\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcstdlib_json.c /Fobuild\temp.win-amd64-3.6\Release\stdlib_json.obj -flto -ffast-math -march=native -O3
    cl : Command line warning D9002 : ignoring unknown option '-flto'
    cl : Command line warning D9002 : ignoring unknown option '-ffast-math'
    cl : Command line warning D9002 : ignoring unknown option '-march=native'
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    stdlib_json.c
    stdlib_json.c(231): error C2061: syntax error: identifier '__attribute__'
    stdlib_json.c(231): error C2059: syntax error: ';'
    stdlib_json.c(373): error C2143: syntax error: missing ':' before '...'
    stdlib_json.c(377): error C2065: 'T11_': undeclared identifier
    stdlib_json.c(377): warning C4047: '=': 'int' differs in levels of indirection from 'NimStringDesc *'
    stdlib_json.c(380): error C2065: 'T11_': undeclared identifier
    stdlib_json.c(380): warning C4047: '=': 'int' differs in levels of indirection from 'NimStringDesc *'
    stdlib_json.c(381): error C2065: 'T11_': undeclared identifier
    stdlib_json.c(381): warning C4047: 'function': 'NimStringDesc *' differs in levels of indirection from 'int'
    stdlib_json.c(381): warning C4024: 'appendString': different types for formal and actual parameter 1
    stdlib_json.c(382): error C2065: 'T11_': undeclared identifier
    stdlib_json.c(382): warning C4047: 'function': 'NimStringDesc *' differs in levels of indirection from 'int'
    stdlib_json.c(382): warning C4024: 'appendString': different types for formal and actual parameter 1
    stdlib_json.c(383): error C2065: 'T11_': undeclared identifier
    stdlib_json.c(383): error C2223: left of '->Sup' must point to struct/union
    stdlib_json.c(383): error C2198: 'resizeString': too few arguments for call
    stdlib_json.c(384): error C2065: 'T11_': undeclared identifier
    stdlib_json.c(384): warning C4047: 'function': 'NimStringDesc *' differs in levels of indirection from 'int'
    stdlib_json.c(384): warning C4024: 'appendString': different types for formal and actual parameter 2
    stdlib_json.c(387): error C2143: syntax error: missing ':' before '...'
    stdlib_json.c(391): error C2065: 'T14_': undeclared identifier
    stdlib_json.c(391): warning C4047: '=': 'int' differs in levels of indirection from 'NimStringDesc *'
    stdlib_json.c(394): error C2065: 'T14_': undeclared identifier
    stdlib_json.c(394): warning C4047: '=': 'int' differs in levels of indirection from 'NimStringDesc *'
    stdlib_json.c(395): error C2065: 'T14_': undeclared identifier
    stdlib_json.c(395): warning C4047: 'function': 'NimStringDesc *' differs in levels of indirection from 'int'
    stdlib_json.c(395): warning C4024: 'appendString': different types for formal and actual parameter 1
    stdlib_json.c(396): error C2065: 'T14_': undeclared identifier
    stdlib_json.c(396): warning C4047: 'function': 'NimStringDesc *' differs in levels of indirection from 'int'
    stdlib_json.c(396): warning C4024: 'appendString': different types for formal and actual parameter 1
    stdlib_json.c(397): error C2065: 'T14_': undeclared identifier
    stdlib_json.c(397): error C2223: left of '->Sup' must point to struct/union
    stdlib_json.c(397): error C2198: 'resizeString': too few arguments for call
    stdlib_json.c(398): error C2065: 'T14_': undeclared identifier
    stdlib_json.c(398): warning C4047: 'function': 'NimStringDesc *' differs in levels of indirection from 'int'
    stdlib_json.c(398): warning C4024: 'appendString': different types for formal and actual parameter 2
    stdlib_json.c(387): error C2046: illegal case
    stdlib_json.c(400): error C2043: illegal break
    stdlib_json.c(401): error C2046: illegal case
    stdlib_json.c(406): error C2043: illegal break
    stdlib_json.c(407): error C2047: illegal default
    stdlib_json.c(411): error C2043: illegal break
    stdlib_json.c(416): error C2059: syntax error: '}'
    stdlib_json.c(758): warning C4013: 'raiseParseErr_xOEBzQ9aFzD8i9aTrXTVac4A' undefined; assuming extern returning int
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by popeyaho** [comment]
and window 10 x64, research and following another issue, installed vc++ but still dont work

**Comment by crinny** [comment]
Having same problem on Windows 10 x64 with latest VC++ and Twisted wheels

**Comment by juancarlospaco** [comment]
It does not use wheel.
It needs GCC.
Everything needs to be 64 Bit.
Try with full Cygwin.

**Comment by crinny** [comment]
> 
> 
> It does not use wheel.
> It needs GCC.
> Everything needs to be 64 Bit.
> Try with full Cygwin.

I tried with installing Cygwin x64 and the error is same.

**Comment by juancarlospaco** [comment]
It needs Python 3.7 Stable of 64Bit.

Paste the full error in a code block if it fails with GCC.

**Comment by juancarlospaco** [comment]
Fixed on master.
