### ISSUE TITLE
question - import faster_than_requests as requests in python Script

### ISSUE THREAD

**Issue by staebchen0** [juancarlospaco/faster-than-requests#60]
Hi, I have installed it now, thank you for your hint:

> Hint: operation successful (98442 lines compiled; 28,373 sec total; 137,738MiB peakmem; Dangerous Release Build) [SuccessX]
> 
> anja @ PC-Anja MINGW64 ~ / faster-than-requests-master / src
> $ ls
> faster_than_requests.dll * faster_than_requests.nim faster_than_requests.nim.cfg faster_than_requests.pyd *
> 

I have still one question:
How can I import it into Visual Studio?

> pip install faster_than_requests

does not work and to import it in my Script

> import faster_than_requests as requests

I have to embed it in Visual Studio. Sorry for the many questions, but I am brand new to the field.

**Comment by juancarlospaco** [comment]
Just put the `faster_than_requests.pyd` in the same folder as your `*.py` file.

**Comment by staebchen0** [comment]
Thank you very much :-)
