### ISSUE TITLE
Test - Faster and urllib 

### ISSUE THREAD

**Issue by staebchen0** [juancarlospaco/faster-than-requests#61]
Hi, everything is running now and I have made a test compared to urlib ....

Result:

> Faster than requests:
> [INFO] Start with Lock..Fri Apr 3 14:23:43 2020
> [INFO] End with Locked Fri Fri 3 2:24:07 PM 2020
> Time:
> 0: 00: 23.297731
> 
> [INFO] Start with. Start unlocking Fri Fri Apr 3 14:24:07 2020
> [INFO] End with Unlocked..Fri Apr 3 14:24:33 2020
> Time:
>  0: 00: 26.024629
> 
> urllib:
> 
> [INFO] Start with Lock..Fri Apr 3 14:24:33 2020
> [INFO] End with blocked..Fri Apr 3 14:24:43 2020
> Time:
> 0: 00: 10.246623
> 
> [INFO] Start with Unlock start..Fri Apr 3 14:24:43 2020
> [INFO] End with Unlocked Fri Fri 3 2:24:50 2020
> Time:
> 0: 00: 07.453506
> 
> Thread 0x1 ended with code 0 (0x0).
> The program "python.exe" was terminated with code 0 (0x0).

Script:
```
import faster_than_requests as requests
import time
import datetime
import urllib.request


print ("Faster")
print("[INFO] Start with Sperre starten.."+ datetime.datetime.now().ctime()+'\n')
start = datetime.datetime.now()
requests.get('http://localhost/sureflap-master/LockOutsite.php')
end = datetime.datetime.now()
print("[INFO] Ende with Gesperrt.."+ datetime.datetime.now().ctime()+'\n')
time_taken = end - start
print('Time: ',time_taken) 


print("[INFO] Start with . Entsperren starten.."+ datetime.datetime.now().ctime()+'\n')
start = datetime.datetime.now()
requests.get('http://localhost/sureflap-master/UnLock.php')
end = datetime.datetime.now()
print("[INFO] Ende with  Entsperrt.."+ datetime.datetime.now().ctime()+'\n')
time_taken = end - start
print('Time: ',time_taken) 

print ("UrlLib")
print("[INFO] Start with Sperre starten.."+ datetime.datetime.now().ctime()+'\n')
start = datetime.datetime.now()
webUrl  = urllib.request.urlopen('http://localhost/sureflap-master/LockOutsite.php')
end = datetime.datetime.now()
print("[INFO] Ende with Gesperrt.."+ datetime.datetime.now().ctime()+'\n')
time_taken = end - start
print('Time: ',time_taken) 

print("[INFO] Start with  Entsperren starten.."+ datetime.datetime.now().ctime()+'\n')
start = datetime.datetime.now()
webUrl  = urllib.request.urlopen('http://localhost/sureflap-master/UnLock.php')
end = datetime.datetime.now()
print("[INFO] Ende with  Entsperrt.."+ datetime.datetime.now().ctime()+'\n')
time_taken = end - start
print('Time: ',time_taken) 
```
Am I doing something wrong when calling?
Faster .... is always slower than urllib

**Comment by juancarlospaco** [comment]
Use `faster_than_requests.get2str()`.

**Comment by staebchen0** [comment]
Thank you for your prompt reply :-)
is faster, but not as fast as urllib ....
is there another way?

Result:

> Faster
> [INFO] Start with Lock..Fri Apr 3 17:39:51 2020
> [INFO] End with Locked Fri Fri 3 3:40:08 PM 2020
> Time:
> 0: 00: 16.997461
> 
> [INFO] Start with. Start unlocking Fri Fri Apr 3 5:40:09 pm 2020
> [INFO] End with Unlocked..Fri Apr 3 17:40:14 2020
> Time:
> 0: 00: 04.983759
> 
> UrlLib
> [INFO] Start with Lock..Fri Apr 3 17:40:14 2020
> [INFO] End with Locked Fri Fri 3 3:40:23 PM 2020
> Time:
> 0: 00: 09.061766
> 
> [INFO] Start with Unlock start..Fri Apr 3 17:40:23 2020
> [INFO] End with Unlocked Fri Fri 3 3:40:27 2020
> Time:
> 0: 00: 04.669607

I sometimes reversed the order, but that wasn't the problem.

Result:

> UrlLib
> [INFO] Start with Sperre starten..Fri Apr  3 17:43:00 2020
> [INFO] Ende with Gesperrt..Fri Apr  3 17:43:07 2020
> Time: 
> 0:00:07.263817
> 
> [INFO] Start with  Entsperren starten..Fri Apr  3 17:43:07 2020
> [INFO] Ende with  Entsperrt..Fri Apr  3 17:43:20 2020
> Time: 
> 0:00:12.822121
> 
> Faster
> [INFO] Start with Sperre starten..Fri Apr  3 17:43:20 2020
> [INFO] Ende with Gesperrt..Fri Apr  3 17:43:35 2020
> Time: 
> 0:00:15.164177
> 
> [INFO] Start with . Entsperren starten..Fri Apr  3 17:43:35 2020
> [INFO] Ende with  Entsperrt..Fri Apr  3 17:43:44 2020
> Time: 
> 0:00:08.662750
>

**Comment by juancarlospaco** [comment]
```console
$ python3 prueba.py

Faster
[INFO] Ende with Gesperrt..Fri Apr  3 13:19:41 2020

Time:  0:00:00.000177
[INFO] Ende with  Entsperrt..Fri Apr  3 13:19:41 2020

Time:  0:00:00.000019

UrlLib
[INFO] Ende with Gesperrt..Fri Apr  3 13:19:41 2020

Time:  0:00:00.009127
[INFO] Ende with  Entsperrt..Fri Apr  3 13:19:41 2020

Time:  0:00:00.000587

```

No idea :man_shrugging: 

- Is everything on your system 64Bit?, Python 64Bit?, OS 64Bit?.
- AntiVirus?, Python3.8 ?.
- You compiled adding `-d:danger -d:release` to the compile command?.

**Comment by staebchen0** [comment]
I checked it

> Interactive Python 3.7 (64-bit) window [PTVS 15.9.18254.1-15.0]
> Type "$ help" to display a list of commands.
> >>> import platform
> >>> platform.architecture ()
> ('64bit', 'WindowsPE')
> >>>

AntiVirus = Avira 

I did not carry out the order.
am i doing this?

`C: \ Users \ anja \ faster-than-requests-master> -d: danger -d: release`

**Comment by juancarlospaco** [comment]
You have Python `3.7`, the latest is `3.8`.
Whatever the command you used to compile, add ` -d: danger -d: release ` to it somewhere.
You have GCC installed?, compile with GCC if you can, is better.

**Comment by staebchen0** [comment]
okay thanks! I will try it
