### ISSUE TITLE
Error After compiling

### ISSUE THREAD

**Issue by enzod3** [juancarlospaco/faster-than-requests#62]
I compile the repository and put faster_than_requests in the same directory as my file but when i run my program I get "DLL load failed while importing faster_than_requests: %1 is not a valid Win32 application."

**Comment by juancarlospaco** [comment]
Yeah some people had problems with IDE.
If you can, just try it on Docker, lot of people are using Docker nowadays.
If you have the full terminal output from compilation and forward, feel free to post it, maybe I can deduce something.
:man_shrugging:

**Comment by enzod3** [comment]
I was able to fix this, I am now having another issue I’m getting a dll error after compiling to and exe with pyinstaller?

**Comment by enzod3** [comment]
to an exe**

**Comment by juancarlospaco** [comment]
Good you fixed the problem. :+1: 

I dont know if I can help much with PyInstaller, I have no idea of that code, not my bug,
try making an issue there for that bug probably is the more direct and faster way basically,
sorry but I dont use it, I just use Nim that gives you `.exe`, `.dll`, `.pyd` binaries without dependencies.

Good luck!. :slightly_smiling_face:

**Comment by iLoooordFx** [comment]
how do you fixed? im having the same issue
