### ISSUE TITLE
Can't install getting a ValueError on strutils

### ISSUE THREAD

**Issue by sneakykiwi** [juancarlospaco/faster-than-requests#64]
- **C:\faster-than-requests\src>nim c -d:ssl -d:release --app:lib --out:faster_than_requests.pyd faster_than_requests.nim
Hint: used config file 'C:\Users\sn3ak\AppData\Local\Temp\Rar$EXa19616.28540\nim-1.2.0\config\nim.cfg' [Conf]
Hint: used config file 'C:\faster-than-requests\src\faster_than_requests.nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: faster_than_requests [Processing]
Hint: httpclient [Processing]
Hint: net [Processing]
Hint: nativesockets [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: pathnorm [Processing]
Hint: osseps [Processing]
Hint: winlean [Processing]
Hint: dynlib [Processing]
Hint: times [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: time_t [Processing]
Hint: sets [Processing]
Hint: hashes [Processing]
Hint: monotimes [Processing]
Hint: ssl_certs [Processing]
Hint: ospaths [Processing]
Hint: openssl [Processing]
Hint: uri [Processing]
Hint: base64 [Processing]
Hint: mimetypes [Processing]
Hint: strtabs [Processing]
Hint: streams [Processing]
Hint: random [Processing]
Hint: httpcore [Processing]
Hint: tables [Processing]
Hint: asyncnet [Processing]
Hint: asyncdispatch [Processing]
Hint: heapqueue [Processing]
Hint: asyncstreams [Processing]
Hint: asyncfutures [Processing]
Hint: deques [Processing]
Hint: cstrutils [Processing]
Hint: asyncfile [Processing]
Hint: json [Processing]
Hint: lexbase [Processing]
Hint: parsejson [Processing]
Hint: threadpool [Processing]
Hint: cpuinfo [Processing]
Hint: cpuload [Processing]
Hint: htmlparser [Processing]
Hint: parsexml [Processing]
Hint: xmltree [Processing]
Hint: sequtils [Processing]
Hint: db_sqlite [Processing]
Hint: sqlite3 [Processing]
Hint: db_common [Processing]
Hint: re [Processing]
Hint: pcre [Processing]
Hint: rtarrays [Processing]
Hint: nimpy [Processing]
Hint: complex [Processing]
Hint: py_types [Processing]
Hint: py_utils [Processing]
Hint: py_lib [Processing]
strutils.nim(2624)       invalidFormatString
Error: unhandled exception: invalid format string [ValueError]**

**Describe the bug**
 It should install it normally

**To Reproduce**
1. Download and navigate to the source folder of the module
2. Try installing it
3. Get that error

**
![image](https://user-images.githubusercontent.com/59621197/79029262-49b5fe80-7b9c-11ea-8981-89e12464d71a.png)
**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81

I am doing this in order to compile it as `pip3 install faster-than-requests` raises the following error:

`Command "C:\Users\sn3ak\PycharmProjects\target-monitor-part\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\sn3ak\\AppData\\Local\\Temp\\pip-install-wxf9kku4\\faster-than-requests\\setup.py';f=getattr(tokenize, 'open', open)(__file__
);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\sn3ak\AppData\Local\Temp\pip-record-ab5ymilc\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\sn3ak\PycharmPr
ojects\target-monitor-part\venv\include\site\python3.7\faster-than-requests" failed with error code 1 in C:\Users\sn3ak\AppData\Local\Temp\pip-install-wxf9kku4\faster-than-requests\
`

**Comment by juancarlospaco** [comment]
Try again without `-d:release`.
if that fails delete the file ` 'C:\faster-than-requests\src\faster_than_requests.nim.cfg'` and try again.

is everything 64Bit?, Windows 64Bit?, Python 64Bit?.

**Comment by MrVenom111** [comment]
@juancarlospaco i m getting the same error BTW everything is 64-bit

**Comment by MrVenom111** [comment]
![github](https://user-images.githubusercontent.com/59961092/80684291-dc342880-8ade-11ea-8d2d-8f7433a09a30.PNG)

**Comment by juancarlospaco** [comment]
It is **not** `*.dll`.
It must be `*.pyd`.

Compile with `--nimcache:.`
