### ISSUE TITLE
Fails to install with pip

### ISSUE THREAD

**Issue by Scylla2020** [juancarlospaco/faster-than-requests#65]
I'm trying to install in Windows 10 64bit and am using Python 3.6.5 64 bit and getting an error:
```
@m..@s..@s..@s..@s.nimble@spkgs@snimpy-0.1.0@snimpy.nim.c(10): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

**Comment by juancarlospaco** [comment]
Git clone and Compile.

The GitHub Actions CI build every commit from zero with very basic commands (curl, etc),
also the Windows section explains how to do it too https://github.com/juancarlospaco/faster-than-requests#windows
also a lot of people just use Docker nowadays.
