### ISSUE TITLE
Show progression for download()

### ISSUE THREAD

**Issue by RGFRv2** [juancarlospaco/faster-than-requests#66]
Hello, I exported `export REQUESTS_DEBUG="true"` then I ran a script to download a file with `requests.download()` but I don't get any information when downloading. 

Does anyone have a solution for this?

**Comment by juancarlospaco** [comment]
`verbose = True` on `download3()`.
Not all of them has it tho.

**Comment by RGFRv2** [comment]
I'dont have download3
```python
Python 3.6.4 (default, Jun 19 2019, 19:59:44) [GCC 4.9.2] on linux
>>> import faster_than_requests
>>> faster_than_requests.download3()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'faster_than_requests' has no attribute 'download3'
```
I installed it via pip with `pip install faster-than-requests`.
```bash
~/ pip3 list | grep faster-than-requests
faster-than-requests 0.9.6
```

**Comment by juancarlospaco** [comment]
Thats correct, `0.9.8` is the latest, use that one.

**Comment by RGFRv2** [comment]
How can I update it ?
```bash
~/ sudo python3.6 -m pip install faster_than_requests --upgrade
Requirement already up-to-date: faster_than_requests in /usr/local/lib/python3.6/site-packages (0.9.6)
```

**Comment by juancarlospaco** [comment]
- uninstall
- install again

Use Python `3.8` 64Bit if possible.

**Comment by RGFRv2** [comment]
I can't go to 3.8, there's no other way to install it?
I uninstalled and reinstalled the package, I'm still in `0.9.6`.

**Comment by juancarlospaco** [comment]
Git clone and compile.

The GitHub Actions CI build every commit from zero with very basic commands (curl, etc),
also the Windows section explains how to do it too https://github.com/juancarlospaco/faster-than-requests#windows
also a lot of people just use Docker nowadays.

Sorry I can not fix what PIP does.

**Comment by RGFRv2** [comment]
Thanks for the information.
I'm closing the issue.

**Comment by juancarlospaco** [comment]
Cool, is really easy to get it compiled, sometimes is just faster than troubleshoot PIP, etc.
:+1:
