### ISSUE TITLE
Case Sensitive Headers

### ISSUE THREAD

**Issue by selestaingegneria** [juancarlospaco/faster-than-requests#67]
Hi,
i set  HTTP 's headers and make a POST with this code:

> headers = [ ("Custom", "Dummy") ]
> requests.requests(url, "POST", data, headers)

When i run my script, i get this HTTP header:

> POST /files HTTP/1.1
> Host: 192.168.1.2
> Connection: Keep-Alive
> custom: dummy
> content-length: 465
> user-agent: Nim httpclient/1.0.6
> content-type: multipart/form-data;

where my custom header is in lower case and not with first character capitalized.

It is possibile to fix this?

**Comment by juancarlospaco** [comment]
Nope.

> Each header field consists of a name followed by a colon (":") and the field value. **Fields are case-insensitive.**

https://tools.ietf.org/html/rfc7230#section-3.2

RFC explicitly states that field headers must be treated as case-insensitive.
