### ISSUE TITLE
Erorr on install with nim :invocation of external compiler program failed

### ISSUE THREAD

**Issue by deli0870** [juancarlospaco/faster-than-requests#68]
hi i tried to install with nim got this error and still confuse how to solve this
:
c:\faster-than-requests-master\src>nim c -d:ssl -d:release --app:lib --out:faster_than_requests.pyd faster_than_requests.nim
Hint: used config file 'C:\Users\sijam\.choosenim\toolchains\nim-1.2.0\config\nim.cfg' [Conf]
Hint: used config file 'c:\faster-than-requests-master\src\faster_than_requests.nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: faster_than_requests [Processing]
Hint: httpclient [Processing]
Hint: net [Processing]
Hint: nativesockets [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: pathnorm [Processing]
Hint: osseps [Processing]
Hint: winlean [Processing]
Hint: dynlib [Processing]
Hint: times [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: time_t [Processing]
Hint: sets [Processing]
Hint: hashes [Processing]
Hint: monotimes [Processing]
Hint: ssl_certs [Processing]
Hint: ospaths [Processing]
Hint: openssl [Processing]
Hint: uri [Processing]
Hint: base64 [Processing]
Hint: mimetypes [Processing]
Hint: strtabs [Processing]
Hint: streams [Processing]
Hint: random [Processing]
Hint: httpcore [Processing]
Hint: tables [Processing]
Hint: asyncnet [Processing]
Hint: asyncdispatch [Processing]
Hint: heapqueue [Processing]
Hint: asyncstreams [Processing]
Hint: asyncfutures [Processing]
Hint: deques [Processing]
Hint: cstrutils [Processing]
Hint: asyncfile [Processing]
Hint: json [Processing]
Hint: lexbase [Processing]
Hint: parsejson [Processing]
Hint: threadpool [Processing]
Hint: cpuinfo [Processing]
Hint: cpuload [Processing]
Hint: htmlparser [Processing]
Hint: parsexml [Processing]
Hint: xmltree [Processing]
Hint: sequtils [Processing]
Hint: db_sqlite [Processing]
Hint: sqlite3 [Processing]
Hint: db_common [Processing]
Hint: re [Processing]
Hint: pcre [Processing]
Hint: rtarrays [Processing]
Hint: nimpy [Processing]
Hint: complex [Processing]
Hint: py_types [Processing]
Hint: py_utils [Processing]
Hint: py_lib [Processing]
CC: stdlib_assertions.nim
Error: invocation of external compiler program failed. The system cannot find the file specified.
Additional info: "Requested command not found: \'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -flto -ffast-math -march=native -mtune=native -fsingle-precision-constant -O3 -fno-strict-aliasing -fno-ident  -IC:\\Users\\sijam\\.choosenim\\toolchains\\nim-1.2.0\\lib -Ic:\\faster-than-requests-master\\src -o C:\\Users\\sijam\\nimcache\\faster_than_requests_r\\stdlib_assertions.nim.c.o C:\\Users\\sijam\\nimcache\\faster_than_requests_r\\stdlib_assertions.nim.c\'. OS error:" 2

can you please help anything wrong with the process?
gcc wass installed

**Comment by juancarlospaco** [comment]
Git clone and Compile.

The GitHub Actions CI build every commit from zero with very basic commands (curl, etc),
also the Windows section explains how to do it too https://github.com/juancarlospaco/faster-than-requests#windows
also a lot of people just use Docker nowadays.

**Comment by deli0870** [comment]
hi juan,
already restart and add as you sugested but still error on the installation process all is i can assure you running on 64,  the gcc is using the wingw64 from nim

c:\faster-than-requests-master\src>nim c -d:ssl -d:danger --app:lib --nimcache:. --out:faster_than_requests.pyd faster_than_requests.nim
Hint: used config file 'C:\Users\sijam\.choosenim\toolchains\nim-1.2.0\config\nim.cfg' [Conf]
Hint: used config file 'c:\faster-than-requests-master\src\faster_than_requests.nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: faster_than_requests [Processing]
Hint: httpclient [Processing]
Hint: net [Processing]
Hint: nativesockets [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: pathnorm [Processing]
Hint: osseps [Processing]
Hint: winlean [Processing]
Hint: dynlib [Processing]
Hint: times [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: time_t [Processing]
Hint: sets [Processing]
Hint: hashes [Processing]
Hint: monotimes [Processing]
Hint: ssl_certs [Processing]
Hint: ospaths [Processing]
Hint: openssl [Processing]
Hint: uri [Processing]
Hint: base64 [Processing]
Hint: mimetypes [Processing]
Hint: strtabs [Processing]
Hint: streams [Processing]
Hint: random [Processing]
Hint: httpcore [Processing]
Hint: tables [Processing]
Hint: asyncnet [Processing]
Hint: asyncdispatch [Processing]
Hint: heapqueue [Processing]
Hint: asyncstreams [Processing]
Hint: asyncfutures [Processing]
Hint: deques [Processing]
Hint: cstrutils [Processing]
Hint: asyncfile [Processing]
Hint: json [Processing]
Hint: lexbase [Processing]
Hint: parsejson [Processing]
Hint: threadpool [Processing]
Hint: cpuinfo [Processing]
Hint: cpuload [Processing]
Hint: htmlparser [Processing]
Hint: parsexml [Processing]
Hint: xmltree [Processing]
Hint: sequtils [Processing]
Hint: db_sqlite [Processing]
Hint: sqlite3 [Processing]
Hint: db_common [Processing]
Hint: re [Processing]
Hint: pcre [Processing]
Hint: rtarrays [Processing]
Hint: nimpy [Processing]
Hint: complex [Processing]
Hint: py_types [Processing]
Hint: py_utils [Processing]
Hint: py_lib [Processing]
CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
CC: stdlib_locks.nim
CC: stdlib_sharedlist.nim
In file included from c:\faster-than-requests-master\src\stdlib_dollars.nim.c:9:0:
C:\Users\sijam\.choosenim\toolchains\nim-1.2.0\lib/nimbase.h:522:13: error: size of array 'Nim_and_C_compiler_disagree_on_target_architecture' is negative
 typedef int Nim_and_C_compiler_disagree_on_target_architecture[sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof(NI)*8 ? 1 : -1];
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from c:\faster-than-requests-master\src\stdlib_locks.nim.c:9:0:
C:\Users\sijam\.choosenim\toolchains\nim-1.2.0\lib/nimbase.h:522:13: error: size of array 'Nim_and_C_compiler_disagree_on_target_architecture' is negative
 typedef int Nim_and_C_compiler_disagree_on_target_architecture[sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof(NI)*8 ? 1 : -1];
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from c:\faster-than-requests-master\src\stdlib_assertions.nim.c:9:0:
C:\Users\sijam\.choosenim\toolchains\nim-1.2.0\lib/nimbase.h:522:13: error: size of array 'Nim_and_C_compiler_disagree_on_target_architecture' is negative
 typedef int Nim_and_C_compiler_disagree_on_target_architecture[sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof(NI)*8 ? 1 : -1];
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from c:\faster-than-requests-master\src\stdlib_sharedlist.nim.c:9:0:
C:\Users\sijam\.choosenim\toolchains\nim-1.2.0\lib/nimbase.h:522:13: error: size of array 'Nim_and_C_compiler_disagree_on_target_architecture' is negative
 typedef int Nim_and_C_compiler_disagree_on_target_architecture[sizeof(NI) == sizeof(void*) && NIM_INTBITS == sizeof(NI)*8 ? 1 : -1];
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: execution of an external compiler program 'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -flto -ffast-math -march=native -mtune=native -fsingle-precision-constant -O3 -fno-strict-aliasing -fno-ident  -IC:\Users\sijam\.choosenim\toolchains\nim-1.2.0\lib -Ic:\faster-than-requests-master\src -o c:\faster-than-requests-master\src\stdlib_assertions.nim.c.o c:\faster-than-requests-master\src\stdlib_assertions.nim.c' failed with exit code: 1

**Comment by juancarlospaco** [comment]
Something is not 64 Bit, the OS, the Python, the GCC, etc etc.
