### ISSUE TITLE
 ProtocolError: Unexpected error encountered: invalid http version

### ISSUE THREAD

**Issue by rajan-blackboxes** [juancarlospaco/faster-than-requests#69]
**`ProtocolError: Unexpected error encountered: invalid http version, 0x7fc1b088f358"!\203\219\01\164s\181\252\147\185\174E),\252T\133\172r\158\196\140\228uZf\4J!|\134\171\175\216\202\19c\185\147\"\154e5\30\155J\236\143\1811\8\221'\133\139\194lZ\6\238\170*\214?\156\"\211b\170\145\175%\25\156\218\128\197Gj\156\190\200\187\166\\\164\198r\143R\243\203\235q\7\174\218\198L\242\155\233\140\1692\131I\221\137&b\234#\11&u\176\162\"\222\167\249\165\237\191-\150\15J\236\224=N\141\237\252\170\22\30\187\251\33\193z\192\157\204\0G\230\195\160M\1289\5\156e@\213\30hsx\215St\156|k/\163\1918\175H\167\253\23\199O\159\129$\199\232bW\142\215;t-%\135\176~b\238\238\21\212,\224\1389z\250\166l\"@l\237\145\216}|x"`**

** bug**
I was scraping images from a http website. Previously it was working, suddenly when run again, it is giving that kind of error. When using code for first run gives this kind of error
**`IOError: Unexpected error encountered: Unable to open file`** and after gives error as in title. Links not worked for any sites

**Expected behavior**
Previously , It was running.
 
**Desktop (please complete the following information):**
 - Colab
 - Chrome

**Additional context**
my code is 
```
import os
import faster_than_requests as requests
from tqdm.notebook import tqdm 


def download(imgList):
  with tqdm(total=len(cleaned)) as pbar:
    for img in imgList:
      filename = os.path.basename(os.path.realpath(img))
      requests.download(img, '/content/drive/My Drive/Projects/Face generation project/images/' + '{}'.format(filename))
      pbar.update(1)

download(['https://www.cleverfiles.com/howto/wp-content/uploads/2018/03/minion.jpg']) # any img link
```

**Comment by juancarlospaco** [comment]
Use a full path without white spaces.

**Comment by rajan-blackboxes** [comment]
May be it was .  I tried to change the directory to download location and tried to download giving raw image filename and It worked now. 
Thanks @juancarlospaco
