### ISSUE TITLE
4xx Client Errors do not let read API response

### ISSUE THREAD

**Issue by PetyaT** [juancarlospaco/faster-than-requests#70]
I was trying out this beautiful library and came across an annoying thing. I'm trying to get some info via API on a site, sometimes my request returns **404 ERROR** (Not Found) and **401 ERROR** (Unauthorized). 

The site I'm willing to reach also gives a description of the error in JSON format. Regular requests library lets me get this description, whereas faster_than_requests returns an error, and there is no way I can get that JSON.

Is there a way to disable raising exceptions when the site I'm trying to request returns 404 and 401 errors? Thanks!

**Comment by juancarlospaco** [comment]
Wrap it in a try...except block?.

**Comment by PetyaT** [comment]
If you wrap it in a try-except block, you only get the name of the exception. That's the question! My API request returns JSON, and there is no way you can get access to it. 

The problem is not in handling the exception, but in getting the JSON response if an 4XX error occurs...

**Comment by juancarlospaco** [comment]
According to HTTP Standard:

> The reason-phrase or data element exists for the sole purpose of providing a
> textual description associated with the numeric status code, mostly
> out of deference to earlier Internet application protocols that were
> more frequently used with interactive text clients. 
> **A client SHOULD ignore the content.**

You can not expect the message or string or data to be there. 
Instead compare only the HTTP error code as intended by the Standard. 
Not my bug, basically an Error must not be another Data Endpoint on your API.
:shrug:
