### ISSUE TITLE
Add ability to use userangent and proxies like requests

### ISSUE THREAD

**Issue by DivineSentry** [juancarlospaco/faster-than-requests#71]
```import requests

proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}

requests.get('http://example.org', proxies=proxies)
```, likewise for headers

**Comment by juancarlospaco** [comment]
This is on the Documentation.
:/

**Comment by Akshat-mehrotra** [comment]
I think he meant something like this
`proxies1 = {
  'http': 'http://firstproxy',
}

requests.get('http://example.org', proxies=proxies1)
proxies2 = {
  'http': 'http://secondproxy',
}

requests.get('http://example.org', proxies=proxies2)
`
No need to go into environment variables, and can change proxies and headers on the fly

**Comment by juancarlospaco** [comment]
That is also on the Documentation.
:/
