### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by iLoooordFx** [juancarlospaco/faster-than-requests#72]
When im tryin to import the module i get this error
"ImportError: DLL load failed while importing faster_than_requests: %1 is not a valid Win32 application"

![image](https://user-images.githubusercontent.com/33207253/83312353-59d77b00-a1e8-11ea-8afe-cbb2019cbbd7.png)

**Comment by juancarlospaco** [comment]
Try the new version I just uploaded a minutes ago.

**Comment by iLoooordFx** [comment]
> Try the new version `0.9.9` I just uploaded a minutes ago.

im using it

**Comment by juancarlospaco** [comment]
You uninstalled the old version first ?.
Try a reboot maybe is cache on temporary files ?.
Python3.8 ?.
Everything is 64Bit ?.

**Comment by iLoooordFx** [comment]
I realized i was using python3.8 32 bits, i installed the 64version and intalled module from pypi.org, now i get 
"ModuleNotFoundError: No module named 'faster_than_requests'"
i compiled the source and put as the same folder as my project, now im getting
"ImportError: DLL load failed while importing faster_than_requests: The specified module could not be found"

**Comment by juancarlospaco** [comment]
- Can you paste all the terminal commands you used to properly understand what you done ?.
- `pip install nimporter` works ?.

**Comment by iLoooordFx** [comment]
Yes, `pip install nimporter` works.
installed module with `pip install faster-than-requests` and got the **ModuleNotFoundError**,
Then i compiled with  `nimble install nimpy` and
`nim c -d:ssl -d:danger --app:lib --out:faster_than_requests.pyd faster_than_requests.nim`
![image](https://user-images.githubusercontent.com/33207253/83313847-44654f80-a1ee-11ea-9167-9f338f5b09f6.png)

**Comment by juancarlospaco** [comment]
To test make a `.py` file with only:

```python
import nimporter
import faster_than_requests
```

Put it on an empty folder, with no other file in the same folder,
then try to run it from terminal using `python file.py` and that should work.

Update your `pip` it says is too old.

**Comment by iLoooordFx** [comment]
![image](https://user-images.githubusercontent.com/33207253/83314309-2c8ecb00-a1f0-11ea-9261-830dc920227d.png)

**Comment by juancarlospaco** [comment]
Please paste the output of the following commands from the terminal:

```
pip --version
python --version
nim --version
```

**Comment by iLoooordFx** [comment]
![image](https://user-images.githubusercontent.com/33207253/83314420-a626b900-a1f0-11ea-85c4-4dd77d7865e6.png)

**Comment by juancarlospaco** [comment]
Thats super weird, it should work, I cant think for a reason for it to not work
...maybe you can try with Docker for Windows ?.

**Comment by iLoooordFx** [comment]
i will try

**Comment by juancarlospaco** [comment]
Example here https://github.com/juancarlospaco/faster-than-requests/blob/master/docker/Dockerfile

**Comment by Akshat-mehrotra** [comment]
Same issue here, using 
pip 20.1.1
python 3.8
nim 1.2
on windows 64 bit

**Comment by juancarlospaco** [comment]
From Arch Linux I can build the file for Windows 64 Bit without any problems, 
I uploaded to the repo, you can download it, put it on the same folder of the `.py` file,
then just run it or import it, just `import faster_than_requests`.
The file can not be renamed.
Just for you, to see if it works.

https://github.com/juancarlospaco/faster-than-requests/blob/master/dist/faster_than_requests.pyd

**Comment by iLoooordFx** [comment]
> From Arch Linux I can build the file for Windows 64 Bit without any problems,
> I uploaded to the repo, you can download it, put it on the same folder of the `.py` file,
> then just run it or import it, just `import faster_than_requests`.
> The file can not be renamed. Windows 64Bit only.
> Just for you, to see if it works.
> 
> https://github.com/juancarlospaco/faster-than-requests/blob/master/dist/faster_than_requests.pyd

works perfectly, thanks

**Comment by juancarlospaco** [comment]
So then it was the Python packaging/install/distribution failing somehow.

Keep the file, you can just copy it anywhere or put it on the `/python-packages/` folder.

**Comment by Greg-Tarr** [comment]
> From Arch Linux I can build the file for Windows 64 Bit without any problems,
> I uploaded to the repo, you can download it, put it on the same folder of the `.py` file,
> then just run it or import it, just `import faster_than_requests`.
> The file can not be renamed. Windows 64Bit only.
> Just for you, to see if it works.
> 
> https://github.com/juancarlospaco/faster-than-requests/blob/master/dist/faster_than_requests.pyd

Can you please make this available again, I am experiencing the exact same problem.

**Comment by juancarlospaco** [comment]
https://github.com/juancarlospaco/faster-than-requests/releases/tag/1.0.0

**Comment by NerfDoriftar** [comment]
> From Arch Linux I can build the file for Windows 64 Bit without any problems, I uploaded to the repo, you can download it, put it on the same folder of the `.py` file, then just run it or import it, just `import faster_than_requests`. The file can not be renamed. Windows 64Bit only. Just for you, to see if it works.
> 
> https://github.com/juancarlospaco/faster-than-requests/blob/master/dist/faster_than_requests.pyd

I got same problem as described in this topic, tried to use your solution and this doesn't work for me....

Code libraries
![image](https://user-images.githubusercontent.com/12801054/142216652-06464da3-02cc-4af3-b0c9-faa8c9ec2de0.png)

DLL libraries in folder
![image](https://user-images.githubusercontent.com/12801054/142216798-7c79eb8a-c199-4a6e-83ef-c499876329fb.png)
