### ISSUE TITLE
import faster_than_requests as requests ModuleNotFoundError: No module named 'faster_than_requests'

### ISSUE THREAD

**Issue by f-dx** [juancarlospaco/faster-than-requests#73]
**Describe the bug**
Unable to import the library after installation 

import faster_than_requests as requests
ModuleNotFoundError: No module named 'faster_than_requests'

**To Reproduce**  import faster_than_requests as requests ModuleNotFoundError:
pip3 install faster_than_requests

**Desktop:**
 - OS: Ubuntu
 - Python version: 3.8.2
 - Version: 0.9.9

Previous version works fine

**Comment by juancarlospaco** [comment]
```python
import nimporter
import faster_than_requests
```
