### ISSUE TITLE
how to properly use the post requests?

### ISSUE THREAD

**Issue by iLoooordFx** [juancarlospaco/faster-than-requests#74]
hi, its me again
im getting a issue with the **post2str()**
**TypeError: post2str() missing 1 required positional argument: body**

my request is **request = requests.post2str(url, data=data)**

**Comment by juancarlospaco** [comment]
` body = "My Body Data Here" `
:)

**Comment by iLoooordFx** [comment]
```
body = {
	 "summoner": "devil",
 	 "region": "BR"
} 
request = requests.post(url, body=body)
```
SystemError: <built-in function post> returned NULL without setting an error

**Comment by juancarlospaco** [comment]
```python
request = requests.post2str(url, body = str(body) )
```

**Comment by juancarlospaco** [comment]
HTTP itself is all only strings over the wire anyways.

**Comment by iLoooordFx** [comment]
<3
