### ISSUE TITLE
ModuleNotFoundError: No module named 'faster_than_requests'

### ISSUE THREAD

**Issue by norgecantero** [juancarlospaco/faster-than-requests#75]
Python Version 3.8.1
Operating System Debian 9.5
faster_than_requests version 0.9.9

#!/usr/bin/env python3.8

import nimporter
import faster_than_requests

**Comment by vspiridonov** [comment]
**Same problem with me.**
(base) macbook85:test_faster vspirid$ python ts.py 
Traceback (most recent call last):
  File "ts.py", line 1, in <module>
    import faster_than_requests as requests
ModuleNotFoundError: No module named 'faster_than_requests'
(base) macbook85:test_faster vspirid$ python --version
Python 3.7.6
(base) macbook85:test_faster vspirid$ pip list | grep 'faster'
faster-than-requests               0.9.9

**Comment by juancarlospaco** [comment]
Run this on your PC it should tell you what you theoretically have installed on your PC:

Python:
```python
from importlib.metadata import distribution
from pprint import pprint
pprint(distribution("faster-than-requests").files)
```

Bash
```console
$ sudo updatedb
$ locate faster_than_requests
```

Paste the results here.

**Comment by norgecantero** [comment]
admin@ip-172-26-12-164:~$ locate faster_than_requests
/usr/local/lib/python3.8/site-packages/faster_than_requests-0.9.9-py3.8.egg-info
/usr/local/lib/python3.8/site-packages/faster_than_requests-0.9.9-py3.8.egg-info/PKG-INFO
/usr/local/lib/python3.8/site-packages/faster_than_requests-0.9.9-py3.8.egg-info/SOURCES.txt
/usr/local/lib/python3.8/site-packages/faster_than_requests-0.9.9-py3.8.egg-info/dependency_links.txt
/usr/local/lib/python3.8/site-packages/faster_than_requests-0.9.9-py3.8.egg-info/installed-files.txt
/usr/local/lib/python3.8/site-packages/faster_than_requests-0.9.9-py3.8.egg-info/requires.txt
/usr/local/lib/python3.8/site-packages/faster_than_requests-0.9.9-py3.8.egg-info/top_level.txt

**Comment by norgecantero** [comment]
How i can resolve this issue?

**Comment by juancarlospaco** [comment]
We are working on fixing this, is the Python toolchain for installation acting weird,
not our code, but should be possible to workaround it, I am working like right now.

If is really an urgency, you can always Git clone and Compile, is also on the documentation too.
:)

**Comment by norgecantero** [comment]
Thank you very much for your fast response.

**Comment by juancarlospaco** [comment]
Fixed.
Tested on Windows and Linux.

**Comment by RobDeepLearning** [comment]
Hello Juan Carlos,

I encounter the same issue as above, both on my Linux and Mac machines:
`/usr/project/.git/logs/refs/heads/use_faster_than_requests
/usr/project/.git/refs/heads/use_faster_than_requests
/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info
/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info/PKG-INFO
/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info/SOURCES.txt
/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info/dependency_links.txt
/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info/installed-files.txt
/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info/requires.txt
/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info/top_level.txt
`
