### ISSUE TITLE
is it possible to ignore SSL certificates? 

### ISSUE THREAD

**Issue by alexander-ae** [juancarlospaco/faster-than-requests#76]
In a similar way to how requests works:

https://requests.readthedocs.io/en/master/user/advanced/#ssl-cert-verification

    requests.get('https://kennethreitz.org',` verify=False)

**Comment by Yardanico** [comment]
@juancarlospaco IMO this is a very bad solution and potentially a security issue as it disables certificate validation for ALL requests. You should instead use a custom SSL context as in https://nim-lang.org/docs/net.html#newContext%2Cstring%2Cstring%2Cstring%2Cstring%2Cstring , and if a user passes `verify = False`, set `verifyMode` to `CVerifyNone`

**Comment by juancarlospaco** [comment]
Pull Requests Welcome.

**Comment by hanfu** [comment]
Module is installed using pip and it seems still doing SSL check.  Should I build myself?
