### ISSUE TITLE
Hello Juan Carlos,

### ISSUE THREAD

**Issue by RobDeepLearning** [juancarlospaco/faster-than-requests#77]
Hello Juan Carlos,

I encounter the same issue as above, both on my Linux and Mac machines:
`/usr/project/.git/logs/refs/heads/use_faster_than_requests`
`/usr/project/.git/refs/heads/use_faster_than_requests`
`/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info`
`/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info/PKG-INFO`
`/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info/SOURCES.txt`
`/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info/dependency_links.txt`
`/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info/installed-files.txt`
`/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info/requires.txt`
`/usr/PycharmProjects/Pip_VirtualEnv/lib/python3.7/site-packages/faster_than_requests-0.9.9-py3.7.egg-info/top_level.txt`

_Originally posted by @RobDeepLearning in https://github.com/juancarlospaco/faster-than-requests/issues/75#issuecomment-641878865_

**Comment by hanfu** [comment]
how to install v. 1.0?
pip install faster-than-requests==1.0
ERROR: Could not find a version that satisfies the requirement faster-than-requests==1.0 (from versions: 0.1, 0.5, 0.9.2, 0.9.6, 0.9.8, 0.9.9)
