### ISSUE TITLE
Script crashing while running download2() in threaded mode

### ISSUE THREAD

**Issue by SnappierSoap318** [juancarlospaco/faster-than-requests#78]
code:
```
import json
import os
import faster_than_requests as requests

urls = []
with open('r-wallpaper-Top-100-results.json', 'r') as files:
    posts = json.load(files)
    for i in range(1, 100):
        for data in posts['Post ' + str(i)]:
            img_links = posts['Post ' + str(i)]['URL']
            file_path = os.getcwd() + posts['Post ' + str(i)]["Title"]+".jpg"
            urls.append([img_links, file_path])
requests.download2(urls,threads = True)
```
OS: Windows, using WSL 
errors which kept coming up after a few iterations 

`
oserr.nim(94) raiseOSError Error: unhandled exception: Resource temporarily unavailable [OSError]
`
this came up after I ran the script again after getting the above error 
`
httpclient.nim(277) fileError Error: unhandled exception: Unable to open file [IOError]
`

**Comment by juancarlospaco** [comment]
is `urls` a list of tuples?.
Check that the filename is full path, it wont expand relative paths nor stuff like `~`.

**Comment by SnappierSoap318** [comment]
yep urls is a list of tuples and the filename is full path, and doesnt expand
