### ISSUE TITLE
nimpy.SslError: Unexpected error encountered: SSL Certificate check failed

### ISSUE THREAD

**Issue by z3dc0ps** [juancarlospaco/faster-than-requests#79]
Traceback (most recent call last):
  File "test1.py", line 5, in <module>
    r=requests.head("http://dev-on-business.nokia.com")
nimpy.SslError: Unexpected error encountered: SSL Certificate check failed.
![1](https://user-images.githubusercontent.com/61974788/85925234-af20ae00-b8b4-11ea-9289-430424a3d522.JPG)

**Comment by z3dc0ps** [comment]
![2](https://user-images.githubusercontent.com/61974788/85925495-6964e500-b8b6-11ea-9493-33770fbf255b.JPG)

**Comment by juancarlospaco** [comment]
You do not need `import nimporter` and you do not need `import nimpy` and all its related code.
