### ISSUE TITLE
cannot install on arch64(Termux)

### ISSUE THREAD

**Issue by dyseo** [juancarlospaco/faster-than-requests#8]
i have try install using pip with following command: `pip install faster_than_requests`

and got error like this

```
λ ~/ pip install faster_than_requests
Collecting faster_than_requests
  Using cached https://files.pythonhosted.org/packages/71/dd/b2160ca61114a35238bf9d5f5ccb88ca759b6d2f9246e6e13f4d263c270d/faster_than_requests-0.1.zip
Building wheels for collected packages: faster-than-requests
  Building wheel for faster-than-requests (setup.py) ... error
  ERROR: Complete output from command /data/data/com.termux/files/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-7chbh3m4/faster-than-requests/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /data/data/com.termux/files/usr/tmp/pip-wheel-kab5de04 --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_ext
  building 'faster_than_requests' extension
  creating build
  creating build/temp.linux-aarch64-3.7
  aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Oz -Oz -fPIC -I. -I/data/data/com.termux/files/usr/include/python3.7m -c stdlib_asyncstreams.c -o build/temp.linux-aarch64-3.7/stdlib_asyncstreams.o -flto -ffast-math -march=native -O3
  clang-8: error: the clang compiler does not support '-march=native'
  error: command 'aarch64-linux-android-clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel 
```

this not working not Termux or im forgot some necessary packages?

**Comment by juancarlospaco** [comment]
It needs GCC.
On your system is trying to use clang for some reason.

**Comment by dyseo** [comment]
> It needs GCC.
> On your system is trying to use clang for some reason.

how make sure i have clang on my system, before that i've install clang as well as i know with command line `pkg install clang`, idk this correct or not fot this lib

**Comment by juancarlospaco** [comment]
Refer to the documentation of your OS.
You need to have GCC.
You do Not need to have Clang.
You can run `gcc --version` to check if you have GCC.

**Comment by dyseo** [comment]
> Refer to the documentation of your OS.
> You need to have GCC.
> You do Not need to have Clang.
> You can run `gcc --version` to check if you have GCC.

λ ~/ gcc --version
clang version 8.0.0 (tags/RELEASE_800/final)
Target: aarch64-unknown-linux-android
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin

**Comment by juancarlospaco** [comment]
`gcc --version` should print something like:

```
gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.

```

Something on your SO is kinda very strange.
GCC seems replaced by Clang, but I am not sure.

**Comment by juancarlospaco** [comment]
Making it more explicit, if that helps of something: https://github.com/juancarlospaco/faster-than-requests/commit/69b30a4b3fe500409a5d7850b8f2510564e449ed

I dunno what to say, maybe try if it works with the Docker...
