### ISSUE TITLE
'get' takes only 1 argument (4 given) 

### ISSUE THREAD

**Issue by nocturn9x** [juancarlospaco/faster-than-requests#80]
- **Please paste the output of `faster_than_requests.debugs()`.**

```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in function debugs> returned NULL without setting an error
```
(Seriously? This library functions appear as builtin? lol) 

**Describe the bug**

As an introduction, this library is everything but a carefully designed piece of software. Considering its name I'd have expected a solid API, which by the way is completely different from requests and mostly for no particular reason. As for the bug, I've tried to use some keyword argument options with the `get` method, such as `proxyUrl` and `userAgent` with no success, without the extra parameters it works, but I need other options. I keep getting a `TypeError: 'get' takes exactly one arguments (4 given)`
(oh and btw camelCase names in a Python library? Did the developer even read PEP8 at all?) 
As for what implies other methods such as `put` or `get`, the behavior is even quirkier and nonsensical, because they just raise `SystemError`, which is actually a Python exception that occurs when something very bad happens in the interpreter, in this case the function has set its return value to `NULL` without setting an exception using CPython's API, which means nothing in Python. 

With such an ironical name I'd have at least loved if the library actually ever worked, lol. Gonna stick with requests, at least that's slow, but works as intended! (It's not the de-facto standard for no reason :)) 

**To Reproduce**
1. Just call `get` with more than one parameter

**Expected behavior**
Maybe accept the arguments that the documentation **explicitly** talks about? 

**Desktop (please complete the following information):**
 - OS: Debian 10 buster
 - Version 1.0 on Python 3.8.3

**Comment by juancarlospaco** [comment]
You are off by one version. :shrug: 

The code on master is being worked on, like literally right now, is like rolling release,
that will be the next version, tagged, versioned, etc eventually when ready.

**Comment by nocturn9x** [comment]
This does not explain why even basic functionality such as post is completely broken and unusable. Not to mention to absence for anything like a connection pooling mechanism.

**Comment by nocturn9x** [comment]
And also, how can I be off one version? I read an issue that is 18 days old where you state that the latest available version for Python 3.8 is 1.0.0, which is what I have

**Comment by juancarlospaco** [comment]
You are replying to yourself, the stuff on Git is not `1.0.0`.

**Comment by nocturn9x** [comment]
Did I mention git? I used pip, are you saying that the version on pip is completely outdated?

**Comment by juancarlospaco** [comment]
So, trying to understand and reach some kind of conclusion:

- This is not drop-in replacement of any pre-existent software.
- This is not camelCase, this is Style Agnostic.
- This may not follow PEP8, due to PEP8 limitations.
- I did not choose the name, the community named it on a live stream were it started.

:)
