### ISSUE TITLE
Cannot import faster_than_requests

### ISSUE THREAD

**Issue by Mental42** [juancarlospaco/faster-than-requests#81]
When I try to import faster_than_requests I get this error: 
Error: ImportError: DLL load failed: %1 is not a valid Win32 application
I am using a 64bit python in a 64bit computer

**Comment by juancarlospaco** [comment]
I dont know by that message what can be, the Python tooling to install is not too good for compiled stuff. :shrug: 
If it fails I recommend you just Git clone and compile it.
The GitHub Actions CI build every commit from zero with very basic commands (curl, etc),
also the Windows section explains how to do it too https://github.com/juancarlospaco/faster-than-requests#windows
also a lot of people just use Docker nowadays.
