### ISSUE TITLE
how to convert properly post requests

### ISSUE THREAD

**Issue by djaquilexe** [juancarlospaco/faster-than-requests#84]
how to convert this POST request from the regular :

`requests.post('https://github.com/', headers=headers, json=json)`

to a faster-than-request POST requests format ? if its possible.

**Comment by juancarlospaco** [comment]
```python
import faster_than_requests as requests

requests.post("http://httpbin.org/post", """{"foo": "bar", "baz": true}""", http_headers = my_headers_here)
```

- https://github.com/juancarlospaco/faster-than-requests/blob/master/examples/example.py#L6
- https://github.com/juancarlospaco/faster-than-requests/blob/master/examples/post_file.py
- Examples on the examples folder.
- Documentation on the readme.
