### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Sprajter** [juancarlospaco/faster-than-requests#86]
I don't know how to implement already installed in users/user and compiled ftr  so the "module not found" information won't pop.

**Comment by juancarlospaco** [comment]
I do not understand what you mean, please post the whole output of the terminal.

**Comment by Sprajter** [comment]
I have installed the git repository into "site_packages", compiled and it says 
![obraz](https://user-images.githubusercontent.com/65497812/90017379-bc023100-dcab-11ea-9f74-2d3bd7848046.png)

**Comment by Sprajter** [comment]
Ok, now it works
