### ISSUE TITLE
Unexpected error encountered: invalid integer

### ISSUE THREAD

**Issue by kootenpv** [juancarlospaco/faster-than-requests#9]
It imports, but doesn't work.

On Arch Linux using Python 3.7

```
In [9]: faster_than_requests.gets("https://github.com/kootenpv")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-692969b068e5> in <module>
----> 1 faster_than_requests.gets("https://github.com/kootenpv")

ValueError: Unexpected error encountered: invalid integer: 
```

**Comment by juancarlospaco** [comment]
It will try to return the response of an HTTP API:

```python
Python 3.7.3 (default, Mar 26 2019, 21:43:19)
[GCC 8.2.1 20181127] on linux

>>> import faster_than_requests
>>> faster_than_requests.gets("https://github.com/kootenpv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
nimpy.ValueError: Unexpected error encountered: invalid integer:

>>> faster_than_requests.gets("https://httpbin.org/get")
{'content-length': '148', 'content-type': 'application/json', 'headers': '{"date": ["Tue, 21 May 2019 22:44:00 GMT"], "x-xss-protection": ["1; mode=block"], "access-control-allow-credentials": ["true"], "x-frame-options": ["DENY"], "content-length": ["148"], "content-type": ["application/json"], "server": ["nginx"], "connection": ["keep-alive"], "access-control-allow-origin": ["*"], "x-content-type-options": ["nosniff"], "referrer-policy": ["no-referrer-when-downgrade"]}', 'version': '1.1', 'body': '{\n  "args": {}, \n  "headers": {\n    "Host": "httpbin.org"\n  }, \n  "origin": "190.136.xx.xx, 190.136.xx.xx", \n  "url": "https://httpbin.org/get"\n}\n', 'status': '200 OK'}
>>>
```

Try `faster_than_requests.gets("https://httpbin.org/get")` 
or `faster_than_requests.get2str("https://github.com/kootenpv")`
or `faster_than_requests.downloads("https://github.com/kootenpv", "file.html")`
or a full `requests()` or `requests2()`.

**Comment by kootenpv** [comment]
Ah, gets is like "get json"? Then I get it!

**Comment by juancarlospaco** [comment]
Yes, most of API use JSON, some very old API might use XML, but those are rarely seen, most of times you want computer readable data.

If you only want an string you can use get to string `get2str`.

But... if you consider this is not good, feel free to tinker with another API design, 
on the first versions we implemented stuff requested by people, mostly people doing 
data science, working with HTTP REST API, scraping, etc.
:slightly_smiling_face:

**Comment by kootenpv** [comment]
I would say you shouldn't add a scraper to this package - it sounds like you should make a scraping package that depends on this instead.

**Comment by juancarlospaco** [comment]
So we think we talked about the possible usages and way of working, then I will close this soon.

Please read the documentation on the readme and check the examples, we will try to improve UX on next version.

(Still some people say is a lot more friendly than PyCurl :P )
