### ISSUE TITLE
Can i use timeout, ?

### ISSUE THREAD

**Issue by machinexa2** [juancarlospaco/faster-than-requests#90]
There is no option to timeout like in requests 
![image](https://user-images.githubusercontent.com/60662297/94008156-3e5d3500-fdc2-11ea-8007-295a720ea3ae.png)
you will see there are no options to timeout when using help

**Comment by machinexa2** [comment]
even after waiting for 10-20 second when holding the request by burp it didnt timeout by default

**Comment by juancarlospaco** [comment]
`faster_than_requests.get(  timeout = 9000 )`

is Microseconds precision so multiply by 1000.

**Comment by machinexa2** [comment]
btw how can i specify 2 arguments

**Comment by machinexa2** [comment]
it gives error

**Comment by machinexa2** [comment]
@juancarlospaco

**Comment by machinexa2** [comment]
there is no example on how to use those arguments in README.md

**Comment by juancarlospaco** [comment]
`faster_than_requests.get( argument0 = "value", argument1 = "value",   )`

**Comment by machinexa2** [comment]
`>>> faster_than_requests.get('http://google.com', timeout = 9000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get() takes exactly 1 arguments (2 given)
>>> 
`

**Comment by machinexa2** [comment]
```python
>>> faster_than_requests.get('http://google.com', timeout = 9000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get() takes exactly 1 arguments (2 given)
>>> faster_than_requests.get(url = 'http://google.com', timeout = 9000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get() takes exactly 1 arguments (2 given)
>>> 
```

**Comment by machinexa2** [comment]
@juancarlospaco

**Comment by juancarlospaco** [comment]
Examples on the examples folder.

**Comment by machinexa2** [comment]
could you post an example in examples folder how to use timeout ?

**Comment by machinexa2** [comment]
i didnt find one

**Comment by juancarlospaco** [comment]
Looks like you are using old version, try:

```console
$ sudo pip3 install faster_than_requests==d4d03a6 --no-binary :all:
```

![temp](https://user-images.githubusercontent.com/1189414/94010425-4befcc00-fd7c-11ea-8196-3f5c83668d58.png)

**Comment by machinexa2** [comment]
thanks it works!, awesome bro nice work keep it up

**Comment by juancarlospaco** [comment]
![temp](https://user-images.githubusercontent.com/1189414/94010910-f36cfe80-fd7c-11ea-8a90-1acbe2a20da7.png)
