### ISSUE TITLE
How to avoid 'Connection was closed before full request has been made'?

### ISSUE THREAD

**Issue by meteoDaniel** [juancarlospaco/faster-than-requests#91]
I am using `get` and sometimes this error occures: 
``` 
nimpy.ProtocolError: Unexpected error encountered: Connection was closed before full request has been made
```

What are the reasons for this and how can I avoid it ? 

Btw. thanks a lot for this cool package it is really faster than requests.

**Comment by juancarlospaco** [comment]
Use a `try:  except: ` block and/or use a `sleep` before the call, then adjust the sleep time to the smallest possible, 
not perfect but works, sometimes the server may just cut you off when doing request too quickly or something like that.

**Comment by meteoDaniel** [comment]
@juancarlospaco sound weird but i will try this later and let you know if it works. Thanks a lot and have a great day!

**Comment by meteoDaniel** [comment]
Your solutions does not fix the problem. As I understand you right , having get processes in parallel could lead to this error? Because I am having an app and that triggers multiple downloads at the same time.

**Comment by meteoDaniel** [comment]
It appears when I am making a request ti my api for a secon time with a time lag of a few seconds.

**Comment by meteoDaniel** [comment]
My work around for now:
```
try:
    get(url)
except NimPyException:
    get(url)
```

**Comment by juancarlospaco** [comment]
Yeah thats basically what I was recommending you to try, is the correct work around.
:)

**Comment by meteoDaniel** [comment]
Do you know the origin of this error?

**Comment by juancarlospaco** [comment]
Try with the latest version, should be faster and better
`sudo pip install faster-than-requests==57c7862`
