### ISSUE TITLE
faster-than-requests fails to import due to undefined symbol "__builtin_ssubll_overflow" (using centos 7)

### ISSUE THREAD

**Issue by ahmadm890** [juancarlospaco/faster-than-requests#92]
When I try to import faster_than_requests I got this error:

"ImportError: /usr/local/lib/python3.8/site-packages/faster_than_requests.cpython-38-x86_64-linux-gnu.so: undefined symbol: __builtin_ssubll_overflow"

- I am using 64 Bit version of centos 7.
- I checked with python 3.8.5 and also 3.6.8

**Comment by juancarlospaco** [comment]
GCC must be `10.2.0` or higher.
Check that you are using the latest version `d4d03a6` of the package.

**Comment by ahmadm890** [comment]
I installed the new version of gcc, but the problem still continue.

**Comment by juancarlospaco** [comment]
Which version of GCC ?, run `gcc --version` and post the results.

This implements a faster way to detect overflows based on GCC’s `__builtin_sadd_overflow` family of functions.
Some versions of GCC lack this feature and unfortunately we cannot detect this case reliably.

This means the GCC is too old or your Distro is packaging GCC the wrong way.

**Comment by ahmadm890** [comment]
The gcc version is 10.2.0. After reinstalling the package, the problem is solved. Thank you for taking the time.
