### ISSUE TITLE
Serious bug: Ctrl + C Doesnt work and is very slow

### ISSUE THREAD

**Issue by machinexa2** [juancarlospaco/faster-than-requests#93]
`Linux kali-linux 5.8.0-kali2-amd64 #1 SMP Debian 5.8.10-1kali1 (2020-09-22) x86_64 GNU/Linux`
64 bit
So lets start
first bug is when doing get request i cant do Ctrl + C, please make sure i can cancel the request when taking too much time.
It causes so late that i need to pkill that process because Ctrl + C doesnt work. 
Second the most slowest library
![image](https://user-images.githubusercontent.com/60662297/94685323-fc476c80-0348-11eb-86c3-652fba5235c5.png)
Took nearly ages to do that

**Comment by machinexa2** [comment]
During that 56 second if i ctrl + c it doesnt work

**Comment by machinexa2** [comment]
Watch it yourself

**Comment by machinexa2** [comment]
Version: 
```
root@kali-linux:~/MachineYadav/My-Tools/JScanner# pip3 show faster_than_requests
Name: faster-than-requests
Version: 20.9.9
Summary: Faster & simpler requests replacement for Python
Home-page: https://github.com/juancarlospaco
Author: Juan Carlos
Author-email: juancarlospaco@gmail.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by: 
```

**Comment by machinexa2** [comment]
Even on https and http ctrl + C doesnt work and both https and http are equally slow though https is less slower than http but still fucking slow

**Comment by machinexa2** [comment]
looks like i am going to use requests for long time before moving on to this module

**Comment by juancarlospaco** [comment]
Your version is old.

Try with the latest version, should be faster and better:
`sudo pip install faster-than-requests==57c7862`

Do not use `get()`, use `get2tr()` or `get2str2()`.

Do not post a new message for each line, edit the top comment.

New speed up may land relatively soon too.

Use whatever you feel like using.

**Comment by machinexa2** [comment]
get2str works fast, get() doesnt thanks

**Comment by juancarlospaco** [comment]
It can be faster but the problem is Python objects are heavy,
functions return a Python `dict` and constructing that Python `dict` is slow,
it can be changed so functions return a `list` of `str` it is x10+ faster like `["body", "200",  ...]`,
or it can be changed so functions return a `tuple` of different types it is x10+ faster like `("body", 200,  ...)`.
:thinking:

**Comment by machinexa2** [comment]
nice @juancarlospaco
