### ISSUE TITLE
Somethings wrong with pypi package version number

### ISSUE THREAD

**Issue by meteoDaniel** [juancarlospaco/faster-than-requests#94]
I tried to update my `faster_than_requests` package and took the version number from pypi. 
``` 
The directory '/home/daniel/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/daniel/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting faster-than-requests==20.09.28
  Could not find a version that satisfies the requirement faster-than-requests==20.09.28 (from versions: 0.1, 0.5, 0.9.2, 0.9.6)
No matching distribution found for faster-than-requests==20.09.28
``` 

I guess the next valid version number after 0.9.6 is 0.9.7 or 0.10.0 or 1.0.0.

**Comment by juancarlospaco** [comment]
We use Rolling Release.

The version is just the Git commit short hash.

Example:
`sudo pip install faster-than-requests==57c7862`

**Comment by meteoDaniel** [comment]
Do you have a guide how to tell pip3 to use your git hashes as version? I am working with python for 5 years now and I have never heard about that, And it still does not work for my pip3 version `pip 9.0.1 from /usr/lib/python3/dist-packages`

**Comment by juancarlospaco** [comment]
Your PIP is old, `20.2.3` is the current version.

Tell pip to use the git hashes as version using `sudo pip install faster-than-requests==57c7862`
