### ISSUE TITLE
Crashes after some get requests

### ISSUE THREAD

**Issue by omertal323** [juancarlospaco/faster-than-requests#95]
After issuing the same get request for a few times, I get this error:
nimpy.OSError: Unexpected error encountered: Additional info: "IO error has occurred in the BIO layer"

any other request after that yeilds this:
nimpy.AssertionError: Unexpected error encountered: net.nim(1444, 9) `not socket.isClosed` Cannot `send` on a closed socket

**Comment by juancarlospaco** [comment]
https://github.com/juancarlospaco/faster-than-requests/issues/91#issuecomment-700141063
