### ISSUE TITLE
Problems with python 3.8 SLOW and failing compilation

### ISSUE THREAD

**Issue by JustDevZero** [juancarlospaco/faster-than-requests#96]
Hello,

I'm having problems with the library, a bunch of errors are trown during the instalation, but it's installed 'somehow'.

- You must have 64 Bit Python 3. Python 3.8.5
- You must have 64 Bit GCC Compiler: gcc (GCC) 10.2.1
- You must have 64 Bit Operating System: 5.6.6-300.fc32.x86_64

But, ignoring that, it works but tremendously slow, not 'faster than requests' but 'slower than htmllib' :(

Pastebin with the brutally big output on pip install:

https://pastebin.com/fWA25Kbd

```
timeit("import faster_than_requests as requests;requests.get('https://google.es')", number=10)
28.098495040998387
timeit("import requests as requests;requests.get('https://google.es')", number=10)
3.4597925010002655
```

**Comment by juancarlospaco** [comment]
Your version is old. 
We use Rolling Release, the version is just the Git commit short hash. Your PIP version should be `20.2.3` or newer.

The error message is a Bug on PIP, not my bug.
You can workaround the Bug adding to the install command ` --no-binary :all: `

Try with the latest version, should be faster and better:
`sudo pip install faster-than-requests==57c7862 --no-binary :all: `

Do not use `get()`, use `get2tr()`.

```console
$ python3 example.py
faster_than_requests    3.639932759000658
requests                8.083468799001275
```

```python
from timeit import timeit
print("faster_than_requests\t", timeit("requests.get2str('http://google.es')", setup="import faster_than_requests as requests",  number=10))
print("requests\t", timeit("requests.get('http://google.es')", setup="import requests as requests", number=10))
```

New speed up may land relatively soon too, we have no Sponsors nor Companies backing so is a lot of effort.

**Comment by JustDevZero** [comment]
OK, @juancarlospaco I tried directly with this instead and worked like a charm.

Also, the speed it's hella fast comparing with the previous test, so great for now.

Thanks!
