### ISSUE TITLE
Issue with importing after compiling

### ISSUE THREAD

**Issue by Evan99w** [juancarlospaco/faster-than-requests#98]
I followed all the steps mentioned in other posts and issues and after compiling the .pyd file and placing it with my .py when trying to import it I get the error below:
`could not load: (libcrypto-1_1-x64|libeay64).dll`
I've also tried running it form the terminal instead of from an IDE, no difference 
The specified dll's are in the nim bin folder so they should be included? Also recompiling made no difference. 
Any known fix or what am I doing wrong?

**Comment by juancarlospaco** [comment]
Copy the DLL on the same folder as the PYD.

**Comment by Evan99w** [comment]
Thanks, this worked
